### PR TITLE
Workerfarm improvements

### LINKED ISSUE #1286: Uncaught ReferenceError: process is not defined
### 🎛 Configuration (.babelrc, package.json, cli command)

```
{
  "name": "parcel-worker-error",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html --no-cache"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-custom-asset": "file:parcel-plugin-custom-asset"
  },
  "dependencies": {}
}
```

### 🤔 Expected Behavior

Start the server app without errors.

### 😯 Current Behavior

Parcel compile without problems but when I enter on `localhost:1234` I'm seeing the error:

```
Uncaught ReferenceError: process is not defined
    at Object.parcelRequire.4 (parcel-worker-error.e898f6f3.js:133)
    at newRequire (parcel-worker-error.e898f6f3.js:48)
    at parcelRequire.2 (parcel-worker-error.e898f6f3.js:75)
    at parcel-worker-error.e898f6f3.js:101
```

### 💁 Possible Solution

Is not a solution but I think this kind of errors start with the new feature of custom workerfarm in 1.7.1 and maybe the solution is the PR #1235 

### 🔦 Context

So, this issue is happening when we use some plugin that is extending a custom asset from JSAsset. In the code sample, you can see a simple test.

### 💻 Code Sample

https://github.com/tinchoz49/parcel-worker-error

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 10
| npm/Yarn         | npm 6
| Operating System | Manjaro xfce

### LINKED ISSUE #1319: Cannot read property 'run' of undefined
# 🐛 bug report

```
🚨  Cannot read property 'run' of undefined
    at /Users/nw/projects/motion/orbit/node_modules/parcel-bundler/lib/workerfarm/child.js:68:45
    at Generator.next (<anonymous>)
    at step (/Users/nw/projects/motion/orbit/node_modules/parcel-bundler/lib/workerfarm/child.js:3:191)
    at /Users/nw/projects/motion/orbit/node_modules/parcel-bundler/lib/workerfarm/child.js:3:437
    at new Promise (<anonymous>)
    at /Users/nw/projects/motion/orbit/node_modules/parcel-bundler/lib/workerfarm/child.js:3:99
    at Child.handleRequest (/Users/nw/projects/motion/orbit/node_modules/parcel-bundler/lib/workerfarm/child.js:75:7)
    at Child.messageListener (/Users/nw/projects/motion/orbit/node_modules/parcel-bundler/lib/workerfarm/child.js:36:19)
    at process.emit (events.js:185:15)
    at emit (internal/child_process.js:783:12)
```

## 🤔 Expected Behavior

This is on a small site I have working with 1.6.2, but 1.8.x seems to break. Mostly just would be helpful if there was more clear error messaging here so I could debug without binary searching.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.2
| Node             | 9
| Operating System | high sierra

### LINKED ISSUE #1548: Cannot read property 'process' of undefined
# 🐛 bug report

when run parcel build , it show me the error with "Cannot read property 'process' of undefined"
at Object.run (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/worker.js:23:27)
    at Child.handleRequest (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:59:49)
    at Child.messageListener (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:34:19)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

when I use MacOS 10.13.6，it work!
but when I use CentOS 7 ，it show the error

the nodejs version is the same with two Operating System, the nodejs version is 10.4.1
the only difference with those system is the NODE_ENV
I haven't ser NODE_ENV with MacOS
I set NODE_ENV=production with CentOS 7

The parcel 1.7.0 version is work find with two Operating System
this problem happen with parcel 1.9.0

the follow is my package.json description

  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html --public-url / --no-source-maps"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "vue-hot-reload-api": "^2.3.0",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.0.0",
    "iview": "^2.14.2",
    "parcel-bundler": "^1.9.0",
    "vue": "^2.5.16",
    "vue-template-compiler": "^2.5.16"
  }

## 🤔 Expected Behavior

build success

## 😯 Current Behavior

when run parcel build , it show me the error with "Cannot read property 'process' of undefined"
at Object.run (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/worker.js:23:27)
    at Child.handleRequest (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:59:49)
    at Child.messageListener (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:34:19)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

## 💁 Possible Solution

use parcel 1.7.0

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| parcel-plugin-vue | 1.9.0
| Parcel            | 1.9.0
| Vue                | 2.5.16
| Node             | 10.4.1 
| npm/Yarn      |  6.1.0
| Operating System  |  CentOS 7

### PR DESCRIPTION
**Pull request by DeMoorJasper**
* Passes bundler options to workerfarm
* Persists these bundler options to every worker
* Moved all previous initRemote code to worker
* Improved workerfarm end function (to 100% sure kill all processes that are idle)
* Less concurrent workerfarm calls for faster execution (due to less freezing and overloading)
* Don't use the workerfarm on single-threaded machines
* Assign the custom worker functions to the process

Closes #1548 Closes #1286 Closes #1319

### CODE REVIEW

File: src/workerfarm/WorkerFarm.js [hunk 1]
```diff
@@ -268,13 +256,8 @@ class WorkerFarm extends EventEmitter {
...
     }
 
-    let cores;
-    try {
-      cores = require('physical-cpu-count');
-    } catch (err) {
-      cores = os.cpus().length;
-    }
-    return cores || 1;
+    let cores = os.cpus().length;
```
Comment (devongovett) [inline src/workerfarm/WorkerFarm.js]: hmm, last time I tried this, it was much slower than using only the physical cpu count. why did you change it?

Comment (DeMoorJasper) [reply src/workerfarm/WorkerFarm.js]: Originally I changed it because I made the workers start on request, but that appeared to add about a second in build time. So I went back to starting all workers at the start of the workerfarm, which made it as fast as it originally was.
It should not differ that much os.cpus or real cpu count, I'd have to do some performance testing to make sure this doesn't really impact performance.

Comment (DeMoorJasper) [reply src/workerfarm/WorkerFarm.js]: Appears to be faster with `physical-cpu-count` as you said.

I've changed it back

**Comment by DeMoorJasper** [comment]
This PR appears to be stable on travis now. Ready for review :)

File: src/worker.js [hunk 2]
```diff
@@ -28,15 +20,16 @@ async function run(path, id, isWarmUp) {
 }
 
 // request.location is a module path relative to src or lib
-async function addCall(request, awaitResponse = true) {
-  if (process.send && process.env.PARCEL_WORKER_TYPE === 'remote-worker') {
-    return child.addCall(request, awaitResponse);
+function addCall(request, awaitResponse = true) {
```
[the remark this answers is not in the document]
Comment (DeMoorJasper) [reply src/worker.js]: Sounds like a great idea

File: src/workerfarm/child.js [hunk 3]
```diff
@@ -47,6 +38,11 @@ class Child {
     });
   }
 
+  childInit(module, childId) {
+    this.module = require(module);
```
[the remark this answers is not in the document]
Comment (DeMoorJasper) [reply src/workerfarm/child.js]: I think the only reason I can currently think of is performance.
I think the warmup workers will also become obsolete in this case.

**Comment by DeMoorJasper** [comment]
I've added some error throwing and changed `addCall` to `masterCall`.

However it caused a bug so I'll try get that out first

File: src/workerfarm/WorkerFarm.js [hunk 4]
```diff
@@ -275,8 +264,16 @@ class WorkerFarm extends EventEmitter {
     return cores || 1;
   }
 
+  static callMaster(request, awaitResponse = true) {
+    if (process.parcelWorker) {
+      return process.parcelRequest(request, awaitResponse);
```
Comment (devongovett) [inline src/workerfarm/WorkerFarm.js]: `child` is a singleton, so you could probably avoid attaching stuff to `process` by just requiring it here:

```javascript
if (process.send) {
  let child = require('./child');
  return  child.addCall(request, awaitResponse);
}
// ...
```

File: src/workerfarm/child.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (devongovett) [reply src/workerfarm/child.js]: Maybe - requires are cached though, so should only be a large perf hit the first time anyway. Worth testing it out.

File: src/workerfarm/WorkerFarm.js (hunk 4 above)
Comment (DeMoorJasper) [reply src/workerfarm/WorkerFarm.js]: Just checking process.send is pretty dangerous as parcel can be used as an api in a worker sandbox in node.js

File: src/workerfarm/child.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (DeMoorJasper) [reply src/workerfarm/child.js]: I remember experimenting with it in #1235 Ended up being an intense performance penalty (At the start).

Should be just as fast as now on larger codebases. It's just worrying on small codebases.

[the remark this answers is not in the document]
Comment (devongovett) [reply src/workerfarm/child.js]: sure

File: src/workerfarm/WorkerFarm.js (hunk 4 above)
Comment (devongovett) [reply src/workerfarm/WorkerFarm.js]: mmm, maybe something like `require.main === childModule`? That would check if the module the process launched with is the parcel child, which is basically what we want.

File: src/workerfarm/child.js [hunk 5]
```diff
@@ -10,23 +14,19 @@ class Child {
     this.responseId = 0;
     this.maxConcurrentCalls = 10;
 
-    process.env.PARCEL_WORKER_TYPE = 'remote-worker';
+    // Assigning parcelWorker variables to process
+    // Slightly improves the usability of bi-directional request
+    // in places that don't have access to child or workerfarm
+    // in a reliable way (for example the tests of Parcel)
+    process.parcelWorker = true;
+    process.parcelRequest = this.addCall.bind(this);
```
Comment (devongovett) [inline src/workerfarm/child.js]: looks like this is only used in the tests now? can the tests also just call `WorkerFarm.callMaster`?

Comment (DeMoorJasper) [reply src/workerfarm/child.js]: We'll have to handle node 6 and 8 but sure, I'll change. I'd like to keep `process.parcelWorker = true;`, unless you prefer the env variable as I mentioned earlier

File: src/Logger.js [hunk 6]
```diff
@@ -192,12 +192,12 @@ function stringWidth(string) {
 // If we are in a worker, make a proxy class which will
 // send the logger calls to the main process via IPC.
 // These are handled in WorkerFarm and directed to handleMessage above.
-if (process.send && process.env.PARCEL_WORKER_TYPE === 'remote-worker') {
-  const worker = require('./worker');
+if (process.parcelWorker) {
```
Comment (devongovett) [inline src/Logger.js]: Maybe `WorkerFarm.isWorker` for this check? That could be set as a static property to equal `require.main === childModule` in the worker farm.
