### PR TITLE
Bug fixes

### LINKED ISSUE #5833: Making a require conditional requires clearing the cache
# 🐛 bug report

Wrapping an existing dependency in an if statement doesn't wrap the dependency (with a cached build).

## 💁 Possible Solution

`dep.meta.shouldWrap` is overwritten when reading the dependency from cache?

## 💻 Code Sample

```js
// if (Date.now() < 0) {
	const x = require("./something");

	console.log(x);
// }
```

1. `parcel build index.js`
2. Comment in the first and last line
3. `parcel build index.js`. `something` is still being executed. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 560d06051b36b3f5703848bba801996f351c4ab4

### LINKED ISSUE #6428: [V2] axios xhr.js fails with cookies.read is not a function
# 🐛 bug report

I'm try to move a CRA/Webpack application to parcel v2 but Axios fails with the following error

```
Failed to load TypeError: cookies.read is not a function
    dispatchXhrRequest xhr.js:110
    xhrAdapter index.f1aa576d.js:93571
    dispatchRequest dispatchRequest.js:52
    promise callback*request Axios.js:61
    method Axios.js:76
    wrap bind.js:9
....
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Just a package.json with "parcel": "next"

## 🤔 Expected Behavior

works like it does in the original CRA/Webpack application

## 😯 Current Behavior

Fails in Axios code with

```
Failed to load TypeError: cookies.read is not a function
    dispatchXhrRequest xhr.js:110
    xhrAdapter index.f1aa576d.js:93571
    dispatchRequest dispatchRequest.js:52
    promise callback*request Axios.js:61
    method Axios.js:76
    wrap bind.js:9
....
```

Setting a break point shows this

Bildschirmfoto 2021-06-08 um 19 06 45

This means axios does not expect to get back an Promise from the require-call the cookies object defined helpers/cookies.

## 🔦 Context

Impossible to fetch data

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | next
| Node             | 
| npm/Yarn         | yarn
| Operating System | OS-X

### LINKED ISSUE #6479: require.extensions becomes undefined.extensions
With 725 and Fedora 34, both node 12 & 14 I get the following;

Note; when wrapping this in a ```try``` the build works

```/* istanbul ignore else */
if (typeof require !== 'undefined' && undefined.extensions) {
    undefined.extensions['.handlebars'] = extension;
    undefined.extensions['.hbs'] = extension;
}
```
ERROR: TypeError: undefined has no properties

_Originally posted by @DaveO-Home in https://github.com/parcel-bundler/parcel/issues/6478#issuecomment-864428606_

### LINKED ISSUE #6505: Parcel messes up the cache and does `Error: Got unexpected undefined` until cleaning the cache - unsure what triggers it
# 🐛 bug report

When
a) Having a `babel.config.js`
and 
b) removing and re-adding the current working directory

parcel messes up it's cache and will no longer run without cleaning the cache

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip

## 🤔 Expected Behavior

Parcel invalidates the cache because it is inconsistent and rebuilds it.

## 😯 Current Behavior

Parcel won't run again until the cache is deleted.

```
Error: Got unexpected undefined
    at nullthrows (/private/tmp/parcel-infinity-loops/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:252:44)
    at loadRequestGraph (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:856:18)
    at async Function.init (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:820:17)
    at async Parcel._init (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/Parcel.js:460:50)
    at async Parcel.watch (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/Parcel.js:529:7)
    at async run (/private/tmp/parcel-infinity-loops/node_modules/parcel/lib/cli.js:342:9) {
  framesToPop: 1
}
```

## 💁 Possible Solution

Invalidate cache if it's invalid (lol)

## 🔦 Context

This issue popped up every now and then and I just cleaned cache but now I finally found out how to reproduce it. It's been happing since pre SWC.

## 💻 Code Sample

[parcel-unexpected-undefined.zip](https://github.com/parcel-bundler/parcel/files/6697010/parcel-unexpected-undefined.zip)

How to reproduce:
go unzip file and go into folder in two terminal windows

Window 1:
```
npm install
cd src
npm run serve
```

Now switch window:
Window 2 (cwd is the parent directory of src):
```
git add src
git stash
git stash pop
```

Go back to window 1:
press ctrl+c
```
npm run serve
```

you will get this error:
```
daniel@Daniels-MacBook-Pro src % npm run serve
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new <anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:58:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:48:30)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

now continue with this:
```
cd ../src/
npm run serve
```

et voilà:

```
daniel@Daniels-MacBook-Pro src % npm run serve

> serve
> parcel serve --port 1234 src/main.ts

Error: Got unexpected undefined
    at nullthrows (/private/tmp/parcel-unexpected-undefined/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/RequestTracker.js:252:44)
    at loadRequestGraph (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/RequestTracker.js:856:18)
    at async Function.init (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/RequestTracker.js:820:17)
    at async Parcel._init (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/Parcel.js:460:50)
    at async Parcel.watch (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/Parcel.js:529:7)
    at async run (/private/tmp/parcel-unexpected-undefined/node_modules/parcel/lib/cli.js:342:9) {
  framesToPop: 1
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.729+e63235f3|
| Node             |v16.3.0|
| npm/Yarn         |npm 7.15.1|
| Operating System |macOS 10.15.7 (19H1217)|

### LINKED ISSUE #6521: Invalidate cache when NODE_ENV changes
# 🐛 bug report

IF you set `NODE_ENV` to `production` and build using Parcel, and then set it to `test` and rebuild, Parcel will use the production cache,

```js
scripts {
    "build.test": "cross-env NODE_ENV=test parcel build --target main ./lib/main.js",
    "build": "cross-env NODE_ENV=production parcel build --target main ./lib/main.js",
}
```

```
npm run build && npm run build.test
```

## 🤔 Expected Behavior

Invalidate the cache when `NODE_ENV` changes. 

## 😯 Current Behavior

It reuses the production cache in the test build.

## 💁 Possible Solution

Clean `.parcel-cache`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2 nightly ~700
| Node             | All
| npm/Yarn         | All
| Operating System | All

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #6479. Fixes #6521. Fixes #6428. Fixes #5833. Fixes #6505.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.72s | -110.00ms |
| Cached | 478.00ms | +13.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.95s | -44.00ms |
| Cached | 397.00ms | -44.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/303308188280685122)**

File: packages/optimizers/terser/src/TerserOptimizer.js [hunk 1]
```diff
@@ -3,30 +3,45 @@
...
 import ThrowableDiagnostic, {escapeMarkdown} from '@parcel/diagnostic';
 
 import path from 'path';
 
 export default (new Optimizer({
-  async optimize({contents, map, bundle, options, getSourceMapReference}) {
+  async loadConfig({config, options}) {
+    let userConfig = await config.getConfigFrom(
+      path.join(options.entryRoot, 'index'),
+      ['.terserrc', '.uglifyrc', '.uglifyrc.js', '.terserrc.js'],
```
Comment (mischnic) [inline packages/optimizers/terser/src/TerserOptimizer.js]: While we're at it: uglify is being actively development now, so I think `.uglifyrc` shouldn't be used here

**Review by mischnic — APPROVED** [review]
