### PR TITLE
Worker bug fixes

### LINKED ISSUE #1635: --detailed-report always reports 0 bytes for size of sourcemap .map files
Somewhat similar to #1151, when I'm building a bundle and ask for a `--detailed-report`, I'm (erroneously) told that the generated sourcemap files were 0 bytes:

```
> filer@0.0.29 release /Users/humphd/repos/filer
> parcel build --global Filer src/index.js --out-file filer.min.js --detailed-report

✨  Built in 308ms.

dist/filer.min.js                                                     70.15 KB    79ms
├── node_modules/node-libs-browser/node_modules/buffer/index.js       19.52 KB    41ms
├── src/filesystem/implementation.js                                  17.96 KB    39ms
├── lib/intercom.js                                                    3.75 KB    39ms
├── src/filesystem/interface.js                                        3.12 KB     7ms
├── src/shell/shell.js                                                 3.06 KB    38ms
├── src/providers/websql.js                                            2.46 KB    12ms
├── lib/nodash.js                                                      2.33 KB    37ms
├── src/providers/indexeddb.js                                         1.95 KB    12ms
├── src/path.js                                                        1.69 KB     9ms
├── node_modules/node-libs-browser/node_modules/process/browser.js     1.68 KB     3ms
└── + 21 more assets

dist/filer.min.map                                                         0 B    73ms
~/repos/filer (parceljs *) $ ls -lah dist
total 2096
drwxr-xr-x   7 humphd  staff   224B 28 Jun 11:18 .
drwxr-xr-x  22 humphd  staff   704B 28 Jun 11:07 ..
-rw-r--r--   1 humphd  staff    70K 28 Jun 11:18 filer.min.js
-rw-r--r--   1 humphd  staff   278K 28 Jun 11:18 filer.min.map
``` 

The actual file on disk is `278K`.  It would be nice to know this, even if only so you didn't wrongly assume that that sourcemap didn't generate properly.

### LINKED ISSUE #5503: Async imports from workers don't work: 'Cannot find module'
# 🐛 bug report

## 🤔 Expected Behavior

The entry asset of the async bundle should be registered into `parcelRequire`

## 😯 Current Behavior

- `Uncaught (in promise) Error: Cannot find module '6CLGt'`

## 💁 Possible Solution

I think `isAssetReferencedByDependant` is wrong? There is no `parcelRequire.register()` in the async bundle

## 💻 Code Sample

`parcel build index.html`

```html
<script src="index.js"></script>
```
```js
// index.js
new Worker("./worker.js");

// worker.js
import("./async.js").then((v) => console.log("worker: async=", v));

// async.js
export const async = "async!";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  f89e5ef87fcb58e6131475b5218f188cc231a1d9

### LINKED ISSUE #5504: Async import from both worker and child worker: 'Cannot find module'
# 🐛 bug report

Doing async imports in nested workers doesn't work beacuse `./loaders/worker/js-loader` isn't available in the inner worker.

## 😯 Current Behavior

```
child-worker.b4a550ff.js:59 Uncaught Error: Cannot find module '2TfhN'
    at newRequire (child-worker.b4a550ff.js:59)
    at newRequire (child-worker.b4a550ff.js:43)
    at localRequire (child-worker.b4a550ff.js:81)
    at Object.1xm4F../loaders/worker/js-loader (child-worker.b4a550ff.js:144)
    at newRequire (child-worker.b4a550ff.js:69)
    at localRequire (child-worker.b4a550ff.js:81)
    at Object.39YhH../async.js (child-worker.b4a550ff.js:142)
    at newRequire (child-worker.b4a550ff.js:69)
    at child-worker.b4a550ff.js:118
    at child-worker.b4a550ff.js:141
```

## 💁 Possible Solution

This is probably because the context is actually the same between main and child worker, so Parcel thinks it can reuse the asset from a parent bundle?

## 💻 Code Sample

`parcel build index.html --no-scope-hoist`

```html
<script src="index.js"></script>
```
```js
// index.js
new Worker("./worker.js");

// worker.js
new Worker("./child-worker.js");
import("./async.js").then((v) => console.log("worker: async=", v));

// child-worker.js
import("./async.js").then((v) => console.log("child worker: async=", v));

// async.js
export const async = "async!";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  f89e5ef87fcb58e6131475b5218f188cc231a1d9

### LINKED ISSUE #5864: Parcel 2 does not include dependencies correctly in split bundles and Web Workers with scope hoisting disabled
# 🐛 bug report

Using the latest versions of Parcel 2, dependencies are incorrectly excluded from code split bundles and Worker bundles that are descendants of that code split _when scope hoisting is disabled._ This triggers a `Cannot find module '[id]'` on page load on sites built with the `parcel build` command.

Scope hoisting is still really buggy for us and we haven't been able to debug that, so it's disabled. I'll likely submit a separate issue for that.

## 🎛 Configuration (.babelrc, package.json, cli command)

Take a look at this repository: https://github.com/embarktrucks/parcel-split-webworker-issue

## 🤔 Expected Behavior

Parcel should include pertinent dependencies in split bundles and Worker bundles that descend from those.

## 😯 Current Behavior

A bunch of dependencies are excluded.

To try this out, copy [this repository](https://github.com/embarktrucks/parcel-split-webworker-issue) into your `parcel/` repository at `packages/examples/`, `cd` into the directory, and run:

```
yarn run parcel build --no-scope-hoist --no-cache index.html
```

You will get output similar to this:
```
dist/browser/index.fe0b0221.js                            70.25 KB    2.57s                     
├── ../../../node_modules/lodash/lodash.js                69.08 KB    417ms                     
└── Code from unknown sourcefiles                          1.17 KB      0ms                     

dist/browser/index.85b8c16e.js                              3.8 KB    974ms                     
├── Code from unknown sourcefiles                          1.29 KB      0ms                     
├── ../../runtimes/js/src/JSRuntime.js                       625 B     22ms                     
├── ../../runtimes/js/src/relative-path.js                   478 B     49ms                     
├── ../../runtimes/js/src/bundle-url.js                      447 B     50ms                     
├── ../../runtimes/js/src/loaders/browser/js-loader.js       407 B     45ms                     
├── ../../runtimes/js/src/cacheLoader.js                     282 B      9ms                     
├── ../../runtimes/js/src/bundle-manifest.js                 246 B     39ms                     
└── src/index.js                                              85 B    1.95s                     

dist/browser/split.0112a5d5.js                             1.61 KB    973ms                     
├── Code from unknown sourcefiles                          1.14 KB      0ms                     
├── ../../runtimes/js/src/get-worker-url.js                  221 B     51ms                     
├── ../../runtimes/js/src/JSRuntime.js                       157 B     23ms                     
└── src/split.js                                             105 B     36ms                     
# ^^ LODASH NOT INCLUDED

dist/browser/worker.f5b2ae32.js                            1.38 KB    974ms                     
└── src/worker.js                                             19 B    378ms                     
# ^^ LODASH NOT INCLUDED

dist/browser/index.html                                      223 B    972ms                     
└── index.html                                               228 B    1.82s                     
Done in 8.79s.  
```

If you look in the `worker.[hash].js` and `split.[hash].js` files, they point
to `lodash` but don't actually include it, triggering an error `Cannot find
module` on page load.

## 💁 Possible Solution

We fixed this by monkey-patching the `DefaultBundler` by commenting out [these lines](https://github.com/embarktrucks/parcel/blob/f28eaf60ac018d49d2176c563c86d09f84feaa8e/packages/bundlers/default/src/DefaultBundler.js#L410).

## 🔦 Context

We gate a ton of functionality behind splits + web workers because our web application is pretty complex. It appears that few users do this, so I imagine this is not covered by your tests.

## 💻 Code Sample

https://github.com/embarktrucks/parcel-split-webworker-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.577 and [current `master` commit](https://github.com/parcel-bundler/parcel/commit/f28eaf60ac018d49d2176c563c86d09f84feaa8e) |
| Node             | 15.4 |
| Yarn         | 1.22.5 |
| Operating System | Ubuntu 16.04 |

### LINKED ISSUE #5920: new Worker(new URL(...), { type: "module" }) results in invalid code
# 🐛 bug report

Trying latest nightly (2.0.0-nightly.607), code like this fails to transpile correctly:

```js
const worker = new Worker(new URL('./workerHelpers.js', import.meta.url), {
  type: 'module'
});
```

## 🤔 Expected Behavior

It results in something like

```js
new Worker('relative-path-after-bundling')
```

with URL transpiled to the bundled worker path and `type: 'module'` removed (because it's no longer an ESM).

## 😯 Current Behavior

It results in (`--no-optimize` for readability):

```js
const worker = new Worker(Promise.resolve($d15010e440eb1ef867c1e32ed9720f14$exports), {
  type: 'module'
});
```

which is obviously wrong, and results in browser trying to stringify the promise and then fetch URLs:

image

## 🔦 Context

I think this used to work on v2, but perhaps was broken as part of https://github.com/parcel-bundler/parcel/pull/5846 (or maybe earlier, idk). /cc @mischnic

### LINKED ISSUE #6562: Parcel 2 build failing with importScripts() is not supported in module workers.
# 🐛 bug report

The build passes with `parcel build public/index.html`
but when I run `parcel public/index.html` I get the below error:

```
🚨 Build failed.

@parcel/transformer-js: importScripts() is not supported in module workers.

  /Users/jessabyrne/projectrepos/project/node_modules/@loaders.gl/loader-utils/dist/esm/lib/library-utils/library-utils.js:66:12
    65 | 
  > 66 |   return "modules/".concat(moduleName, "/src/libs/").concat(library);
  >    |            ^
    67 | }
    68 | 
```

It seems to get far along but fails near the end. I've tried clearing both the `.cache` and `.parcel-cache` as well as removing `node_modules` and reinstalling. 

This happened after making some changes to fix other errors:

1. changing `<script async src="../src/index.tsx" type="text/javascript"></script>` to `<script async src="../src/index.tsx" type="module"></script>`
    
   2. Changing
```
          navigator
            .serviceWorker
            .register('service-worker.js')
```
to
```
          navigator
            .serviceWorker
            .register(new URL('service-worker.js', meta.url))
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
    "@parcel/transformer-raw": "^2.0.0-nightly.755",
    "@parcel/transformer-typescript-tsc": "^2.0.0-nightly.755",
    "parcel": "^2.0.0-nightly.753",
```

.parcelrc
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"],
    "*.{jpg,png,svg}": ["@parcel/transformer-raw"]
  }
}
```

babel.config.json
```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ]
}

```

## 🤔 Expected Behavior

task should build

## 😯 Current Behavior

build fails

## 💁 Possible Solution

Could be related to this issue: https://github.com/parcel-bundler/parcel/issues/5021
also perhaps this PR https://github.com/parcel-bundler/parcel/pull/6531

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.753
| Node             | v16.3.0
| npm/Yarn         | 7.15.1
| Operating System | osx Big Sur

### LINKED ISSUE #6579: URL in Worker constructor not being replaced with actual bundle URL
# 🐛 bug report

`new URL` isn't being replaced with some reference to the actual worker bundle

## 🎛 Configuration (.babelrc, package.json, cli command)

```
{
	"browserslist": "IE 11",
	"dependencies": {
		"parcel": "2.0.0-nightly.763"
	}
}

```

`yarn parcel build index.html --no-optimize --no-cache`

## 😯 Current Behavior

This is what the `type=module` page script bundle looks like:

```js
new Worker(new URL("./worker.js", _import.meta.url), {
    type: "module"
});
```

## 💻 Code Sample

https://github.com/mischnic/parcel-issue-6579

```html
<script type="module" src="index.js"></script>
```
```js
// index.js
new Worker(new URL("./worker.js", import.meta.url), { type: "module" });

// worker.js
console.log("worker")
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.763

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #6579. Fixes #5503. Fixes #5504. Fixes #5920. Fixes #5864. Fixes #6562. Fixes T-1102. Fixes T-1101.

* Fixes dynamic imports in workers with old browser targets. The runtime calls `importScripts` which would previously error for modules.
* Fixes `import` being renamed to `_import` by SWC for very old browser targets (ES3 reserved words pass).
* Relaxes importScripts error so it doesn't occur outside a worker context, or when passed a variable rather than a string literal (only allowed in script workers).
* Fixes workers that reference themselves, i.e. `new Worker('current-filename')`. This was a bug in bundling that caused the asset to be erroneously internalized due to the cycle.
* Disables shared bundles between different contexts, i.e. between the page and worker. This caused breakages because the wrong loaders could be added, and transformers might depend on the environment context. This will need to be revisited at some point.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.43s | +170.00ms |
| Cached | 410.00ms | -12.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 196.00ms | -13.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 209.00ms | +20.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 5.90s | -126.00ms |
| Cached | 355.00ms | -0.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/303938569923199553)**

**Review by DeMoorJasper — APPROVED** [review]

File: packages/core/integration-tests/test/html.js [hunk 1]
```diff
@@ -1649,26 +1649,31 @@ describe('html', function() {
...
-        type: 'js',
-        assets: ['worker.js'],
+        assets: ['worker.js', 'lodash.js'],
       },
     ]);
 
-    let lodashSibling = path.basename(
-      b.getBundles().find(v => v.getEntryAssets().length === 0).filePath,
-    );
+    // let lodashSibling = path.basename(
```
Comment (wbinnssmith) [inline packages/core/integration-tests/test/html.js:1674]: debug? or should this be removed?

Comment (devongovett) [reply packages/core/integration-tests/test/html.js:1674]: I left it in case we bring back shared bundles between page and worker...
