### PR TITLE
fix(sourcemaps): Handle null mappings properly

### LINKED ISSUE #1825: Sourcemaps: null mappings not working as expected
# 🐛 bug report

## 🤔 Expected Behavior

Null mappings should be mapped

## 😯 Current Behavior

Null mappings are being ignored

## 💁 Possible Solution

Don't ignore null mappings

## 🔦 Context

Comments by @loganfsmyth in #1755

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

This allows null mappings in parcels sourcemaps.
Creating more accurate sourcemaps.
Also adds a couple extra tests for sourcemaps, using the SourceMap class directly, giving a more in depth coverage of SourceMap

Closes #1825

Original PR: #1851

## 🚨 Test instructions

Run unit tests

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

File: packages/core/integration-tests/test/sourcemaps.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ const assert = require('assert');
 const fs = require('@parcel/fs');
 const path = require('path');
 const mapValidator = require('sourcemap-validator');
+const SourceMap = require('../src/SourceMap');
```
Comment (devongovett) [inline packages/core/integration-tests/test/sourcemaps.js]: Looks like the tests are failing because of this import. Maybe this test should be inside the `parcel-bundler` package rather than the integration tests?

Comment (DeMoorJasper) [reply packages/core/integration-tests/test/sourcemaps.js]: It probably should although maybe it would be a good idea to extract the sourcemap implementation in the future to allow plugins to use it?

Comment (devongovett) [reply packages/core/integration-tests/test/sourcemaps.js]: yeah eventually

**Comment by devongovett** [comment]
seems like some html minification tests are failing? doesn't seem related though
