### PR TITLE
Fix: more loosened React lib version check

### LINKED ISSUE #7335: React lib version check should be loosened more
# 🐛 bug report

React lib version check should cover extra cases before using semver.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"type": "module",
	"dependencies": {
		"clsx": "^1.1.1",
		"history": "^5.1.0",
		"preact": "https://pkg.csb.dev/preactjs/preact/commit/96082866/preact",
		"react-router-dom": "^6.0.2"
	},
	"devDependencies": {
		"parcel": "^2.0.1",
		"postcss": "^8.3.11",
		"vite": "^2.6.14"
	}
}
```

## 🤔 Expected Behavior

Build should run successfully.

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/transformer-js: Invalid comparator: https://pkg.csb.dev/preactjs/preact/commit/96082866/preact

  TypeError: Invalid comparator: https://pkg.csb.dev/preactjs/preact/commit/96082866/preact
  at Comparator.parse (/project/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:754:11)
  at new Comparator (/project/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:737:8)
  at Range.<anonymous> (/project/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:925:12)
  at Array.map (<anonymous>)
  at Range.parseRange (/project/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:924:13)
  at Range.<anonymous> (/project/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:867:17)
  at Array.map (<anonymous>)
  at new Range (/project/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:866:40)
  at Function.minVersion (/project/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:1306:11)
  at loadConfig (/project/node_modules/.pnpm/@parcel+transformer-js@2.0.1_@parcel+core@2.0.1/node_modules/@parcel/transformer-js/lib/JSTransformer.js:222:127)
```

## 💁 Possible Solution

https://github.com/parcel-bundler/parcel/blob/46fe00fec9d841563df43afa8439d955e22c6cec/packages/transformers/js/src/JSTransformer.js#L208-L210

I think the check here could just be simplified to:

```js
let minReactLibVersion = semver.valid(reactLibVersion)
	? semver.minVersion(reactLibVersion)?.toString()
	: null;
```

## 🔦 Context

npm, and other package managers supports installing packages from a tarball, alongside other things like specifying workspace packages with `workspace:` or even plain symlinking via `link:`.

[npm-install documentation](https://docs.npmjs.com/cli/v8/commands/npm-install)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | 17.1.0 |
| npm/Yarn         | pnpm 6.22.2 |
| Operating System | Arch Linux 5.15.2-217-tkg-pds |

### PR DESCRIPTION
**Pull request by Shinyaigeek**
# ↪️ Pull Request

Fixes: #7335 

Hi team :wave:

Currently, `JSTransformer`'s detection of React lib version in package.json is crashed when react lib is specified with URL (such as `https://pkg.csb.dev/preactjs/preact/commit/96082866/preact` ). I fixed this.

## 💻 Examples

**package.json**
```json

{
  "private": true,
  "dependencies": {
    "preact": "https://pkg.csb.dev/preactjs/preact/commit/96082866/preact"
  }
}


```

## 🚨 Test instructions

I added a test case to whether or not check parcel correctly work with react dependency specified with URL.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by Shinyaigeek** [comment]
some test related to this PR case  failed, I will fix later🙏

File: packages/transformers/js/src/JSTransformer.js [hunk 1]
```diff
@@ -209,8 +209,11 @@ export default (new Transformer({
           pkg?.dependencies?.[effectiveReactLib] ||
           pkg?.devDependencies?.[effectiveReactLib] ||
           pkg?.peerDependencies?.[effectiveReactLib];
+        reactLibVersion = reactLibVersion
+          ? semver.validRange(reactLibVersion)
+          : null;
         let minReactLibVersion =
-          reactLibVersion != null && reactLibVersion !== '*'
+          reactLibVersion !== null && reactLibVersion !== '*'
```
Comment (Shinyaigeek) [inline packages/transformers/js/src/JSTransformer.js:216]: I use `semver.validRange` instead of `semver.valid`, because `semver.valid` returns null with the input such as `17` so some test case will be failed. I use `semver.validRange` to avoid this. If you have another idea about this, I would appreciate it if you tell me.

**Review by devongovett — APPROVED** [review]
