### PR TITLE
Log warning instead of crash if image optimizer fails

### LINKED ISSUE #7096: Build fails during image optimization
# 🐛 bug report

My project fails to build with this error:

```
@parcel/optimizer-image: Sampling factors too large for interleaved scan

  Error: Sampling factors too large for interleaved scan
  at Object.optimize
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/optimizer-image/lib/ImageOptimizer.js:42:42)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async PackagerRunner.optimize
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:364:20)
  at async PackagerRunner.getBundleResult
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:255:15)
  at async PackagerRunner.getBundleInfo
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:239:9)
  at async PackagerRunner.run
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:160:183)
  at async Child.handleRequest
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/workers/lib/child.js:217:9)
```

This error message is very likely from libjpeg via sharp, so it’s likely trying to optimize one of my images. Sadly, the error message does not convey which image was being optimized.

For this particular project, I’d actually want to turn _off_ image optimization, but [the docs](https://parceljs.org/recipes/image/#configuration) don’t seem to tell me how to disable it (I tried adding an empty `sharp.config.js`, to no avail).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             | 16.4
| Operating System | MacOS M1

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

Partially fixes #7096 by no longer crashing if optimising of image fails.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
cc @surma regarding image copyright/license to include it in the repo

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.05s | -81.00ms |
| Cached | 298.00ms | -10.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.64s | +172.00ms |
| Cached | 441.00ms | -18.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.14m | -4.99s 🚀 |
| Cached | 1.61s | +10.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/pdfRenderer.48c56b00.js | 1.11mb | +0.00b | 52.05s | -4.65s 🚀 |
| dist/index.d173b989.js | 693.74kb | +0.00b | 52.01s | +10.82s ⚠️ |
| dist/editorView.8daeea01.js | 594.83kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/popup.64bc9a82.js | 209.67kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/index.53c272cd.js | 145.62kb | +0.00b | 52.01s | +10.82s ⚠️ |
| dist/Toolbar.e3ba4416.js | 107.23kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/media-viewer.d950776f.js | 74.93kb | +0.00b | 52.05s | -4.65s 🚀 |
| dist/card.8ef34b4f.js | 62.67kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/card.41e5c61a.js | 60.71kb | +0.00b | 52.05s | -4.65s 🚀 |
| dist/Modal.cd71eaf3.js | 45.33kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/js.660b75db.js | 17.25kb | +0.00b | 38.21s | -2.97s 🚀 |
| dist/ui.5d3f7adc.js | 14.94kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/smartMediaEditor.48c8cf63.js | 13.25kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/dropzone.e0209bf8.js | 12.15kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/workerHasher.11b8f69d.js | 11.83kb | +0.00b | 38.21s | -2.97s 🚀 |
| dist/index.faaa4035.js | 6.18kb | +0.00b | 52.05s | -4.65s 🚀 |
| dist/card.26823fa1.js | 5.77kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/media-viewer.a19e03bf.js | 4.50kb | +0.00b | 38.21s | -2.97s 🚀 |
| dist/media-viewer.21624a99.js | 3.93kb | +0.00b | 38.21s | -2.97s 🚀 |
| dist/EmojiPickerComponent.0482d6c0.js | 3.73kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/png-chunks-extract.5c9c0fb9.js | 3.58kb | +0.00b | 38.21s | -2.97s 🚀 |
| dist/index.c6306681.css | 3.47kb | +0.00b | 52.28s | -4.69s 🚀 |
| dist/dropzone.55bef257.js | 3.29kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/Modal.ecafad9e.js | 3.15kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/clipboard.df70240c.js | 2.93kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/ResourcedEmojiComponent.667554b4.js | 2.12kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/card.47672f0e.js | 2.04kb | +0.00b | 38.21s | -2.97s 🚀 |
| dist/browser.4e039ed7.js | 1.69kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/workerHasher.14be1ebc.js | 1.63kb | +0.00b | 52.05s | -4.65s 🚀 |
| dist/Modal.ca6d4d94.js | 1.16kb | +0.00b | 38.21s | -2.97s 🚀 |
| dist/media-card-analytics-error-boundary.c718a9a7.js | 1.12kb | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/media-picker-analytics-error-boundary.8b2547e5.js | 966.00b | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/media-viewer-analytics-error-boundary.c928a889.js | 966.00b | +0.00b | 52.05s | -4.65s 🚀 |
| dist/media-card-analytics-error-boundary.30f51dac.js | 962.00b | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/media-card-analytics-error-boundary.6e65cc90.js | 962.00b | +0.00b | 52.05s | -4.65s 🚀 |
| dist/simpleHasher.fc0d6100.js | 643.00b | +0.00b | 51.97s | +10.78s ⚠️ |
| dist/simpleHasher.57fb325c.js | 643.00b | +0.00b | 52.05s | -4.65s 🚀 |
| dist/index.html | 386.00b | +0.00b | 52.13s | -4.64s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/editorView.88c79e9e.js | 594.83kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/popup.64bc9a82.js | 209.67kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/Toolbar.e3ba4416.js | 107.23kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/Modal.cd71eaf3.js | 45.33kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/js.660b75db.js | 17.25kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/ui.5d3f7adc.js | 14.94kb | +0.00b | 39.06s | -12.28s 🚀 |
| dist/smartMediaEditor.48c8cf63.js | 13.25kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/dropzone.e0209bf8.js | 12.15kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/EmojiPickerComponent.0482d6c0.js | 3.73kb | +0.00b | 39.06s | -12.28s 🚀 |
| dist/png-chunks-extract.5c9c0fb9.js | 3.58kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/dropzone.55bef257.js | 3.29kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/clipboard.df70240c.js | 2.93kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/ResourcedEmojiComponent.667554b4.js | 2.12kb | +0.00b | 39.06s | -12.28s 🚀 |
| dist/browser.4e039ed7.js | 1.69kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/media-card-analytics-error-boundary.c718a9a7.js | 1.12kb | +0.00b | 39.06s | -12.29s 🚀 |
| dist/media-picker-analytics-error-boundary.8b2547e5.js | 966.00b | +0.00b | 39.06s | -12.29s 🚀 |
| dist/simpleHasher.fc0d6100.js | 643.00b | +0.00b | 39.06s | -12.28s 🚀 |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.22s | +123.00ms |
| Cached | 346.00ms | -70.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 579.68kb | +0.00b | 5.36s | -687.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/313535175374930496)**

**Comment by surma** [comment]
Haha! Yeah, you can use it :)

File: packages/optimizers/image/src/ImageOptimizer.js [hunk 1]
```diff
@@ -1,18 +1,33 @@
...
+      return {
+        contents: optimized.length < buffer.length ? optimized : buffer,
+      };
+    } catch (err) {
+      const filepath = bundle.getMainEntry()?.filePath;
+      const filename = filepath
+        ? relativePath(options.projectRoot, filepath)
+        : 'unknown';
+      logger.warn({
+        message: `Could not optimize image ${filename}: ${err.message}`,
```
Comment (mischnic) [inline packages/optimizers/image/src/ImageOptimizer.js]: 1.  Use `md` to escape characters in the filepath: https://github.com/parcel-bundler/parcel/blob/c444af0d739438be7c73e01b0f2a6b4ff10a0903/packages/namers/default/src/DefaultNamer.js#L58
2. I think this should use the regular `path.relative`, so that Windows users see the correct path separator
3. Sometimes we use cwd instead of the project root 🤷  https://github.com/parcel-bundler/parcel/blob/7d4d53a098755d3dd494eb28d593f1bb4d5c1ec7/packages/transformers/babel/src/config.js#L323-L332

**Review by mischnic — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
