### PR TITLE
Really no sourcemaps

### LINKED ISSUE #4390: Parcel 2 (latest nightly) generates a `.map` file with `--no-source-maps`.
# 🐛 bug report

Parcel 2 (latest nightly) generates a `.map` file with `--no-source-maps`.

To reproduce:

```
$ yarn parcel --version
2.0.0-nightly.180+a1a2515f

$ cat a.js
console.log(1 + 2);

$ rm -rf dist && yarn parcel build a.js && cat dist/a.js.map
dist/a.js    46 B     10ms
└── a.js     20 B    655ms

{"mappings":"AAAAA,QAAQC,IAAI","sources":["a.js"],"names":["console","log"],"version":3,"file":"a.js.map","sourcesContent":["console.log(1 + 2);\n"]}                                                                                          

$ rm -rf dist && y parcel build --no-source-maps a.js && cat dist/a.js.map
dist/a.js    46 B      2ms
└── a.js     20 B    655ms

{"mappings":"AACAA,QAAQC,IAAI","sources":["0"],"names":["console","log"],"version":3,"file":"a.js.map","sourcesContent":[null]}
```
With `--no-source-maps`, `dist/a.js.map` is still generated (it doesn't have `sourcesContent` though).

## 🤔 Expected Behavior

`.map` file should not be generated.

## 😯 Current Behavior

`.map` file is generated.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.180+a1a2515f
| Node             | v13.11.0
| npm/Yarn         | yarn 1.22.4
| Operating System | macOS 10.15.3

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Closes #4390

Previously, we relied on plugins to not return sourcemaps if `target.sourceMap` is false. 
But the non-hoisting JSPackager without running TerserOptimizer afterwards would still emit a sourcemap and therefore write a sourcemap file to dist despite of `--no-source-maps`

# Question

~Sourcemaps can be specified per target, but they are only accessible on `PluginOptions` (a boolean from the cli flag) and on `Target` (the actual settings object). So it would make sense to remove it from the `PluginOptions` and put them on `Target` only (and normalizing the value in the target resolver), but then transformers wouldn't know if sourcemaps are enabled.~

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.77s | +23.00ms |
| Cached | 2.32s | -137.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 285.00ms | +40.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 286.00ms | +42.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/kitchen-sink.32bb4226.js | 1.13kb | +0.00b | 416.00ms | -106.00ms 🚀 |
| dist/modern/kitchen-sink.280a0cce.js | 1.13kb | +0.00b | 415.00ms | -105.00ms 🚀 |
| dist/legacy/index.html | 709.00b | +0.00b | 418.00ms | -108.00ms 🚀 |
| dist/modern/index.html | 709.00b | +0.00b | 415.00ms | -105.00ms 🚀 |
| dist/legacy/styles.afb8e31a.css | 78.00b | +0.00b | 417.00ms | -105.00ms 🚀 |
| dist/modern/styles.cda8c91b.css | 78.00b | +0.00b | 415.00ms | -105.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.09s | +119.00ms |
| Cached | 2.31s | +66.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 66.80kb | +0.00b | 2.52s | +148.00ms ⚠️ |
| dist/module/index.js | 37.45kb | +0.00b | 2.52s | +147.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 66.80kb | +0.00b | 380.00ms | +74.00ms ⚠️ |
| dist/module/index.js | 37.45kb | +0.00b | 373.00ms | +69.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.10m | -4.60s |
| Cached | 4.99s | -185.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/ak-editor.74f8330f.js | 2.49mb | +3.00b ⚠️ | 1.76m | -7.25s 🚀 |
| dist/Toolbar.8b3d4b31.js | 100.43kb | +0.00b | 1.40m | -28.96s 🚀 |
| dist/EmojiPickerComponent.487f0492.js | 98.73kb | +0.00b | 19.56s | -8.36s 🚀 |
| dist/component.f5912f8e.js | 55.59kb | +0.00b | 8.04s | -1.47s 🚀 |
| dist/ui.62597f1b.js | 55.45kb | +0.00b | 30.90s | -2.41s 🚀 |
| dist/smartMediaEditor.ad2a3a1d.js | 55.41kb | +0.00b | 1.38m | -4.19s 🚀 |
| dist/Modal.e8e2dfed.js | 44.27kb | +0.00b | 4.96s | -453.00ms 🚀 |
| dist/component.57556120.js | 28.96kb | +0.00b | 9.27s | -804.00ms 🚀 |
| dist/EmojiPickerComponent.3437cc21.js | 22.43kb | +0.00b | 26.61s | -1.71s 🚀 |
| dist/clipboard.7fb7335e.js | 17.21kb | +0.00b | 49.69s | -36.46s 🚀 |
| dist/js.786dad09.js | 16.49kb | +0.00b | 4.96s | -4.18s 🚀 |
| dist/workerHasher.8c8d4944.js | 11.69kb | +0.00b | 24.36s | +2.48s ⚠️ |
| dist/16.fb3dbc8b.js | 10.08kb | +0.00b | 4.96s | -421.00ms 🚀 |
| dist/16.97fc5546.js | 9.97kb | +0.00b | 4.96s | -420.00ms 🚀 |
| dist/16.73638eb8.js | 9.91kb | +0.00b | 4.96s | -420.00ms 🚀 |
| dist/16.2eecf255.js | 9.86kb | +0.00b | 9.21s | +3.83s ⚠️ |
| dist/date.1c037d1c.js | 9.04kb | +0.00b | 11.03s | -908.00ms 🚀 |
| dist/images.92799093.js | 8.98kb | +0.00b | 11.03s | -1.35s 🚀 |
| dist/fallback.8bdaa9f9.js | 8.97kb | +0.00b | 13.52s | -2.14s 🚀 |
| dist/list-number.1316e9f7.js | 8.77kb | +0.00b | 12.22s | -1.02s 🚀 |
| dist/status.97878d50.js | 8.77kb | +0.00b | 13.52s | -944.00ms 🚀 |
| dist/link.c9af7470.js | 8.61kb | +0.00b | 12.22s | -1.02s 🚀 |
| dist/heading3.bcae1464.js | 8.60kb | +0.00b | 14.62s | -1.04s 🚀 |
| dist/emoji.8c2bc3de.js | 8.54kb | +0.00b | 11.03s | -45.58s 🚀 |
| dist/heading5.6844d092.js | 8.48kb | +0.00b | 14.62s | -2.51s 🚀 |
| dist/heading2.a19338b9.js | 8.42kb | +0.00b | 14.62s | -1.04s 🚀 |
| dist/mention.a261500a.js | 8.38kb | +0.00b | 12.22s | -1.02s 🚀 |
| dist/heading4.02eb6187.js | 8.37kb | +0.00b | 14.62s | -1.04s 🚀 |
| dist/layout.524db8d2.js | 8.36kb | +0.00b | 12.22s | -1.02s 🚀 |
| dist/divider.acfaa3b9.js | 8.33kb | +0.00b | 11.03s | -1.20s 🚀 |
| dist/quote.55197fd6.js | 8.33kb | +0.00b | 13.52s | -944.00ms 🚀 |
| dist/action.536bde1c.js | 8.31kb | +0.00b | 12.13s | +1.04s ⚠️ |
| dist/decision.5cdc67b3.js | 8.29kb | +0.00b | 11.03s | -908.00ms 🚀 |
| dist/panel-warning.cb245541.js | 8.29kb | +0.00b | 57.38s | +42.92s ⚠️ |
| dist/list.624b775a.js | 8.26kb | +0.00b | 12.22s | -1.02s 🚀 |
| dist/heading1.ef0290b4.js | 8.26kb | +0.00b | 14.62s | -1.04s 🚀 |
| dist/panel.6acb9fb3.js | 8.18kb | +0.00b | 13.52s | -944.00ms 🚀 |
| dist/table.500adb35.js | 8.18kb | +0.00b | 13.52s | -944.00ms 🚀 |
| dist/16.073347bf.js | 5.24kb | +0.00b | 9.67s | -1.08s 🚀 |
| dist/16.c4ee6c00.js | 5.17kb | +0.00b | 8.04s | -2.21s 🚀 |
| dist/16.7f86346a.js | 4.89kb | +0.00b | 8.95s | -1.02s 🚀 |
| dist/16.263c7d86.js | 4.84kb | +0.00b | 8.04s | -1.23s 🚀 |
| dist/16.5f13de00.js | 4.84kb | +0.00b | 8.95s | -1.02s 🚀 |
| dist/16.51c4a0ba.js | 4.82kb | +0.00b | 12.05s | -637.00ms 🚀 |
| dist/16.61fcf150.js | 4.78kb | +0.00b | 9.69s | -2.83s 🚀 |
| dist/16.7b85ceeb.js | 4.73kb | +0.00b | 9.67s | -1.08s 🚀 |
| dist/16.ba932c2e.js | 4.70kb | +0.00b | 9.68s | -1.07s 🚀 |
| dist/16.232fb9da.js | 4.69kb | +0.00b | 12.05s | -772.00ms 🚀 |
| dist/16.60895c0e.js | 4.65kb | +0.00b | 8.95s | -1.30s 🚀 |
| dist/16.a6594cea.js | 4.64kb | +0.00b | 8.04s | -3.03s 🚀 |
| dist/16.8a21dead.js | 4.64kb | +0.00b | 8.95s | -1.02s 🚀 |
| dist/16.ba7ed30e.js | 4.64kb | +0.00b | 8.95s | -1.05s 🚀 |
| dist/16.ea6e7d4b.js | 4.63kb | +0.00b | 8.04s | -1.10s 🚀 |
| dist/16.ba0c7d86.js | 4.56kb | +0.00b | 9.69s | -1.08s 🚀 |
| dist/ak-editor.47799eae.css | 3.43kb | +0.00b | 1.78m | +1.66m ⚠️ |
| dist/EmojiUploadComponent.b1f515dc.js | 2.53kb | +0.00b | 27.49s | -3.19s 🚀 |
| dist/ResourcedEmojiComponent.4495d16e.js | 2.32kb | +0.00b | 9.21s | -813.00ms 🚀 |
| dist/media-card-analytics-error-boundary.1e65f6fd.js | 1.68kb | +0.00b | 33.49s | -17.43s 🚀 |
| dist/workerHasher.853c799b.js | 1.67kb | +0.00b | 23.98s | +2.09s ⚠️ |
| dist/simpleHasher.3db92b55.js | 642.00b | +0.00b | 23.98s | +2.09s ⚠️ |
| dist/index.html | 212.00b | +0.00b | 1.20s | -6.97s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/ak-editor.74f8330f.js | 2.49mb | +0.00b | 634.00ms | +91.00ms ⚠️ |
| dist/pdfRenderer.7bec20fe.js | 1.13mb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/editorView.b8479877.js | 587.00kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/popup.90029bd6.js | 218.06kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/esm.672cd889.js | 138.03kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/Toolbar.8b3d4b31.js | 100.43kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/EmojiPickerComponent.487f0492.js | 98.73kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/media-viewer.30301157.js | 71.17kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/card.2f962421.js | 67.80kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/component.f5912f8e.js | 55.59kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/ui.62597f1b.js | 55.45kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/smartMediaEditor.ad2a3a1d.js | 55.41kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/Modal.e8e2dfed.js | 44.27kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/component.57556120.js | 28.96kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/png-chunks-extract.883f0434.js | 25.63kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/EmojiPickerComponent.3437cc21.js | 22.43kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/DatePicker.1dd284a0.js | 21.61kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/dropzone.68e03498.js | 17.75kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/clipboard.7fb7335e.js | 17.21kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/js.786dad09.js | 16.49kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/browser.4d8e9d5b.js | 16.08kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/workerHasher.8c8d4944.js | 11.69kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/16.fb3dbc8b.js | 10.08kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/16.97fc5546.js | 9.97kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/16.73638eb8.js | 9.91kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/16.2eecf255.js | 9.86kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/EmojiTypeAheadComponent.a96819ac.js | 9.31kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/date.1c037d1c.js | 9.04kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/images.92799093.js | 8.98kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/fallback.8bdaa9f9.js | 8.97kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/feedback.bffa274a.js | 8.95kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/list-number.1316e9f7.js | 8.77kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/status.97878d50.js | 8.77kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/code.6b50d9e2.js | 8.69kb | +0.00b | 632.00ms | +90.00ms ⚠️ |
| dist/link.c9af7470.js | 8.61kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/heading6.6daffbba.js | 8.61kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/heading3.bcae1464.js | 8.60kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/emoji.8c2bc3de.js | 8.54kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/heading5.6844d092.js | 8.48kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/expand.1a4c120f.js | 8.46kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/heading2.a19338b9.js | 8.42kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/mention.a261500a.js | 8.38kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/heading4.02eb6187.js | 8.37kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/layout.524db8d2.js | 8.36kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/divider.acfaa3b9.js | 8.33kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/quote.55197fd6.js | 8.33kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/action.536bde1c.js | 8.31kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/decision.5cdc67b3.js | 8.29kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/panel-warning.cb245541.js | 8.29kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/list.624b775a.js | 8.26kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/heading1.ef0290b4.js | 8.26kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/panel-error.8bc896be.js | 8.19kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/panel.6acb9fb3.js | 8.18kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/table.500adb35.js | 8.18kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/panel-success.7636d22e.js | 8.13kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/panel-note.2eea2289.js | 8.13kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.073347bf.js | 5.24kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.c4ee6c00.js | 5.17kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.7f86346a.js | 4.89kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.263c7d86.js | 4.84kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.5f13de00.js | 4.84kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.51c4a0ba.js | 4.82kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/16.61fcf150.js | 4.78kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/16.7b85ceeb.js | 4.73kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.ba932c2e.js | 4.70kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.232fb9da.js | 4.69kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/16.60895c0e.js | 4.65kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.a6594cea.js | 4.64kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.8a21dead.js | 4.64kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.ba7ed30e.js | 4.64kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.ea6e7d4b.js | 4.63kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/16.ba0c7d86.js | 4.56kb | +0.00b | 633.00ms | +92.00ms ⚠️ |
| dist/EmojiPickerComponent.29136bfe.js | 3.78kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/ak-editor.47799eae.css | 3.43kb | +0.00b | 631.00ms | +91.00ms ⚠️ |
| dist/EmojiUploadComponent.b1f515dc.js | 2.53kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/ResourcedEmojiComponent.4495d16e.js | 2.32kb | +0.00b | 633.00ms | +91.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.a8ed833d.js | 1.69kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.1e65f6fd.js | 1.68kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/workerHasher.853c799b.js | 1.67kb | +0.00b | 632.00ms | +91.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.62b79dc4.js | 1.59kb | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/simpleHasher.3db92b55.js | 642.00b | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/EmojiPickerComponent.39e7a3dc.js | 467.00b | +0.00b | 632.00ms | +92.00ms ⚠️ |
| dist/index.html | 212.00b | +0.00b | 635.00ms | +88.00ms ⚠️ |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/263700894726488586)**

File: packages/core/core/src/TargetResolver.js [hunk 1]
```diff
@@ -139,7 +139,7 @@ export default class TargetResolver {
               scopeHoist:
                 this.options.scopeHoist && descriptor.scopeHoist !== false,
             }),
-            sourceMap: descriptor.sourceMap,
+            sourceMap: this.options.sourceMaps && descriptor.sourceMap,
```
Comment (mischnic) [inline packages/core/core/src/TargetResolver.js:142]: Now `--no-sourcemaps` overrides `targets.*.sourceMaps`
