### PR TITLE
Bug fixes

### LINKED ISSUE #6199: Could not find target with name ...
# 🐛 bug report

When running a build with what seems like a valid configuration, I get a cryptic error about an unexpected undefined.

## 🎛 Configuration (.babelrc, package.json, cli command)

I have 3 targets defined in my package.json:

```json
  "main": "dist/main.js",
  "renderer": "dist/index.html",
  "splash": "dist/splash.html",
  "targets": {
    "main": {
      "context": "electron-main",
      "distDir": "./dist",
      "source": "./app/main.js"
    },
    "renderer": {
      "context": "electron-renderer",
      "publicUrl": ".",
      "distDir": "./dist",
      "source": "./app/renderer/index.html",
      "includeNodeModules": [
        "@appium/gui-libs"
      ]
    },
    "splash": {
      "context": "electron-renderer",
      "publicUrl": ".",
      "distDir": "./dist",
      "source": "./app/renderer/splash.html"
    }
  },
```

## 🤔 Expected Behavior

I expect to be able to run e.g. `npx parcel build --target renderer .` and have a bundle generated. I'm attempting to keep as much information as possible in the config and as little on the CLI, so I figured specifying a target and a directory-style argument `.` would do that.

## 😯 Current Behavior

Instead, I get this, no matter what target I choose:

```
Error: Got unexpected undefined
    at nullthrows (/Users/jlipps/Code/appium/appium-desktop/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/RequestTracker.js:245:44)
    at loadRequestGraph (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/RequestTracker.js:831:18)
    at async Function.init (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/RequestTracker.js:792:17)
    at async Parcel._init (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/Parcel.js:481:50)
    at async Parcel.run (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/Parcel.js:518:7)
    at async run (/Users/jlipps/Code/appium/appium-desktop/node_modules/parcel/lib/cli.js:377:7) {
  framesToPop: 1
}
```

## 💻 Code Sample

[split-apps branch at the Appium Desktop repo](https://github.com/appium/appium-desktop/tree/split-apps)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 12.21.0
| npm/Yarn         | 7.5.6
| Operating System | Darwin 19.6.0

### LINKED ISSUE #6605: '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first'
# 🐛 bug report

Importing an MDX file causes a Rust panic

## 😯 Current Behavior

```
@parcel/transformer-js: cannot access a scoped thread local variable without calling `set` first

  Error: cannot access a scoped thread local variable without calling `set` first
  at Object.transform (packages/transformers/js/src/JSTransformer.js:371:9)
  at Transformation.runTransformer (packages/core/core/src/Transformation.js:760:7)
  at Transformation.runPipeline (packages/core/core/src/Transformation.js:403:36)
  at Transformation.runPipelines (packages/core/core/src/Transformation.js:260:29)
  at Transformation.runPipelines (packages/core/core/src/Transformation.js:306:34)
  at Transformation.run (packages/core/core/src/Transformation.js:174:19)
  at Object.run (packages/core/core/src/requests/AssetRequest.js:135:8)
  at RequestTracker.runRequest (packages/core/core/src/RequestTracker.js:831:20)
  at AssetGraphBuilder.runAssetRequest (packages/core/core/src/requests/AssetGraphRequest.js:815:18)
  at PromiseQueue._runFn (packages/core/utils/src/PromiseQueue.js:85:7)
```

## Context

"last working run was June 29, so likely a regression in 2.0.0-nightly.746"

## 💻 Code Sample

`parcel build index.js`

```js
// index.js
import page from "./page.mdx";
console.log(page);


// page.mdx
# Hello, world!
```

package.json:
```json
{
  "dependencies": {
    "@mdx-js/mdx": "^1.6.22",
    "@mdx-js/react": "^1.6.22",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-select": "^4.3.1"
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | fd99fa043c2dffe946543c501beff90094f9f703

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #6605. Fixes #6199.

* Always adds `@jsxRuntime classic` to compiled MDX
* Fixes the `--target` option when combined with targets that have a `source` field.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.20s | +115.00ms |
| Cached | 402.00ms | -3.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 179.00ms | -15.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 5.94s | +42.00ms |
| Cached | 346.00ms | -12.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/305152403000263233)**

File: packages/core/core/src/requests/TargetRequest.js [hunk 1]
```diff
@@ -154,7 +154,7 @@ export class TargetResolver {
       optionTargets = [exclusiveTarget];
     }
 
-    let packageTargets = await this.resolvePackageTargets(
+    let packageTargets: Map<string, ?Target> = await this.resolvePackageTargets(
```
Comment (wbinnssmith) [inline packages/core/core/src/requests/TargetRequest.js]: nit: `Map<string, Target | null>`? It's not really a maybe target, it's more a target or the "skipped" value null

**Review by wbinnssmith — APPROVED** [review]
