### PR TITLE
Fix bugs with web manifests

### LINKED ISSUE #1764: Parcel incorrectly converts linked json to Javascript
# 🐛 bug report

Some user agents require a `<link />` tag with some **actual JSON** (not JSON-compatible JS module). Unfortunately there seems to be no way to prevent Parcel from converting it into some JS module nonsense.

## 🎛 Configuration (.babelrc, package.json, cli command)

Completely stock Parcel.

## 🤔 Expected Behavior

Parcel should leave the file alone, keeping the `json` extension, _maybe_ minifying the JSON data itself but nothing more.

## 😯 Current Behavior

Parcel converts the JSON data into a Javascript object and module export and renames the file to `.js`.

## 💁 Possible Solution

Please stop converting JSON data.

## 🔦 Context

Trying to get Chrome to read the [`manifest.json`](https://developers.google.com/web/fundamentals/web-app-manifest/) from the `<link rel="manifest" />` tag in an HTML entry point.

## 💻 Code Sample

manifest.json
```json
{
  "foo": "bar"
}
```

```html
...
<head>
    <link rel="manifest" href="manifest.json" />
</head>
...
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7 |
| Node             | 8.9.3 |
| npm/Yarn         | 5.5.1 |
| Operating System | Alpine Linux (docker) |

### LINKED ISSUE #5743: incorrect bundle type inferred from target
# 🐛 bug report

Target in package.json specifying output file causing incorrect bundle type to be inferred.

## 🎛 Configuration

.babelrc
```js
{
    "plugins": [
        [
            "@babel/plugin-transform-typescript",
            {
                "allowNamespaces": true
            }
        ]
    ]
}
```

package.json
```json
{
    # ...
    "scripts": {
        # ...
        "build-dev-watch": "concurrently \"tsc --inlineSourceMap -w\" \"parcel watch --target=clientSide index.html\"",
    },
    "clientSide": "build/clientSide/index.html",
    "targets": {
        "clientSide": {
            "context": "browser",
            "outputFormat": "global"
        }
    },
    "devDependencies": {
        # ...
        "concurrently": "^5.3.0",
        "parcel": "^2.0.0-nightly.560",
        "sass": "^1.32.5",
        "typescript": "^4.1.3"
    }
}
```
(The first tsc script is for nodejs server side code. I had trouble using multiple targets for parcel but I think it by design uses the same entry point for each target.)

cli command
```
npm run build-dev-watch
```

## 🤔 Expected Behavior

Compiled bundle type should be HTML probably since the input file was index.html. This error did not occur in parcel@2.0.0-beta.1.

## 😯 Current Behavior

```
Bundling...
× Build failed.
@parcel/namer-default: Target "clientSide" declares an output file path of "buildclientSideindex.html" which does not match the compiled bundle type "webmanifest".
C:\Users\d3\Documents\WebProjects\d3-web-remote\package.json:20:19
   19 |     },
 > 20 |     "clientSide": "build/clientSide/index.html",
 >    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you mean "build\clientSide\index.webmanifest"?
   21 |     "targets": {
   22 |         "clientSide": {
Try changing the file extension of "clientSide" in package.json.
```

## 🔦 Context

Trying to bundle up client side typescript and sass code with a html entry point. The html linked to a webmanifest which should be included in the build but not fundamentally affect the output type.
Then changing the clientSide as it instructs to "build\clientSide\index.webmanifest", results in the opposite error, it says it's an html bundle and I should call the output "build\clientSide\index.html". Changing it back brings the first error again.

## 💻 Code Sample

index.html
```html
# ...
<head>
    # ...
    <script src="src/clientSide/index.ts"></script>
    <link rel="stylesheet" href="res/style.scss">
    <link rel="manifest" href="manifest.webmanifest">
    <link rel="icon" href="res/icon/favicon-96x96.png" sizes="96x96" type="image/png">
</head>
# ...
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.560
| Node             | v14.8.0
| npm/Yarn         | 6.14.7
| Operating System | Windows 10 v10.0.14393 Build 14393

### PR DESCRIPTION
**Pull request by devongovett**
* Adds a `webmanifest:` named pipeline which accepts both `.json` and `.webmanifest` files. The HTML transformer prepends `webmanifest:` to the href of `<link rel="manifest">`. This is a hack to avoid the JSON file being transformed into JavaScript until we have a better solution for that. Fixes #1764.
* The namer was trying to use the target distEntry for all bundles with `needsStableName`, not just those in an entry bundle group. Fixes #5743.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.82s | +51.00ms |
| Cached | 522.00ms | +16.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.15s | -282.00ms |
| Cached | 425.00ms | -6.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/303720132074537537)**

File: packages/namers/default/src/DefaultNamer.js [hunk 1]
```diff
@@ -37,7 +38,7 @@ export default (new Namer({
 
     if (
       bundle.id === mainBundle.id &&
-      bundle.needsStableName &&
+      isEntry &&
```
Comment (mischnic) [inline packages/namers/default/src/DefaultNamer.js:41]: Shouldn't we keep `bundle.needsStableName &&`?

Comment (devongovett) [reply packages/namers/default/src/DefaultNamer.js:41]: Good question. I assumed that the target's configured distEntry should always win?

File: packages/transformers/html/src/dependencies.js [hunk 2]
```diff
@@ -142,10 +142,20 @@ export default function collectDependencies(
       (attrs.rel === 'canonical' || attrs.rel === 'manifest') &&
       attrs.href
     ) {
-      attrs.href = asset.addURLDependency(attrs.href, {
+      let href = attrs.href;
+      if (attrs.rel === 'manifest') {
+        // A hack to allow manifest.json rather than manifest.webmanifest.
+        // If a custom pipeline is used, it is responsible for running @parcel/transformer-webmanifest.
+        if (!href.includes(':')) {
+          href = 'webmanifest:' + href;
```
Comment (mischnic) [inline packages/transformers/html/src/dependencies.js:150]: This could be problematic when someone redefines this pipeline in their local parcelrc and doesn't include the webmanifest transformer, but oh well

**Review by mischnic — APPROVED** [review]

File: packages/namers/default/src/DefaultNamer.js (hunk 1 above)
Comment (mischnic) [reply packages/namers/default/src/DefaultNamer.js:41]: This is correct if we say that `needsStableName == true` implies that there is no hash in the bundle name, and not necessarily the other way around.
