### PR TITLE
Insert prelude for referenced sibling dependencies in HTML

### LINKED ISSUE #5814: parcelRequire is not a function (Nightly 577)
# 🐛 bug report

After a successful build of our monorepo, opening the web app shows the following error (With minification disabled):

```
Uncaught TypeError: parcelRequire is not a function
```

Looking at the JS source, this happens because parcelRequire is called before it is defined:
```
  var $parcel$global = typeof globalThis !== 'undefined' ? globalThis : typeof self !== 'undefined' ? self : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : {};
  var parcelRequire = $parcel$global.parcelRequired28b;
  var $f2593f70eaebde174314e6f9aabfc2a0$init = parcelRequire("7niVC");
   ...
  var $bf482cc9ddc9dcdfc826e2d46e1a9602$init = parcelRequire("5OWw9");
  var parcelRequireName = "parcelRequired28b";
  var $parcel$modules = {};
  var $parcel$bundles = {};
  if (parcelRequire == null)
```

Since the last `if` generates the parcelRequire function, calling at ahead of that statement fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

Babel:
```
module.exports = function (api) {
  api.cache(true);

  return {
    presets: [
      [
        '@babel/preset-env',
        {
          bugfixes: true,
          corejs: 2,
          useBuiltIns: 'entry'
        }
      ],
      '@babel/preset-react',
      '@babel/preset-typescript'
    ],
    plugins: [
      '@babel/plugin-proposal-class-properties',
      ["@babel/plugin-proposal-decorators", {decoratorsBeforeExport: true}]
    ]
  }
};
```

Our entry is index.html which has a few JS resources:
```
    <script src="./polyfills.js"></script>
    <script src="./react.js"></script>
    <!-- Placeholder for insertion of shell js bundle -->
    <script src="./main.js"></script>
    <script defer src="./browser-support.js"></script>
    <script defer src="./error-page.js"></script>
```

polyfills includes core-js polyfills as well as some initilization code and runs fine.
react includes React/ReactDOM and runs fine.
main.js is where our App component lives, and is where the problem above happens.
 
## 🤔 Expected Behavior

Bundled app should load correctly.

## 😯 Current Behavior

Bundled app does not load correctly.

Note that when running a dev server, it does run fine - The problem is only with the build.

## 💻 Code Sample

I can provide access to @devongovett (Same company). Can also try to do a minimal reproduction if required.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 nightly 577 |
| Node             | 14/15 (latest) |
| npm/Yarn         | latest | 
| Operating System | CentOS / Mac OS |

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #5814

When determining whether an asset is referenced, we need to check direct siblings (bundle_group -> bundle edges) in addition to referenced bundles (bundle -> bundle). `getReferencingBundles` only returns the latter. `getBundlesInBundleGroup` includes both.

In this situation, both assets are direct dependencies of the HTML file, so there is no references edge between the bundle for b.js and a.js. This meant that `isAssetReferencedByDependent` returned false and we did not include the prelude.

image

I also attempted to use `createBundleReference` to add a bundle reference in deduplicate, but this broke a number of tests - possibly due to the bundle -> bundle edges needing to be removed later when we move assets around. Considering all sibling bundles in this case seems to work, but I'm not totally sure if there are other cases where we would need reference edges.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.41s | -97.00ms |
| Cached | 468.00ms | +16.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 114.00ms | -14.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 536.00ms | -34.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 52.00ms | -3.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 76.00ms | +5.00ms ⚠️ |
| dist/legacy/index.76ce4b0c.js | 1.12kb | +0.00b | 77.00ms | +5.00ms ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 78.00ms | +6.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 76.00ms | +4.00ms ⚠️ |
| dist/legacy/index.44edca46.css | 77.00b | +0.00b | 77.00ms | +5.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 19.93s | -75.00ms |
| Cached | 944.00ms | -45.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/PermalinkedComment.0a19c7e4.js | 4.24kb | +0.00b | 927.00ms | -233.00ms 🚀 |
| dist/UserProfile.b2960402.js | 1.78kb | +0.00b | 927.00ms | -233.00ms 🚀 |
| dist/NotFound.f3269ae7.js | 542.00b | +0.00b | 319.00ms | +58.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/PermalinkedComment.0a19c7e4.js | 4.24kb | +0.00b | 111.00ms | -8.00ms 🚀 |
| dist/UserProfile.b2960402.js | 1.78kb | +0.00b | 111.00ms | -7.00ms 🚀 |
| dist/NotFound.f3269ae7.js | 542.00b | +0.00b | 89.00ms | +9.00ms ⚠️ |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 65.00ms | -16.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.14m | -4.15s |
| Cached | 3.12s | +28.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.18b636bb.js | 2.46mb | +0.00b | 1.03m | -15.10s 🚀 |
| dist/popup.119ff481.js | 171.12kb | +0.00b | 17.68s | +3.65s ⚠️ |
| dist/EmojiPickerComponent.e20a59f3.js | 139.77kb | +0.00b | 9.04s | -4.07s 🚀 |
| dist/Toolbar.5631a237.js | 100.20kb | +0.00b | 15.58s | -1.27s 🚀 |
| dist/media-viewer.ebcb5e1e.js | 73.43kb | +0.00b | 10.84s | -2.31s 🚀 |
| dist/card.df70c9b7.js | 54.67kb | +0.00b | 10.72s | +3.04s ⚠️ |
| dist/card.1d931b4c.js | 52.43kb | +0.00b | 13.58s | -1.14s 🚀 |
| dist/Modal.558fb5db.js | 39.59kb | +0.00b | 5.13s | +454.00ms ⚠️ |
| dist/component.ad27194c.js | 31.05kb | +0.00b | 2.53s | +441.00ms ⚠️ |
| dist/esm.e3419f0a.js | 27.83kb | +0.00b | 8.46s | -4.45s 🚀 |
| dist/component.f25dcadb.js | 22.80kb | +0.00b | 5.12s | +1.24s ⚠️ |
| dist/DatePicker.faca45d0.js | 21.38kb | +0.00b | 9.04s | -3.79s 🚀 |
| dist/smartMediaEditor.21f91ed8.js | 16.96kb | +0.00b | 17.36s | +2.89s ⚠️ |
| dist/js.8167e2d5.js | 16.55kb | +0.00b | 5.12s | +1.24s ⚠️ |
| dist/dropzone.3ae9a030.js | 16.15kb | +0.00b | 11.28s | -1.81s 🚀 |
| dist/ui.15dd7acd.js | 14.30kb | +0.00b | 10.64s | +2.97s ⚠️ |
| dist/workerHasher.bc6346e1.js | 11.90kb | +0.00b | 8.43s | +2.58s ⚠️ |
| dist/component.677fad45.js | 6.23kb | +0.00b | 4.60s | +723.00ms ⚠️ |
| dist/card.3a4028bd.js | 5.74kb | +0.00b | 10.83s | +3.15s ⚠️ |
| dist/media-viewer.f15e56f4.js | 4.01kb | +0.00b | 11.39s | +3.15s ⚠️ |
| dist/EmojiPickerComponent.4991ddd4.js | 3.68kb | +0.00b | 10.45s | +4.62s ⚠️ |
| dist/png-chunks-extract.608f438d.js | 3.56kb | +0.00b | 5.12s | +1.24s ⚠️ |
| dist/dropzone.d1e8004d.js | 3.46kb | +0.00b | 11.28s | -1.79s 🚀 |
| dist/Modal.08282ab6.js | 3.23kb | +0.00b | 3.82s | -542.00ms 🚀 |
| dist/clipboard.6a6e5fbd.js | 3.00kb | +0.00b | 11.29s | -2.58s 🚀 |
| dist/16.b6ca7fd0.js | 2.50kb | +0.00b | 2.53s | +441.00ms ⚠️ |
| dist/ResourcedEmojiComponent.5046c0ff.js | 2.19kb | +0.00b | 10.52s | +4.68s ⚠️ |
| dist/card.2888338b.js | 2.15kb | +0.00b | 11.61s | +3.36s ⚠️ |
| dist/date.a69000aa.js | 1.97kb | +0.00b | 5.99s | +1.47s ⚠️ |
| dist/images.ece03ae5.js | 1.91kb | +0.00b | 5.47s | +958.00ms ⚠️ |
| dist/feedback.facaac2e.js | 1.87kb | +0.00b | 9.04s | +3.98s ⚠️ |
| dist/16.a9ea9b41.js | 1.86kb | +0.00b | 5.25s | +995.00ms ⚠️ |
| dist/16.89d45d15.js | 1.80kb | +0.00b | 4.77s | +706.00ms ⚠️ |
| dist/workerHasher.31326e89.js | 1.77kb | +0.00b | 8.37s | +2.53s ⚠️ |
| dist/workerHasher.d607e0b8.js | 1.77kb | +0.00b | 13.57s | -1.14s 🚀 |
| dist/list-number.d4568b49.js | 1.69kb | +0.00b | 5.47s | +799.00ms ⚠️ |
| dist/status.6595d133.js | 1.69kb | +0.00b | 5.74s | +785.00ms ⚠️ |
| dist/code.efde0f48.js | 1.61kb | +0.00b | 5.99s | +1.00s ⚠️ |
| dist/link.5be155be.js | 1.54kb | +0.00b | 5.47s | +799.00ms ⚠️ |
| dist/heading6.5a6082c8.js | 1.53kb | +0.00b | 9.04s | +3.98s ⚠️ |
| dist/heading3.1c92891c.js | 1.52kb | +0.00b | 5.84s | +889.00ms ⚠️ |
| dist/16.07ccad90.js | 1.51kb | +0.00b | 5.37s | +1.12s ⚠️ |
| dist/16.00f25203.js | 1.47kb | +0.00b | 4.60s | +540.00ms ⚠️ |
| dist/16.02056ae6.js | 1.47kb | +0.00b | 5.27s | +1.21s ⚠️ |
| dist/emoji.b5624cf5.js | 1.46kb | +0.00b | 5.47s | +958.00ms ⚠️ |
| dist/16.b7da7bde.js | 1.45kb | +0.00b | 2.53s | +441.00ms ⚠️ |
| dist/16.00100306.js | 1.44kb | +0.00b | 5.37s | +962.00ms ⚠️ |
| dist/16.bdd61d2d.js | 1.41kb | +0.00b | 5.37s | +962.00ms ⚠️ |
| dist/heading5.88bc6249.js | 1.41kb | +0.00b | 5.84s | +787.00ms ⚠️ |
| dist/expand.4a483eb0.js | 1.39kb | +0.00b | 9.04s | +3.98s ⚠️ |
| dist/16.fa5f411c.js | 1.36kb | +0.00b | 5.25s | +839.00ms ⚠️ |
| dist/16.2a21d3f4.js | 1.34kb | +0.00b | 2.53s | +441.00ms ⚠️ |
| dist/heading2.22de70fe.js | 1.34kb | +0.00b | 5.84s | +889.00ms ⚠️ |
| dist/16.d10db5a3.js | 1.32kb | +0.00b | 5.25s | +839.00ms ⚠️ |
| dist/16.c9db7e6b.js | 1.32kb | +0.00b | 5.37s | +391.00ms ⚠️ |
| dist/mention.c44b48ed.js | 1.30kb | +0.00b | 5.61s | +938.00ms ⚠️ |
| dist/heading4.a2524c70.js | 1.29kb | +0.00b | 5.84s | +787.00ms ⚠️ |
| dist/Modal.44e980e0.js | 1.29kb | +0.00b | 5.12s | +1.24s ⚠️ |
| dist/layout.81f2196c.js | 1.28kb | +0.00b | 5.47s | +799.00ms ⚠️ |
| dist/16.9e97e787.js | 1.28kb | +0.00b | 2.53s | +441.00ms ⚠️ |
| dist/16.acff901d.js | 1.27kb | +0.00b | 5.25s | +995.00ms ⚠️ |
| dist/component.233c7a65.js | 1.26kb | +0.00b | 3.82s | -543.00ms 🚀 |
| dist/16.015dfb9d.js | 1.26kb | +0.00b | 5.27s | +1.21s ⚠️ |
| dist/16.828b958e.js | 1.26kb | +0.00b | 5.27s | +1.02s ⚠️ |
| dist/16.b9b1643b.js | 1.26kb | +0.00b | 5.25s | +995.00ms ⚠️ |
| dist/16.ec84a250.js | 1.26kb | +0.00b | 4.60s | +540.00ms ⚠️ |
| dist/divider.ed7ccd2e.js | 1.26kb | +0.00b | 6.08s | +1.57s ⚠️ |
| dist/quote.b6d8bffb.js | 1.25kb | +0.00b | 5.74s | +897.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.ff0177b3.js | 1.25kb | +0.00b | 10.83s | +3.15s ⚠️ |
| dist/action.01ec8983.js | 1.24kb | +0.00b | 5.37s | +391.00ms ⚠️ |
| dist/16.458399e0.js | 1.23kb | +0.00b | 3.82s | -543.00ms 🚀 |
| dist/decision.c48f9f1e.js | 1.22kb | +0.00b | 5.99s | +1.47s ⚠️ |
| dist/panel-warning.b5f3360d.js | 1.22kb | +0.00b | 5.74s | +897.00ms ⚠️ |
| dist/list.2dfe3f18.js | 1.19kb | +0.00b | 5.61s | +938.00ms ⚠️ |
| dist/heading1.cc82b077.js | 1.19kb | +0.00b | 5.84s | +888.00ms ⚠️ |
| dist/16.90358f40.js | 1.18kb | +0.00b | 5.37s | +962.00ms ⚠️ |
| dist/panel-error.7454ebc0.js | 1.12kb | +0.00b | 5.61s | -387.00ms 🚀 |
| dist/panel.fc70749c.js | 1.11kb | +0.00b | 5.74s | +897.00ms ⚠️ |
| dist/table.77df779b.js | 1.10kb | +0.00b | 5.74s | +785.00ms ⚠️ |
| dist/panel-success.d5752da0.js | 1.06kb | +0.00b | 5.61s | +768.00ms ⚠️ |
| dist/panel-note.6a71a1f2.js | 1.05kb | +0.00b | 5.61s | +769.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.49b32f4d.js | 1023.00b | +0.00b | 11.28s | -1.79s 🚀 |
| dist/media-card-analytics-error-boundary.9a500f44.js | 1019.00b | +0.00b | 10.83s | +3.15s ⚠️ |
| dist/media-card-analytics-error-boundary.b884d580.js | 1019.00b | +0.00b | 13.56s | -1.15s 🚀 |
| dist/media-viewer-analytics-error-boundary.83da5db2.js | 1015.00b | +0.00b | 11.44s | +3.20s ⚠️ |
| dist/simpleHasher.79137cb4.js | 767.00b | +0.00b | 8.45s | +2.61s ⚠️ |
| dist/simpleHasher.2c5206fd.js | 767.00b | +0.00b | 17.30s | +2.84s ⚠️ |
| dist/index.html | 119.00b | +0.00b | 3.90s | +1.92s ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.3ca4da9b.js | 2.46mb | +0.00b | 564.00ms | -52.00ms 🚀 |
| dist/pdfRenderer.f5a3f4a7.js | 1.11mb | +0.00b | 609.00ms | -75.00ms 🚀 |
| dist/editorView.ea13a2b7.js | 588.08kb | +0.00b | 636.00ms | -54.00ms 🚀 |
| dist/popup.7a55d267.js | 171.12kb | +0.00b | 646.00ms | -38.00ms 🚀 |
| dist/EmojiPickerComponent.e20a59f3.js | 139.77kb | +0.00b | 609.00ms | -67.00ms 🚀 |
| dist/Toolbar.5631a237.js | 100.20kb | +0.00b | 636.00ms | -54.00ms 🚀 |
| dist/media-viewer.ebcb5e1e.js | 73.43kb | +0.00b | 609.00ms | -67.00ms 🚀 |
| dist/card.df70c9b7.js | 54.67kb | +0.00b | 589.00ms | -87.00ms 🚀 |
| dist/card.1d931b4c.js | 52.43kb | +0.00b | 627.00ms | -67.00ms 🚀 |
| dist/Modal.558fb5db.js | 39.59kb | +0.00b | 565.00ms | -51.00ms 🚀 |
| dist/component.ad27194c.js | 31.05kb | +0.00b | 565.00ms | -45.00ms 🚀 |
| dist/esm.e3419f0a.js | 27.83kb | +0.00b | 609.00ms | -67.00ms 🚀 |
| dist/component.f25dcadb.js | 22.80kb | +0.00b | 512.00ms | -108.00ms 🚀 |
| dist/DatePicker.faca45d0.js | 21.38kb | +0.00b | 570.00ms | -106.00ms 🚀 |
| dist/smartMediaEditor.21f91ed8.js | 16.96kb | +0.00b | 636.00ms | -58.00ms 🚀 |
| dist/js.8167e2d5.js | 16.55kb | +0.00b | 511.00ms | -109.00ms 🚀 |
| dist/dropzone.f6594f14.js | 16.15kb | +0.00b | 626.00ms | -58.00ms 🚀 |
| dist/ui.15dd7acd.js | 14.30kb | +0.00b | 589.00ms | -74.00ms 🚀 |
| dist/workerHasher.bc6346e1.js | 11.90kb | +0.00b | 609.00ms | -53.00ms 🚀 |
| dist/component.677fad45.js | 6.23kb | +0.00b | 515.00ms | -108.00ms 🚀 |
| dist/card.3a4028bd.js | 5.74kb | +0.00b | 608.00ms | -68.00ms 🚀 |
| dist/media-viewer.f15e56f4.js | 4.01kb | +0.00b | 609.00ms | -75.00ms 🚀 |
| dist/EmojiPickerComponent.4991ddd4.js | 3.68kb | +0.00b | 589.00ms | -73.00ms 🚀 |
| dist/png-chunks-extract.608f438d.js | 3.56kb | +0.00b | 512.00ms | -108.00ms 🚀 |
| dist/dropzone.d1e8004d.js | 3.46kb | +0.00b | 646.00ms | -37.00ms 🚀 |
| dist/index.ece3a13e.css | 3.46kb | +0.00b | 646.00ms | -48.00ms 🚀 |
| dist/Modal.08282ab6.js | 3.23kb | +0.00b | 495.00ms | -121.00ms 🚀 |
| dist/clipboard.6a6e5fbd.js | 3.00kb | +0.00b | 627.00ms | -57.00ms 🚀 |
| dist/16.b6ca7fd0.js | 2.50kb | +0.00b | 495.00ms | -115.00ms 🚀 |
| dist/ResourcedEmojiComponent.5046c0ff.js | 2.19kb | +0.00b | 589.00ms | -74.00ms 🚀 |
| dist/card.2888338b.js | 2.15kb | +0.00b | 646.00ms | -38.00ms 🚀 |
| dist/date.a69000aa.js | 1.97kb | +0.00b | 552.00ms | -91.00ms 🚀 |
| dist/images.ece03ae5.js | 1.91kb | +0.00b | 553.00ms | -91.00ms 🚀 |
| dist/feedback.facaac2e.js | 1.87kb | +0.00b | 575.00ms | -80.00ms 🚀 |
| dist/16.a9ea9b41.js | 1.86kb | +0.00b | 538.00ms | -88.00ms 🚀 |
| dist/browser.8883c452.js | 1.85kb | +0.00b | 627.00ms | -57.00ms 🚀 |
| dist/16.89d45d15.js | 1.80kb | +0.00b | 515.00ms | -105.00ms 🚀 |
| dist/workerHasher.31326e89.js | 1.77kb | +0.00b | 610.00ms | -66.00ms 🚀 |
| dist/workerHasher.d607e0b8.js | 1.77kb | +0.00b | 636.00ms | -58.00ms 🚀 |
| dist/list-number.d4568b49.js | 1.69kb | +0.00b | 560.00ms | -82.00ms 🚀 |
| dist/status.6595d133.js | 1.69kb | +0.00b | 568.00ms | -84.00ms 🚀 |
| dist/code.efde0f48.js | 1.61kb | +0.00b | 546.00ms | -81.00ms 🚀 |
| dist/link.5be155be.js | 1.54kb | +0.00b | 560.00ms | -82.00ms 🚀 |
| dist/heading6.5a6082c8.js | 1.53kb | +0.00b | 575.00ms | -80.00ms 🚀 |
| dist/heading3.1c92891c.js | 1.52kb | +0.00b | 570.00ms | -85.00ms 🚀 |
| dist/16.07ccad90.js | 1.51kb | +0.00b | 530.00ms | -93.00ms 🚀 |
| dist/16.00f25203.js | 1.47kb | +0.00b | 515.00ms | -105.00ms 🚀 |
| dist/16.02056ae6.js | 1.47kb | +0.00b | 530.00ms | -91.00ms 🚀 |
| dist/emoji.b5624cf5.js | 1.46kb | +0.00b | 554.00ms | -90.00ms 🚀 |
| dist/16.b7da7bde.js | 1.45kb | +0.00b | 495.00ms | -115.00ms 🚀 |
| dist/16.00100306.js | 1.44kb | +0.00b | 546.00ms | -81.00ms 🚀 |
| dist/16.bdd61d2d.js | 1.41kb | +0.00b | 544.00ms | -83.00ms 🚀 |
| dist/heading5.88bc6249.js | 1.41kb | +0.00b | 575.00ms | -80.00ms 🚀 |
| dist/expand.4a483eb0.js | 1.39kb | +0.00b | 575.00ms | -101.00ms 🚀 |
| dist/16.fa5f411c.js | 1.36kb | +0.00b | 538.00ms | -88.00ms 🚀 |
| dist/16.2a21d3f4.js | 1.34kb | +0.00b | 495.00ms | -115.00ms 🚀 |
| dist/heading2.22de70fe.js | 1.34kb | +0.00b | 570.00ms | -82.00ms 🚀 |
| dist/16.d10db5a3.js | 1.32kb | +0.00b | 538.00ms | -88.00ms 🚀 |
| dist/16.c9db7e6b.js | 1.32kb | +0.00b | 546.00ms | -81.00ms 🚀 |
| dist/mention.c44b48ed.js | 1.30kb | +0.00b | 560.00ms | -82.00ms 🚀 |
| dist/heading4.a2524c70.js | 1.29kb | +0.00b | 574.00ms | -81.00ms 🚀 |
| dist/Modal.44e980e0.js | 1.29kb | +0.00b | 511.00ms | -109.00ms 🚀 |
| dist/layout.81f2196c.js | 1.28kb | +0.00b | 554.00ms | -88.00ms 🚀 |
| dist/16.9e97e787.js | 1.28kb | +0.00b | 495.00ms | -115.00ms 🚀 |
| dist/16.acff901d.js | 1.27kb | +0.00b | 536.00ms | -91.00ms 🚀 |
| dist/component.233c7a65.js | 1.26kb | +0.00b | 565.00ms | -51.00ms 🚀 |
| dist/16.015dfb9d.js | 1.26kb | +0.00b | 518.00ms | -103.00ms 🚀 |
| dist/16.828b958e.js | 1.26kb | +0.00b | 530.00ms | -93.00ms 🚀 |
| dist/16.b9b1643b.js | 1.26kb | +0.00b | 530.00ms | -93.00ms 🚀 |
| dist/16.ec84a250.js | 1.26kb | +0.00b | 515.00ms | -105.00ms 🚀 |
| dist/divider.ed7ccd2e.js | 1.26kb | +0.00b | 554.00ms | -90.00ms 🚀 |
| dist/quote.b6d8bffb.js | 1.25kb | +0.00b | 568.00ms | -82.00ms 🚀 |
| dist/media-card-analytics-error-boundary.ff0177b3.js | 1.25kb | +0.00b | 608.00ms | -68.00ms 🚀 |
| dist/action.01ec8983.js | 1.24kb | +0.00b | 546.00ms | -81.00ms 🚀 |
| dist/16.458399e0.js | 1.23kb | +0.00b | 565.00ms | -51.00ms 🚀 |
| dist/decision.c48f9f1e.js | 1.22kb | +0.00b | 554.00ms | -89.00ms 🚀 |
| dist/panel-warning.b5f3360d.js | 1.22kb | +0.00b | 567.00ms | -83.00ms 🚀 |
| dist/list.2dfe3f18.js | 1.19kb | +0.00b | 560.00ms | -82.00ms 🚀 |
| dist/heading1.cc82b077.js | 1.19kb | +0.00b | 570.00ms | -82.00ms 🚀 |
| dist/16.90358f40.js | 1.18kb | +0.00b | 539.00ms | -87.00ms 🚀 |
| dist/panel-error.7454ebc0.js | 1.12kb | +0.00b | 560.00ms | -90.00ms 🚀 |
| dist/panel.fc70749c.js | 1.11kb | +0.00b | 567.00ms | -83.00ms 🚀 |
| dist/table.77df779b.js | 1.10kb | +0.00b | 570.00ms | -80.00ms 🚀 |
| dist/panel-success.d5752da0.js | 1.06kb | +0.00b | 567.00ms | -83.00ms 🚀 |
| dist/panel-note.6a71a1f2.js | 1.05kb | +0.00b | 567.00ms | -83.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.49b32f4d.js | 1023.00b | +0.00b | 646.00ms | -37.00ms 🚀 |
| dist/media-card-analytics-error-boundary.9a500f44.js | 1019.00b | +0.00b | 589.00ms | -87.00ms 🚀 |
| dist/media-card-analytics-error-boundary.b884d580.js | 1019.00b | +0.00b | 627.00ms | -67.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.83da5db2.js | 1015.00b | +0.00b | 646.00ms | -38.00ms 🚀 |
| dist/simpleHasher.79137cb4.js | 767.00b | +0.00b | 610.00ms | -52.00ms 🚀 |
| dist/simpleHasher.2c5206fd.js | 767.00b | +0.00b | 636.00ms | -58.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 492.00ms | -42.00ms 🚀 |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 14.55s | -26.00ms |
| Cached | 553.00ms | +28.00ms ⚠️ |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/290535446675456521)**

File: packages/core/core/src/BundleGraph.js [hunk 1]
```diff
@@ -658,7 +658,10 @@ export default class BundleGraph {
     let visitedBundles: Set<Bundle> = new Set();
     // Check if any of this bundle's descendants, referencers, bundles referenced
     // by referencers, or descedants of its referencers reference the asset.
-    return [bundle, ...this.getReferencingBundles(bundle)].some(referencer => {
+    let siblingBundles = this.getBundleGroupsContainingBundle(
```
Comment (wbinnssmith) [inline packages/core/core/src/BundleGraph.js:661]: nit: this may contain duplicate values

**Review by wbinnssmith — APPROVED** [review]
