### PR TITLE
Invalidate cache for entry and target changes

### LINKED ISSUE #3862: Changing publicUrl requires clearing the cache
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"scripts": {
		"start": "parcel index.html",
		"build": "parcel build index.html"
	},
	"devDependencies": {
		"@babel/core": "^7.7.4"
	},
	"default": "dist/index.html",
	"targets": {
		"default": {
			"publicUrl": "SOME_URL"
		}
	}
}
```

`parcel build index.html`

## 🤔 Expected Behavior

Updating the `publishUrl` value should also change the html file.

## 😯 Current Behavior

Occurrences of the public url in the index.html aren't updated, e.g.
`<script src="SOME_URL/test.98afe41f.js"></script>`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |v2
| Node             |
| npm/Yarn         |
| Operating System |

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #3862. Fixes #5212. Fixes T-368. Fixes T-363. Fixes T-714.

This adds tests and implements fixes for cache invalidation of entry and target requests.

* Ensures entry requests are invalided when a file they resolve is deleted. In the case of globs, this is ok (previously it errored), but in other cases, we can throw a nicer error this way.
* Ensures target requests are invalidated when a package.json is created or deleted.
* Ensures target requests are invalidated whenever a `browserslist` or `.browserslistrc` file is created/updated/deleted. Also ensures that changes to `BROWSERSLIST_ENV` and `NODE_ENV` environment variables invalidate the cache.
* Invalidates the packager cache when the publicUrl and sourcemap target options change by including them in the cache key. Ideally these would only be included if they are used but there's not a great way of doing that at the moment...

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.81s | -83.00ms |
| Cached | 3.42s | +114.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 197.00ms | -91.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 362.00ms | +114.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 362.00ms | +169.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 220.00ms | -145.00ms 🚀 |
| dist/legacy/index.45cccf70.js | 1.10kb | +0.00b | 453.00ms | +180.00ms ⚠️ |
| dist/modern/index.1964d1f6.js | 1.10kb | +0.00b | 305.00ms | -148.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 454.00ms | +181.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 305.00ms | -149.00ms 🚀 |
| dist/legacy/index.b3acc8eb.css | 77.00b | +0.00b | 454.00ms | +181.00ms ⚠️ |
| dist/modern/index.7bc22a8b.css | 77.00b | +0.00b | 305.00ms | -148.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 25.82s | -548.00ms |
| Cached | 3.33s | -33.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/NotFound.f8a0616d.js | 387.00b | +0.00b | 1.07s | +283.00ms ⚠️ |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 140.00ms | -74.00ms 🚀 |

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.23m | +4.86s |
| Cached | 7.65s | -211.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.8016b423.js | 2.72mb | -3.00b 🚀 | 1.75m | +3.60s |
| dist/EmojiTypeAheadComponent.1990d771.js | 8.67kb | +0.00b | 1.08m | +8.29s ⚠️ |
| dist/index.ac562c80.css | 3.46kb | +0.00b | 1.18m | +11.39s ⚠️ |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 1.76s | -212.00ms 🚀 |
| dist/EmojiUploadComponent.d54a1fc6.js | 2.18kb | +0.00b | 1.08m | +8.29s ⚠️ |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 9.00s | +2.94s ⚠️ |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 5.88s | -2.27s 🚀 |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 5.88s | -2.09s 🚀 |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 1.76s | -212.00ms 🚀 |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 7.44s | +801.00ms ⚠️ |
| dist/heading3.2113b7a1.js | 1.29kb | +0.00b | 7.02s | +389.00ms ⚠️ |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 9.00s | +2.94s ⚠️ |
| dist/16.436f097f.js | 1.21kb | +0.00b | 1.76s | -212.00ms 🚀 |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 9.03s | +2.97s ⚠️ |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 7.03s | +394.00ms ⚠️ |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 1.76s | -213.00ms 🚀 |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 5.88s | -2.09s 🚀 |
| dist/heading2.a2a1be3f.js | 1.11kb | +0.00b | 7.02s | +389.00ms ⚠️ |
| dist/16.3920766f.js | 1.10kb | +0.00b | 1.76s | -213.00ms 🚀 |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 7.02s | +389.00ms ⚠️ |
| dist/heading1.7d899ba5.js | 976.00b | +0.00b | 6.90s | +350.00ms ⚠️ |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 1.08m | +8.29s ⚠️ |
| dist/index.html | 119.00b | +0.00b | 8.08s | +1.04s ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.8016b423.js | 2.72mb | +0.00b | 261.00ms | -35.00ms 🚀 |
| dist/pdfRenderer.15a6a023.js | 1.11mb | +0.00b | 577.00ms | -35.00ms 🚀 |
| dist/EmojiPickerComponent.ae601247.js | 75.29kb | +0.00b | 497.00ms | -46.00ms 🚀 |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 285.00ms | -43.00ms 🚀 |
| dist/component.d7c29980.js | 30.70kb | +0.00b | 261.00ms | -35.00ms 🚀 |
| dist/component.54080a26.js | 22.50kb | +0.00b | 307.00ms | -44.00ms 🚀 |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 497.00ms | -46.00ms 🚀 |
| dist/EmojiPickerComponent.7dc0ebd0.js | 18.23kb | +0.00b | 497.00ms | -46.00ms 🚀 |
| dist/js.5733a017.js | 16.40kb | +0.00b | 285.00ms | -43.00ms 🚀 |
| dist/workerHasher.1e706e77.js | 11.75kb | +0.00b | 537.00ms | -35.00ms 🚀 |
| dist/EmojiTypeAheadComponent.1990d771.js | 8.67kb | +0.00b | 537.00ms | -34.00ms 🚀 |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 307.00ms | -45.00ms 🚀 |
| dist/media-viewer.59c17dad.js | 3.92kb | +0.00b | 577.00ms | -35.00ms 🚀 |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 497.00ms | -46.00ms 🚀 |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 285.00ms | -43.00ms 🚀 |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 285.00ms | -42.00ms 🚀 |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 285.00ms | -34.00ms 🚀 |
| dist/EmojiUploadComponent.d54a1fc6.js | 2.18kb | +0.00b | 537.00ms | -34.00ms 🚀 |
| dist/card.eea6ad8c.js | 2.03kb | +0.00b | 577.00ms | -36.00ms 🚀 |
| dist/ResourcedEmojiComponent.abe8596c.js | 2.00kb | +0.00b | 261.00ms | -35.00ms 🚀 |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 308.00ms | -44.00ms 🚀 |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 465.00ms | -38.00ms 🚀 |
| dist/workerHasher.6d5b22d7.js | 1.54kb | +0.00b | 537.00ms | -34.00ms 🚀 |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 334.00ms | -23.00ms 🚀 |
| dist/16.19c93285.js | 1.33kb | +0.00b | 308.00ms | -44.00ms 🚀 |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 333.00ms | -24.00ms 🚀 |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 669.00ms | +88.00ms ⚠️ |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 465.00ms | -38.00ms 🚀 |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 369.00ms | -212.00ms 🚀 |
| dist/16.436f097f.js | 1.21kb | +0.00b | 669.00ms | +88.00ms ⚠️ |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 465.00ms | -38.00ms 🚀 |
| dist/expand.450f3aea.js | 1.16kb | +0.00b | 465.00ms | -38.00ms 🚀 |
| dist/media-card-analytics-error-boundary.2323af57.js | 1.15kb | +0.00b | 577.00ms | -36.00ms 🚀 |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 669.00ms | +88.00ms ⚠️ |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 333.00ms | -24.00ms 🚀 |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 333.00ms | -24.00ms 🚀 |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 334.00ms | -23.00ms 🚀 |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 308.00ms | -44.00ms 🚀 |
| dist/16.3920766f.js | 1.10kb | +0.00b | 669.00ms | +89.00ms ⚠️ |
| dist/component.6600f83e.js | 1.07kb | +0.00b | 261.00ms | -35.00ms 🚀 |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 465.00ms | -38.00ms 🚀 |
| dist/panel-error.8d11e8b7.js | 906.00b | +0.00b | 669.00ms | +247.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.0afa7031.js | 755.00b | +0.00b | 577.00ms | -35.00ms 🚀 |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 497.00ms | -46.00ms 🚀 |
| dist/simpleHasher.16c8bf41.js | 528.00b | +0.00b | 537.00ms | -35.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 261.00ms | -35.00ms 🚀 |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/278512104895414796)**

File: packages/transformers/react-refresh-babel/src/ReactRefreshBabelTransformer.js [hunk 1]
```diff
@@ -3,23 +3,26 @@
...
+    let pkg = await config.getPackage();
     return !(pkg && pkg.dependencies && pkg.dependencies['react']);
   }
 }
 
 export default (new Transformer({
-  async transform({asset, options}) {
-    if (!(await shouldExclude(asset, options))) {
+  async loadConfig({config, options}) {
+    config.setResult(await shouldExclude(config, options));
```
Comment (mischnic) [inline packages/transformers/react-refresh-babel/src/ReactRefreshBabelTransformer.js:22]: Why is this needed?

Comment (devongovett) [reply packages/transformers/react-refresh-babel/src/ReactRefreshBabelTransformer.js:22]: Moving it into loadConfig to avoid asset.getPackage() which causes any package.json change to invalidate the asset due to the hash of the included file. This way, only the changes in the package.json we actually care about invalidate the asset.

**Review by wbinnssmith — APPROVED** [review]

**Review by padmaia — APPROVED** [review]

**Review by mischnic — APPROVED** [review]
