### PR TITLE
Give priority to styl files in StylusAsset resolver

### LINKED ISSUE #1110: Failing AppVeyor test [VUE]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

Appveyor (Current master 0140dcea58edd0df5959752e38faf41b96a1d509 )

### 🤔 Expected Behavior

Should pass

### 😯 Current Behavior

`vue should produce a vue bundle using preprocessors` fails
capture

### 🔦 Context

Trying to get CI to pass

### PR DESCRIPTION
**Pull request by brandon93s**
Stylus's base case expects a `.styl` file. If a folder has two or more files with the same name, but different extensions, any `styl` file should take precedence for the sake of resolution. This sorts `styl` to the top of the list so that it is checked first. 
Closes #1110

### CODE REVIEW

File: src/assets/StylusAsset.js [hunk 1]
```diff
@@ -50,13 +50,30 @@ class StylusAsset extends Asset {
...
 async function createEvaluator(asset) {
   const Evaluator = await localRequire(
     'stylus/lib/visitor/evaluator',
     asset.name
   );
   const utils = await localRequire('stylus/lib/utils', asset.name);
-  const resolver = new Resolver(asset.options);
+  const resolver = new Resolver(
+    Object.assign({}, asset.options, {
+      extensions: getResolverExtensions(asset.options)
```
Comment (devongovett) [inline src/assets/StylusAsset.js]: maybe we should just hard-code the extensions supports importing? `['.styl', '.css']` - currently it's not possible to e.g. import a `.less` file from stylus anyway. WDYT?

**Comment by brandon93s** [comment]
@devongovett Thanks for wrapping this up, been traveling without PC!
