### PR TITLE
Fix `web_accessible_resources` and HMR

### LINKED ISSUE #7953: Web Extension Transformer: a broken `web_accessible_resources` field is added
- Follows https://github.com/parcel-bundler/parcel/pull/7050

# 🐛 bug report

When building a web extension, it seems that the hosts specified in the content scripts are copied to the `web_accessible_resources` field, even if unnecessary, breaking the manifest altogether in some cases.

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration. It happens on both build and watch.

## 🤔 Expected Behavior

No `web_accessible_resources` unless required:

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"css": ["manifest.b7514168.css"]
		}
	]
}
```

or at least use a supported origin glob:

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"css": ["manifest.b7514168.css"]
		}
	],
	"web_accessible_resources": [
		{
			"matches": ["https://github.com/*"],
			"extension_ids": [],
			"resources": []
		}
	]
}
```
## 😯 Current Behavior

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"css": ["manifest.b7514168.css"]
		}
	],
	"web_accessible_resources": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"extension_ids": [],
			"resources": []
		}
	]
}
```

## 💻 Code Sample

Input manifest:

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": [ "https://github.com/fregante/browser-extension-template/*" ],
			"css": [ "content.css" ]
		}
	]
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.1049
| parcel/config-webextension | 2.4.2-nightly.2674 |
| Node             | v16.4.2
| npm/Yarn         | 7.18.1
| Operating System | macOS 11

### PR DESCRIPTION
**Pull request by 101arrowz**
# ↪️ Pull Request

Actually fixes #7953

This actually, really fixes `web_accessible_resources` generation for web extensions and HMR by using a runtime as a cache invalidator for the packager based on the state of the bundle graph. This is probably bad practice compared to just doing the generation from the runtime, but since JSON assets are automatically transformed to JS it's not possible to actually consume the result of the transformer in the packager without eval.

### CODE REVIEW

**Comment by devongovett** [comment]
Looks like a couple tests are failing.

File: packages/packagers/webextension/src/WebExtensionPackager.js [hunk 1]
```diff
@@ -56,9 +58,16 @@ export default (new Packager({
...
-          extension_ids: [],
+          matches: contentScript.matches.map(match => {
+            if (/^(((http|ws)s?)|ftp|\*):\/\//.test(match)) {
+              let pathIndex = match.indexOf('/', match.indexOf('://') + 3);
+              // Avoids creating additional errors in invalid match URLs
+              if (pathIndex == -1) pathIndex = match.length;
+              return match.slice(0, pathIndex) + '/*';
+            }
+            return match;
+          }),
```
Comment (devongovett) [inline packages/packagers/webextension/src/WebExtensionPackager.js:70]: So if I'm reading this right, `"https://github.com/fregante/browser-extension-template/*"` would be transformed to `"https://github.com/*"`? What's the reason for that? Should we add a test?

We could also consider using a URL parser for this:

```js
  return new URL(match).origin + '/*'
```

File: packages/runtimes/webextension/src/WebExtensionRuntime.js [hunk 2]
```diff
@@ -12,39 +12,50 @@ const AUTORELOAD_BG = fs.readFileSync(
...
+      const descendants = [];
+      bundleGraph.traverseBundles(b => {
+        descendants.push(b.id);
+      }, bundle);
       return {
         filePath: __filename,
-        code: AUTORELOAD_BG,
+        code: JSON.stringify(descendants),
         isEntry: true,
       };
```
Comment (devongovett) [inline packages/runtimes/webextension/src/WebExtensionRuntime.js:31]: Nice hack. This is ok for now. We'll think about a better way to do this in core.

File: packages/packagers/webextension/src/WebExtensionPackager.js (hunk 1 above)
Comment (101arrowz) [reply packages/packagers/webextension/src/WebExtensionPackager.js:70]: In web extensions `web_accessible_resources` will error if the path is not a wildcard. We can't use the `new URL` constructor because there's a bunch of special syntax here like `*://something*.com/*` that doesn't get parsed properly by `new URL` but is covered by this logic.

Now in theory we could literally replace all this with `["<all_urls>"]` and it would work the same, but that makes fingerprinting by bad actors much easier.

**Comment by 101arrowz** [comment]
Not sure why the tests are failing now, it seems to be unrelated to the changes in this PR but clearly it's not. Investigating now...

EDIT: Actually the issue was me not removing the broken `priority: 'parallel'` logic to try to make the packager reload. Using a runtime seems to be the only way to update on bundle graph change rather than bundle change.

**Review by devongovett — APPROVED** [review]

**Comment by fregante** [comment]
<details>Is this truncating `web_accessible_resources[*].resources` in every case? I have `resources: ['*.js']` in it and it's outputting `resources: []`

Same goes for for mv2: `web_accessible_resources: ['*.js']` is becoming `web_accessible_resources: []`</details>

Edit: false alarm, the array was being trimmed because there were no `*.js` files, I needed to use `../*.js`
