### PR TITLE
Fix crash when importing CSS with require

### LINKED ISSUE #3676: Basic .parcelrc crashes Parcel
Using the following `.parcelrc` crashes the latest alpha release `2.0.0-alpha.2.1`.

~~~json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "*.js": ["@parcel/transformer-babel"]
  }
}
~~~

Error thrown:

~~~shell
🚨 The expression evaluated to a falsy value:

  (0, _assert.default)(typeof v === 'string')


  (0, _assert.default)(typeof v === 'string')

    at assertString (/home/romu/tmp/parcel-ssr/node_modules/@parcel/scope-hoisting/lib/link.js:47:23)
    at /home/romu/tmp/parcel-ssr/node_modules/@parcel/scope-hoisting/lib/link.js:89:16
    at enter (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:475:16)
    at enter (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:475:16)
    at enter (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:475:16)
    at walk (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:310:26)
    at walk (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:331:22)
    at Graph.dfs (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:355:12)
    at Graph.traverse (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:257:17)
    at Graph.filteredTraverse (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:265:17)
~~~

Repro: https://github.com/brillout/parcel-ssr

Context: I want to build an SSR tool on top of Parcel.

Env: Linux / parcel@2.0.0-alpha.2.1 / node@12.2.0 / yarn@1.19.1

### LINKED ISSUE #6478: Build fails in Parcel nightly 725
# 🐛 bug report

I just upgraded from **nightly.570** to **nightly.725**. Everything worked fine before, but now when I try to build I get this error:

```
× Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

    at ScopeHoistingPackager.resolveSymbol \node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:698:27)
    at ScopeHoistingPackager.buildReplacements (node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:607:27)
    at ScopeHoistingPackager.buildAsset (\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:416:39)
    at ScopeHoistingPackager.visitAsset (\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:376:17)
    at \node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:209:40
    at \node_modules\@parcel\core\lib\Graph.js:538:16
    at \node_modules\@parcel\core\lib\Graph.js:538:16
    at \node_modules\@parcel\core\lib\Graph.js:538:16
    at walk (k\node_modules\@parcel\core\lib\Graph.js:403:26)
    at walk (\node_modules\@parcel\core\lib\Graph.js:425:22)
\dist\index.HASH_REF_638417ca3afb1157.js
```

I build with `--no-cache` and I also tried removing `.parcel-cache`.
The dev server works fine.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "build": "cmd /c \"set PARCEL_BUNDLE_ANALYZER=1 && parcel build src/index.html --no-cache --no-source-maps\"",
  },
  "dependencies": {
    "@date-io/moment": "^1.3.13",
    "@material-ui/core": "^4.10.2",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/pickers": "^3.2.10",
    "@types/chart.js": "^2.9.21",
    "@types/deep-equal": "^1.0.1",
    "@types/heatmap.js": "^2.0.36",
    "@types/js-cookie": "^2.2.6",
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.5",
    "chart.js": "^2.9.3",
    "deep-equal": "^2.0.4",
    "gulp-if": "^3.0.0",
    "heatmap.js": "^2.0.5",
    "i18next": "^19.4.5",
    "js-cookie": "^2.2.1",
    "material-table": "^1.60.0",
    "material-ui-confirm": "^2.0.5",
    "moment": "^2.26.0",
    "notistack": "^1.0.6",
    "query-string": "^6.13.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.8.13",
    "react-promise-tracker": "^2.1.0",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "redux": "^4.0.5",
    "tslint": "^6.1.3",
    "yargs": "^15.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.0",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.10.1",
    "@babel/plugin-proposal-optional-chaining": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "@babel/preset-typescript": "^7.10.1",
    "@parcel/transformer-image": "^2.0.0-nightly.2349",
    "@parcel/transformer-sass": "^2.0.0-nightly.727",
    "@types/jasmine": "^3.6.6",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "del": "^5.1.0",
    "gulp": "^4.0.2",
    "gulp-chmod": "^3.0.0",
    "gulp-delete-lines": "0.0.7",
    "gulp-file-checksum": "^2.0.1",
    "gulp-remove-code": "^3.0.4",
    "gulp-replace": "^1.0.0",
    "gulp-sftp": "git+https://git@github.com/webksde/gulp-sftp.git",
    "gulp-zip": "^5.0.1",
    "jasmine": "^3.6.4",
    "jasmine-console-reporter": "^3.1.0",
    "parcel": "^2.0.0-nightly.725",
    "puppeteer": "^8.0.0",
    "sass": "^1.26.8",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  },
  "browserslist": [
    "last 1 Chrome version"
  ],
  "app": "dist/index.html",
  "targets": {
    "app": {
      "publicUrl": "./"
    }
  }
}

```

## 🤔 Expected Behavior

Build works.

## 😯 Current Behavior

Build fails.

```@parcel/packager-js: The expression evaluated to a falsy value:```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.725
| Node             | v14.15.0
| npm/Yarn         | npm 6.14.8
| Operating System | W10

### PR DESCRIPTION
**Pull request by mischnic**
Closes https://github.com/parcel-bundler/parcel/issues/3676, see https://github.com/parcel-bundler/parcel/issues/3676#issuecomment-860624452
Closes https://github.com/parcel-bundler/parcel/issues/6478
Fixes T-1061

### CODE REVIEW

File: packages/transformers/js/core/src/hoist.rs [hunk 1]
```diff
@@ -642,6 +642,9 @@ impl<'a> Fold for Hoist<'a> {
         // require('foo') -> $id$import$foo
         if let Some(source) = match_require(&node, &self.collect.decls, self.collect.ignore_mark) {
           self.add_require(&source);
+
+          // !!
+
```
Comment (mischnic) [inline packages/transformers/js/core/src/hoist.rs]: What we need here is the logic from the old scope hoisting implementation which checked `isUnused()`, so if the return value is unused (`require("x");` is a statement or as the non-last item in a sequence expression)

But that's harder with swc than with Babel

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.17s | -309.00ms |
| Cached | 438.00ms | +14.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 487.63kb | -166.00b 🚀 | 5.64s | -47.00ms |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 352.00ms | +25.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 487.63kb | -166.00b 🚀 | 5.55s | -110.00ms |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.29s | +40.00ms |
| Cached | 401.00ms | +8.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/302542877390537225)**

File: packages/transformers/js/core/src/hoist.rs (hunk 1 above)
Comment (devongovett) [reply packages/transformers/js/core/src/hoist.rs]: Why do we need to know if the return value is unused? Don't we still need to include the code for side effects?

Comment (mischnic) [reply packages/transformers/js/core/src/hoist.rs]: Yes, but the `'*'` symbol shouldn't be added.

Comment (devongovett) [reply packages/transformers/js/core/src/hoist.rs]: Oh I see. Well it probably shouldn't crash even if you did something like `var x = require('./x.css')`... Don't we do something in the non scope hoisting packager to handle adding an empty JS module when you imported a non-JS asset?

File: packages/packagers/js/src/ScopeHoistingPackager.js [hunk 2]
```diff
@@ -676,6 +676,10 @@ ${code}
       exportSymbol,
       symbol,
     } = this.bundleGraph.resolveSymbol(resolved, imported, this.bundle);
+    if (resolvedAsset.type !== 'js') {
+      // Graceful fallback for non-js imports
+      return '{}';
+    }
```
Comment (mischnic) [inline packages/packagers/js/src/ScopeHoistingPackager.js:682]: The non-scope-hoisting packager creates one new asset per non-JS dependency resolution, while this currently returns a new `{}` for every single use of that dependency:

```js
const x = require("./index.css");
console.log(x);
console.log(x);
```
becomes
```js
console.log({});
console.log({});
```

Comment (mischnic) [reply packages/packagers/js/src/ScopeHoistingPackager.js:682]: An alternative would be to insert this asset in the jsruntime, but that would require calling `getDependencyResolution` on every single dependency to find the non-js ones.

Comment (devongovett) [reply packages/packagers/js/src/ScopeHoistingPackager.js:682]: This seems fine to me. Not sure if anyone will really care that they get different objects back rather than the same one. Pretty edge case.

File: packages/transformers/js/core/src/hoist.rs [hunk 3]
```diff
@@ -471,6 +471,18 @@ impl<'a> Fold for Hoist<'a> {
                 }
               }
             }
+            Stmt::Expr(ExprStmt { expr, span }) => {
+              if let Some(source) =
```
Comment (devongovett) [inline packages/transformers/js/core/src/hoist.rs:475]: Can you add a comment about why this is handled here?

**Review by devongovett — APPROVED** [review]
