### PR TITLE
Check browserslist prop in package.json for environments

### LINKED ISSUE #1026: Parsing objects for browserslist fails
Parcel doesn't interpret environments in a browserslist config.

Using this config

```json
  "browserslist": {
    "development": ">2%, last 1 edge versions, not ie > 0, not op_mini all",
    "production": ">2%, last 1 edge versions, not ie > 0, not op_mini all"
  }
```

Results in

```sh
🚨  <file>: Browser queries must be an array. Got object.
    at browserslist (.../node_modules/browserslist/index.js:207:11)
    at getTargetEngines (.../node_modules/parcel-bundler/src/utils/getTargetEngines.js:69:24)
    at <anonymous>
```

It looks like the main `browserslist(queries, opts)` API that's exported isn't meant to know about environments (it's left to the user to determine which environment to supply it with).

### PR DESCRIPTION
**Pull request by nicolaisueper**
This will fix #1026.

Please let me know if I should change anything.

Regards
Nico

### CODE REVIEW

**Comment by devongovett** [comment]
Awesome, thanks for working on this. Could you add a test to cover this change?

**Comment by nicolaisueper** [comment]
I encountered a problem testing this feature/fix.

[Over here](https://github.com/parcel-bundler/parcel/pull/1053/files#diff-62939a6d4567e7b9e2741ec83de4c4e4R41) I determine the browserlist-prop to use by checking `NODE_ENV` for any value. When running the tests, `NODE_ENV` equals to undefined.

I also have no idea how to reach the options I pass the bundler inside the tests.

Would you please give me a hint how to continue? I pushed a WIP test case w/ my last commit.

**Comment by nicolaisueper** [comment]
I had to refactor things to get the tests running.
I'd be happy if anyone can review this. I'm not very happy with the solution but I didn't find another way.

File: src/Bundler.js [hunk 1]
```diff
@@ -72,6 +72,7 @@ class Bundler extends EventEmitter {
       outDir: Path.resolve(options.outDir || 'dist'),
       outFile: options.outFile || '',
       publicURL: publicURL,
+      isProduction,
```
Comment (DeMoorJasper) [inline src/Bundler.js]: Could u rename this to `production` instead of `isProduction` as we used the key `production` in the vue branch

File: src/Parser.js [hunk 2]
```diff
@@ -73,7 +74,7 @@ class Parser {
   getAsset(filename, pkg, options = {}) {
     let Asset = this.findParser(filename);
     options.parser = this;
-    return new Asset(filename, pkg, options);
+    return new Asset(filename, pkg, options, this.isProdBuild);
```
Comment (DeMoorJasper) [inline src/Parser.js]: You don't need to pass this as it's part of the options?

File: src/Parser.js [hunk 3]
```diff
@@ -46,6 +46,7 @@ class Parser {
     for (let ext in extensions) {
       this.registerExtension(ext, extensions[ext]);
     }
+    this.isProdBuild = options.isProduction;
```
Comment (DeMoorJasper) [inline src/Parser.js]: You don't need to set this as it's part of the options?

File: src/assets/JSAsset.js [hunk 4]
```diff
@@ -19,14 +19,15 @@ const SW_RE = /\bnavigator\s*\.\s*serviceWorker\s*\.\s*register\s*\(/;
...
-  constructor(name, pkg, options) {
+  constructor(name, pkg, options, isProdBuild) {
     super(name, pkg, options);
     this.type = 'js';
     this.globals = new Map();
     this.isAstDirty = false;
     this.isES6Module = false;
     this.outputCode = null;
     this.cacheData.env = {};
+    this.isProdBuild = isProdBuild;
```
Comment (DeMoorJasper) [inline src/assets/JSAsset.js]: This should normally be part of the this.options

File: src/transforms/babel.js [hunk 5]
```diff
@@ -26,8 +26,8 @@ const JSX_PRAGMA = {
   hyperapp: 'h'
 };
 
-async function babelTransform(asset) {
-  let config = await getConfig(asset);
+async function babelTransform(asset, isProdBuild) {
```
Comment (DeMoorJasper) [inline src/transforms/babel.js]: shouldn't be necessary as asset.options.production should return the same as `isProdBuild `

File: src/Parser.js (hunk 3 above)
Comment (nicolaisueper) [reply src/Parser.js]: The options don't get stored inside the parser object. Should I do `this.options = options` instead?

File: src/assets/JSAsset.js (hunk 4 above)
Comment (nicolaisueper) [reply src/assets/JSAsset.js]: This is just the asset options, not the application options afaik

Comment (nicolaisueper) [reply src/assets/JSAsset.js]: Oh, you're right

File: src/transforms/babel.js (hunk 5 above)
Comment (nicolaisueper) [reply src/transforms/babel.js]: Refactored 👌

**Comment by Grawl** [comment]
There is no documentation for this feature on Parcel website.
