### PR TITLE
fix: process meta tag dependencies

### LINKED ISSUE #6702: Meta tags e.g. `og:image` and `twitter:image` do not get resolved to absolute URLs
# 🐛 bug report

When using meta tags for social, particularly the `twitter:image` meta, you need to use an absolute URL otherwise the image won't appear on twitter. Whilst you can use `publicUrl` in the CLI or config, this changes all the URLs which then means if you have a staging site or Previews e.g when using Firebase, the site cannot resolve any of the assets because it's looking at absolute URLs which have not been updated.

## 🎛 Configuration (.babelrc, package.json, cli command)

No config used, just running `parcel build ./src/index.html`

## 🤔 Expected Behavior

meta tags should be parsed to append (if present) `og:url` to the meta tags for things like `og:image`, `twitter:image`.

## 😯 Current Behavior

If you don't use `publicUrl` they have relative URLs, using `publicUrl` appends everything which can't be used in previews or staging links. Appending it yourself means the asset is not pulled in via the bundler and if it is by a different link, it won't have the correct hash suffix.

## 💁 Possible Solution

I imagine a plugin can be built for this around `html` and then included.

## 🔦 Context

When i'm building a client's site and deploying their social cards do not have the image visible, unless I manually change the built files, so deployments then become manual again.

## 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta property="og:url" content="https://mydomain.com" />
    <meta property="og:image" content="assets/meta/NFHQ_OG.jpg" />
    <meta name="twitter:image" content="assets/meta/NFHQ_OG.jpg" />
  </head>
  <body> 
    <h1>hello world</h1>
  </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | 16.2.0 |
| npm/Yarn         | yarn |
| Operating System | MacOS |

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

This PR adds back the processing of meta tags

Closes #6702 

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.21s | -95.00ms |
| Cached | 321.00ms | +6.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.html | 775.00b | +0.00b | 1.36s | +203.00ms ⚠️ |
| dist/modern/index.html | 715.00b | +0.00b | 1.36s | +203.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 11.37s | -15.00ms |
| Cached | 505.00ms | +10.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 240.00ms | -25.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.22m | -1.25s |
| Cached | 1.83s | -3.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.9779ace0.js | 1.77mb | +2.00b ⚠️ | 20.68s | -743.00ms |
| dist/index.957c414c.js | 694.59kb | +15.00b ⚠️ | 55.56s | +13.62s ⚠️ |
| dist/editorView.510b5f4c.js | 594.90kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/popup.5797319a.js | 209.65kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/EmojiPickerComponent.3fd2da43.js | 146.66kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/index.e0e9517a.js | 145.42kb | +0.00b | 55.56s | +13.62s ⚠️ |
| dist/Toolbar.98d22779.js | 107.22kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/card.719fd13b.js | 62.65kb | +0.00b | 55.55s | +13.61s ⚠️ |
| dist/Modal.b96e8679.js | 45.31kb | -15.00b 🚀 | 54.96s | +13.01s ⚠️ |
| dist/esm.e1ed465b.js | 33.13kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/DatePicker.14403a6b.js | 22.96kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/js.0f0bb621.js | 17.24kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/ui.2d51cb62.js | 14.93kb | +0.00b | 54.96s | +13.01s ⚠️ |
| dist/smartMediaEditor.ffc51334.js | 13.24kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/dropzone.0d183115.js | 12.13kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/card.45f850d6.js | 5.75kb | +0.00b | 55.55s | +13.61s ⚠️ |
| dist/EmojiPickerComponent.55e0a64c.js | 3.71kb | +0.00b | 54.96s | +13.01s ⚠️ |
| dist/png-chunks-extract.94b5b9fc.js | 3.56kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/dropzone.cf53fd41.js | 3.28kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/Modal.7f4c60b3.js | 3.13kb | +0.00b | 55.55s | +13.61s ⚠️ |
| dist/clipboard.d25985ee.js | 2.92kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/ResourcedEmojiComponent.78f6ddfc.js | 2.10kb | +0.00b | 54.96s | +13.01s ⚠️ |
| dist/feedback.e18b45f0.js | 1.75kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/browser.09200cd5.js | 1.68kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/workerHasher.567cfc57.js | 1.62kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/heading6.b3b946d1.js | 1.49kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/heading5.e617db66.js | 1.37kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/expand.1f17de7f.js | 1.27kb | +0.00b | 33.96s | +10.75s ⚠️ |
| dist/media-card-analytics-error-boundary.75fac461.js | 1.10kb | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/media-picker-analytics-error-boundary.1602c912.js | 949.00b | +0.00b | 54.96s | +13.02s ⚠️ |
| dist/media-card-analytics-error-boundary.b1a780f3.js | 945.00b | +0.00b | 55.55s | +13.61s ⚠️ |
| dist/simpleHasher.2a6e12b6.js | 626.00b | +0.00b | 54.96s | +13.01s ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.fe7ac9a4.js | 694.58kb | +19.00b ⚠️ | 56.26s | -1.06s |
| dist/EmojiPickerComponent.b962c268.js | 146.66kb | +0.00b | 34.91s | +11.71s ⚠️ |
| dist/esm.2799b52b.js | 33.13kb | +0.00b | 34.91s | +11.71s ⚠️ |
| dist/DatePicker.b95c367a.js | 22.96kb | +0.00b | 34.91s | +11.71s ⚠️ |
| dist/js.0f0bb621.js | 17.24kb | +0.00b | 55.66s | +13.42s ⚠️ |
| dist/png-chunks-extract.94b5b9fc.js | 3.56kb | +0.00b | 55.66s | +13.42s ⚠️ |
| dist/feedback.e18b45f0.js | 1.75kb | +0.00b | 34.91s | +11.71s ⚠️ |
| dist/workerHasher.567cfc57.js | 1.62kb | +0.00b | 34.91s | +11.71s ⚠️ |
| dist/heading6.b3b946d1.js | 1.49kb | +0.00b | 34.91s | +11.71s ⚠️ |
| dist/heading5.e617db66.js | 1.37kb | +0.00b | 34.91s | +11.71s ⚠️ |
| dist/expand.1f17de7f.js | 1.27kb | +0.00b | 34.91s | +11.71s ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.56s | -77.00ms |
| Cached | 413.00ms | -26.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/307652535352558146)**

File: packages/transformers/html/src/dependencies.js [hunk 1]
```diff
@@ -122,19 +122,26 @@ export default function collectDependencies(
...
+        return (
+          values &&
+          values.includes(attrs[attr]) &&
+          attrs.content !== '' &&
+          !(attrs.name === 'msapplication-config' && attrs.content === 'none')
+        );
+      });
+      if (isMetaDependency) {
+        const metaAssetUrl = attrs.content;
+        if (metaAssetUrl && !/^(http|https):\/\//.test(metaAssetUrl)) {
```
Comment (devongovett) [inline packages/transformers/html/src/dependencies.js]: Seems ok but don't we usually let resolvers handle full URLs? If they don't resolve to anything the original specifier gets put back. What was happening here?

Comment (DeMoorJasper) [reply packages/transformers/html/src/dependencies.js]: Just forgot we did that, will remove it

**Review by devongovett — APPROVED** [review]
