### PR TITLE
Replace options.entryRoot with bundleGraph.getEntryRoot(target)

### LINKED ISSUE #6458: Wrong distDir when using `parcel watch .`
# 🐛 bug report

The output of `parcel watch .` ends up in the wrong directory.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
// package.json
{
  "private": true,
  "targets": {
    "default": {
      "context": "browser",
      "source": "src/index.html",
      "distDir": "public"
    }
  },
  "scripts": {
    "watch": "parcel watch ."
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.3.1"
  }
}
```

The only other file I have is `src/index.html`.

bilde

## 🤔 Expected Behavior

I want parcel to build and produce `public/index.html`. 

## 😯 Current Behavior

When I run this the file ends up in `public/<parent-folder-name>/src/index.html`. In the image below (and above) the project is in the folder `parcel-test`, which is why the build output is in `public/parcel-test/index.html`. 

bilde

## 💻 Code Sample

There's not much more than the `package.json` file in this scenario, just an html file with the default content from vscode snippet `html:5`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | 14.16.1 |
| npm/Yarn         | 6.14.12 |
| Operating System | Windows 10 |

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #6458.

`options.entryRoot` is used during naming as a common root directory from which to determine relative paths for non-hashed bundles. However, this is computed before entry resolution, so if an entry resolves to a directory, the computed root will be wrong. In addition, if entries have different targets, it will also be incorrect. This PR replaces this with a `bundleGraph.getEntryRoot` method, which receives a target, finds all of the entries associated with that target distDir, and computes the common root dir from there. This is memoized per target dist dir for performance.

In addition, it seems we were exposing internal bundle group objects with project paths instead of full file paths. This adds a public wrapper class for bundle groups like we have for all of our other public objects.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.47s | +115.00ms |
| Cached | 373.00ms | -18.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 5.67s | -148.00ms |
| Cached | 344.00ms | -20.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/305020371645497921)**

File: packages/core/core/src/public/BundleGroup.js [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+  IBundleGroup,
+  InternalBundleGroup,
+> = new WeakMap();
+export function bundleGroupToInternalBundleGroup(
+  target: IBundleGroup,
+): InternalBundleGroup {
+  return nullthrows(_bundleGroupToInternalBundleGroup.get(target));
+}
+
+export default class BundleGroup implements IBundleGroup {
```
Comment (wbinnssmith) [inline packages/core/core/src/public/BundleGroup.js:25]: 🤩

**Review by wbinnssmith — APPROVED** [review]
