### PR TITLE
Pass .posthtmlrc options to posthtml-parse

### LINKED ISSUE #1103: 🐛Vue self-closing tags broken on build but fine on dev
When a `div` is self-closed in vue template, it will not correctly closed causing things below get embed in that self-closing tag.

| Code | Result |
|------|--------|
| image | image |

And strangely it's a production-build-only (`parcel build`) bug. Works fine on dev.

### 🎛 Configuration (.babelrc, package.json, cli command)

Included in repro.

### 💁 Possible Solution

No idea, even don't know it's a Vue issue or a Parcel issue.

### 💻 Code Sample

https://github.com/laosb/parcel-vue-test/commit/60baa3f7e1de3b963a5af1aeddba10d5e24a49a6

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0 |
| Node             |  9.8.0 |
| npm/Yarn         | Yarn 1.5.1 |
| Operating System | macOS 10.13.3 |

### LINKED ISSUE #1123: Parcel lowercasing Vue attributes
🐛 bug report

I noticed that my logo component in Vue is huge when I run `parcel index.html`. I looked at both the Webpack output code and the Parcel output code and the only thing that was different was that Parcel caused my SVG's `viewBox` attribute to be all lowercase (`viewbox`) which breaks it (at least in the latest version of FireFox).

After testing it out some more, I noticed it doesn't change the capitalization when I remove the `use` elements and `xlink`.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"presets": [
		["env", {
			"modules": false,
			"targets": {
				"browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
			}
		}],
		"stage-2"
	],
	"plugins": [
		"transform-runtime"
	],
	"env": {
		"test": {
			"presets": ["env", "stage-2"],
			"plugins": ["istanbul"]
		}
	}
}
```

### PR DESCRIPTION
**Pull request by luikore**
This pull request makes HTML parsing options configurable, so HTMLAsset parsing / transform behavior can be more consistent.

With this change we can config `.posthtmlrc` with the following options (they are consumed by posthtml-parse, then htmlparser2. See also https://github.com/fb55/htmlparser2/wiki/Parser-options )

- `xmlMode: true`
- `lowerCaseAttributeNames: false`
- `lowerCaseTags: false`
- `recognizeSelfClosing: true`
- ...

If we config `recognizeSelfClosing: true` in `.posthtmlrc`,  we can also fix #1103 

Allow setting `false` to lower case options maybe can also fix #1123 . (not tested yet)

### CODE REVIEW

**Comment by luikore** [comment]
@devongovett 
The vue support of parcel is still basically unusable due to so many bugs.
I hope some one can really pay some time to have a review about this?
Or just say you prefer other way for the fix so I can change or close this?

File: src/transforms/posthtml.js [hunk 1]
```diff
@@ -1,7 +1,17 @@
 const loadPlugins = require('../utils/loadPlugins');
 const posthtml = require('posthtml');
+const posthtmlParse = require('posthtml-parser');
 
-module.exports = async function(asset) {
+async function parse(code, asset) {
+  var config = await getConfig(asset);
```
Comment (DeMoorJasper) [inline src/transforms/posthtml.js]: Is the configuration format identical in parser and transform?

File: src/transforms/posthtml.js [hunk 2]
```diff
@@ -11,20 +21,28 @@ module.exports = async function(asset) {
...
   }
 
   config = Object.assign({}, config);
   config.plugins = await loadPlugins(config.plugins, asset.name);
   config.skipParse = true;
-  return config;
+  return config
+}
+
+module.exports = {
```
Comment (DeMoorJasper) [inline src/transforms/posthtml.js]: this can be written as `module.exports = {parse, transform};`

File: src/transforms/posthtml.js [hunk 3]
```diff
@@ -11,20 +21,28 @@ module.exports = async function(asset) {
...
+  asset.isAstDirty = true
+}
 
 async function getConfig(asset) {
-  let config = await asset.getConfig(
-    ['.posthtmlrc', '.posthtmlrc.js', 'posthtml.config.js'],
-    {packageKey: 'posthtml'}
-  );
+  let config =
+    asset.getPackage().posthtml ||
```
Comment (fathyb) [inline src/transforms/posthtml.js]: `asset.getPackage()` returns a `Promise` so your expression always evaluate to `undefined` :

https://github.com/parcel-bundler/parcel/blob/16149185bdd386cf478b08629fd2776dce76c943/src/Asset.js#L127-L133

Use `await` :

```js
(await asset.getPackage()).posthtml || ...
```

File: src/transforms/posthtml.js [hunk 4]
```diff
@@ -11,20 +21,28 @@ module.exports = async function(asset) {
...
+    ]));
   if (!config && !asset.options.minify) {
     return;
   }
 
   config = Object.assign({}, config);
   config.plugins = await loadPlugins(config.plugins, asset.name);
   config.skipParse = true;
-  return config;
+  return config
```
Comment (fathyb) [inline src/transforms/posthtml.js]: Looks like Prettier did not format (`--no-verify`?), you can manually run it by running `yarn format` or `npm run format`.

File: src/assets/HTMLAsset.js [hunk 5]
```diff
@@ -73,14 +72,14 @@ const OPTIONS = {
 };
 
 class HTMLAsset extends Asset {
-  constructor(name, options) {
-    super(name, options);
+  constructor(name, pkg, options) {
+    super(name, pkg, options);
```
Comment (fathyb) [inline src/assets/HTMLAsset.js]: We don't pass `pkg` to the `constructor` anymore for perf reasons : 

```js
constructor(name, options) {
  super(name, options)
```

File: src/transforms/posthtml.js (hunk 3 above)
Comment (luikore) [reply src/transforms/posthtml.js]: Updated.

File: src/transforms/posthtml.js (hunk 4 above)
Comment (luikore) [reply src/transforms/posthtml.js]: Did not know this before, updated

File: src/assets/HTMLAsset.js (hunk 5 above)
Comment (luikore) [reply src/assets/HTMLAsset.js]: Updated.

File: src/transforms/posthtml.js (hunk 1 above)
Comment (luikore) [reply src/transforms/posthtml.js]: Yes, but different options are used. Do you prefer these configs to be different objects?

Comment (DeMoorJasper) [reply src/transforms/posthtml.js]: As long as they can’t conflict it should be fine but it sounds like they can

Comment (luikore) [reply src/transforms/posthtml.js]: How about putting these options into a new htmlparser2rc ?

Comment (DeMoorJasper) [reply src/transforms/posthtml.js]: I was thinking more of something like this:

Comment (DeMoorJasper) [reply src/transforms/posthtml.js]: But as you said they won't conflict I think it's safe for now to just let this PR be as is

File: src/transforms/posthtml.js [hunk 6]
```diff
@@ -12,13 +22,16 @@ module.exports = async function(asset) {
...
-    ['.posthtmlrc', '.posthtmlrc.js', 'posthtml.config.js'],
-    {packageKey: 'posthtml'}
-  );
+  let config =
+    (await asset.getPackage()).posthtml ||
+    (await asset.getConfig([
+      '.posthtmlrc',
+      '.posthtmlrc.js',
+      'posthtml.config.js'
+    ]));
```
Comment (devongovett) [inline src/transforms/posthtml.js]: Did `packageKey` not work?

File: src/transforms/posthtml.js (hunk 1 above)
Comment (devongovett) [reply src/transforms/posthtml.js]: I think this will result in getting the config twice... once for parse, and once for transform. Maybe ok because of the cache? Just pointing that out.
