### PR TITLE
Scope hoisting renaming after babel transforms

### LINKED ISSUE #1538: Experimental scope hoisting: Cannot read property 'constantViolations' of undefined
# 🐛 bug report

I tried to build my React project with the new experimental scope hoisting enabled (`--experimental-scope-hoisting`) and it crashed (works without the feature enabled).

## 🎛 Configuration

cli:
`parcel build src/index.html --out-dir dist --public-url ./dist/ --no-cache --experimental-scope-hoisting`

.babelrc:
```js
{
  "presets": [
    "env",
    "react"
  ],
  "plugins": [
    [ "transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true,
      "moduleName": "babel-runtime"
    } ],
    "styled-components",
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-async-to-generator",
    "inline-react-svg",
    "react-intl"
  ]
}
```

## 🤔 Expected Behavior

Parcel bundles my application.

## 😯 Current Behavior

Parcel didn't bundle my application.

Stacktrace:
```
🚨  /Users/user/development/project/src/shared/services/LanguageService.js: Cannot read property 'constantViolations' of undefined
    at rename (/Users/user/development/project/node_modules/parcel-bundler/src/scope-hoisting/renamer.js:9:33)
    at JSAsset.ImportDeclaration (/Users/user/development/project/node_modules/parcel-bundler/src/scope-hoisting/hoist.js:325:7)
    at NodePath._call (/Users/user/development/project/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/user/development/project/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/user/development/project/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/user/development/project/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/user/development/project/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/user/development/project/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/user/development/project/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/user/development/project/node_modules/babel-traverse/lib/path/context.js:115:19)
```

## 🔦 Context

My `LanguageService` contains some dynamic imports and has only one import (`browser-locale`) - maybe it's related to the dynamic imports or to that package in particular?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.0 |
| Node             | 8.9.1 |
| npm/Yarn         | npm 6.1.0 |
| Operating System | macOS High Sierra |

### LINKED ISSUE #1699: Tree shaking and React
# 🐛 bug report

I am experiencing a faulty behavior when generating a production bundle using the experimental tree shaking feature.

[I have already logged this in the Spectrum channel](https://spectrum.chat/?t=811287bb-429b-4843-9f37-40c576a1e0d6) but decided to open a proper bug report as well.

## 🎛 Configuration (.babelrc, package.json, cli command)

I put together a repository so you can reproduce the same behavior I am experiencing: https://github.com/rafaelrinaldi/parcel-tree-shaking-jsx-error

## 🤔 Expected Behavior

Tree shaking should work just fine.

## 😯 Current Behavior

Tree shaking kinda works but seems to bypass React, logging "React is not defined" in the console.

## 💁 Possible Solution

I believe that this could be two of the following:

1. "React" is imported whenever JSX is used but not necessarily is being referenced, so the tree shaking might be skipping it for that reason (even though the `babel-plugin-transform-react-jsx` plugin added by the `babel-preset-react` should be replacing JSX nodes by `React.createElement()` calls, therefore notifying the tree shaking algorithm that the module is being used)
2. It might be an module load ordering/evaluation issue in Parcel. Perhaps even solved by #1694 

## 🔦 Context

I'm trying to get the experimental tree shaking feature to work in a project that uses a route-based code splitting strategy using react router and react loadable.

## 💻 Code Sample

I put together a repository so you can reproduce the same behavior I am experiencing: https://github.com/rafaelrinaldi/parcel-tree-shaking-jsx-error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4 |
| Node             | v10.6.0 |
| npm         | 6.1.0 |
| Operating System | macOS High Sierra |

### LINKED ISSUE #1821: babel lodash plugin and parcel tree shaking
# 🐛 bug report

[lodash plugin for babel](https://github.com/lodash/babel-plugin-lodash) does not seem to work with `parcel --experimental-scope-hoisting`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "name": "parcelbabel",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "build": "NODE_ENV=production && rm -rf ./dist && parcel build --experimental-scope-hoisting index.html"

    },
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "babel-plugin-lodash": "^3.3.4",
        "parcel-bundler": "^1.9.7"
    },
    "babel": {
        "plugins": ["lodash"]
    }
}
```

## 🤔 Expected Behavior

It should build properly.

## 😯 Current Behavior
Build errors out with the following error:
```
🚨  /home/andymac/devl/parcelbabel/index.js: Cannot read property 'constantViolations' of undefined
    at rename (/home/andymac/devl/parcelbabel/node_modules/parcel-bundler/src/scope-hoisting/renamer.js:9:33)
    at JSAsset.ImportDeclaration (/home/andymac/devl/parcelbabel/node_modules/parcel-bundler/src/scope-hoisting/hoist.js:327:7)
    at NodePath._call (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/andymac/devl/parcelbabel/node_modules/babel-traverse/lib/path/context.js:115:19)
```

## 💁 Possible Solution

Not sure.  I know I could (and I have) refactored my code to use 'lodash-es' and import single functions.  But I thought this bug report could be useful. 

## 💻 Code Sample
minimal code sample:
https://github.com/zxol/parcelbabel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.97
| Node             | 8.11.3
| npm/Yarn         | 5.5.1
| Operating System | ubuntu 16.04

### LINKED ISSUE #2084: Scope hoisting/tree shaking bug (--experimental-scope-hoisting)
# 🐛 bug report

Bundle missing [pragma function](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx) used to transform jsx to vnodes.

## 🎛 Configuration (.babelrc, package.json, cli command)
`parcel build ./src/app.js --experimental-scope-hoisting --no-minify`

Default babel config

## 🤔 Expected Behavior

Pragma function is not tree shaked from source 

## 😯 Current Behavior
Pragma function removed from bundle

In my case: `Uncaught ReferenceError: h is not defined`
## 💁 Possible Solution

Pragma function imported to source, but the function invocation only occurs in the transpiled source
(after `babel-plugin-transform-react-jsx` transformations), as result pragma function invocations are not visible for tree shaking and they are removed.

## 💻 Code Sample

```javascript
import { h } from 'hyperapp';
export default <div>test</div>;
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel      | 1.10.1
| Node        | v8.9.4
| npm/Yarn         |
| Operating System |

### LINKED ISSUE #2204: Extending EventEmitter throws error in production bundle when using --experimental-scope-hoisting flag
# 🐛 bug report
Issue happens if you try to create a new class that extends EventEmitter. When I try to build code using tree shaking flag, I get error that global variable `EventEmitter` doesn't exist. Everything works fine in development mode, as well as build without experimental flag.

## 🤔 Expected Behavior
Application should work as it does in build without using experimental flag

## 😯 Current Behavior

I get following error in console:
```
Uncaught ReferenceError: EventEmitter is not defined
    at app.fc2a6f9a.js:1
    at app.fc2a6f9a.js:1
    at app.fc2a6f9a.js:1
(anonymous) @ app.fc2a6f9a.js:1
(anonymous) @ app.fc2a6f9a.js:1
(anonymous) @ app.fc2a6f9a.js:1
```

## 🔦 Context
Building code with tree shaking

## 💻 Code Sample
run `parcel build --experimental-scope-hoisting index.html` after cloning: 
https://github.com/dugokontov/parcel-tree-shaking-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.10.3
| Node             |8.11.1
| npm/Yarn         |6.4.1/1.10.0
| Operating System |Linux Mint 18.1 Serena

### LINKED ISSUE #2255: scope hoisting: Cannot read property 'constantViolations' of undefined
# 🐛 bug report
 
https://github.com/parcel-bundler/parcel/blob/v1.10.3/src/scope-hoisting/renamer.js#L6 will be throw an error  **Cannot read property 'constantViolations' of undefined** when l use 
```npx -n '--inspect-brk' parcel build  --no-minify --experimental-scope-hoisting --no-source-maps --no-cache --log-level 4 main.js```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/runtime": "^7.1.2",
    "lodash.once": "^4.1.1",
    "parcel-bundler": "^1.10.3"
  },
  "license": "ISC"
}

// .babelrc
{
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": false,
        "helpers": false,
        "regenerator": true
      }
    ]
  ]
}
```

## 😯 Current Behavior
blocking

### main.js
```
const v  = async () => {
	const x = await new Promise((resolve) => {
		resolve(1)
	});

	return x;
};

v().then(r=>{
	console.log(r);
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             |  10.13
| npm/Yarn         | 6.4.1
| Operating System | mac

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

With this change the renaming part of scope-hoisting seems to work with other babel-transforms as well. E.g.:
1. Superclass identifiers get renamed correctly (closes #2204)
2. `<span>Test</span>` gets transpiled to `React.createElement("span", null, "Test")`, but React isn't getting renamed (same for `h` of preact, hyperapp). (closes #1699, closes #2084)
3. `babel-plugin-lodash` transforms the ast just like jsx (closes #1821)
5. most things regarding `constantViolations undefined`: with `styled-jsx` - closes #1538, with `plugin-transform-runtime` - closes #2255

I've added test for jsx and superclasses to the scope-hoisting/es6 folder.

Is a reason for the custom renaming logic? All scope-hoisting tests still pass with simply `scope.rename(oldName, newName)`. 

## 💻 Examples

Previously, scope-hoisting didn't correctly rename the superclass identifier (same problem with jsx)

src:
```js
import Component from "./x.js";

console.log(Component);

class App extends Component {}
```
Before hoisting:
```js
// ...

import Component from "./x.js";
console.log(Component);

var App =
/*#__PURE__*/
function (_Component) {
  _inherits(App, _Component);

  function App() {
    _classCallCheck(this, App);

    return _possibleConstructorReturn(this, _getPrototypeOf(App).apply(this, arguments));
  }

  return App;
}(Component);
```

After hoisting:

```js
// ...

import $Focm$import$Component from "./x.js";
console.log($Focm$import$Component);

var App =
/*#__PURE__*/
function (_Component) {
  _inherits(App, _Component);

  function App() {
    _classCallCheck(this, App);

    return _possibleConstructorReturn(this, _getPrototypeOf(App).apply(this, arguments));
  }

  return App;
}(Component); // <--- Problem
```

### CODE REVIEW

File: packages/core/parcel-bundler/src/scope-hoisting/renamer.js [hunk 1]
```diff
@@ -3,31 +3,7 @@ function rename(scope, oldName, newName) {
...
-    if (path.node.name === oldName) {
-      path.node.name = newName;
-    }
-  }
-
-  // Rename binding identifier, and update scope.
-  binding.identifier.name = newName;
-  scope.bindings[newName] = binding;
-  delete scope.bindings[oldName];
+  scope.rename(oldName, newName);
```
Comment (devongovett) [inline packages/core/parcel-bundler/src/scope-hoisting/renamer.js]: Unfortunately the builtin renamer in babel is very slow, which is why we made our own. The builtin one does a tree traverse, so when bulk renaming variables it is O(n^2).

Could you see if it's possible to fix the bug by modifying the renamer we have already in parcel rather than switching back to the slow babel one?

Comment (mischnic) [reply packages/core/parcel-bundler/src/scope-hoisting/renamer.js]: Somehow this isn't consistent. First, the AST contains the class transpiled to a function. Then, inside the renaming for-loop it's a real classdeclaration again (correctly renamed) and afterwards, it a transpiled class again (but the `console.log(Component)` worked).
`rename` is all called by a ImportDeclaration visitor, could the class transform somehow run in parallel?

Replacing the `for (let path of binding.referencePaths)`-part with babel's solution works fine:
```js
scope.traverse(scope.block, {
	ReferencedIdentifier({node}) {
		if (node.name === oldName) {
			node.name = newName;
		}
	}
});
```


```js
function rename(scope, oldName, newName) {
	// -------- AST of scope -------- (correct)
	import Component from "./x.js";
	console.log(Component);

	var App =
	/*#__PURE__*/
	function (_Component) { // <--------------------------------------- class transpiled
	  _inherits(App, _Component);

	  function App() {
	    _classCallCheck(this, App);

	    return _possibleConstructorReturn(this, _getPrototypeOf(App).apply(this, arguments));
	  }

	  return App;
	}(Component);
	// -------- AST --------

	const binding = scope.getBinding(oldName);

	for (let path of binding.referencePaths) {
		if (path.node.name === oldName) {
			update name

			// -------- AST of path.parent -------- (1st run)
			console.log($Focm$import$Component)
			// -------- AST --------

			// -------- AST of path.parent -------- (2nd run)
			class App extends $Focm$import$Component { // <------------- now a classdeclaration again?
			  constructor() {
			    return _possibleConstructorReturn(this,
			    			_getPrototypeOf(App).apply(this, arguments));
			  }
			}
			// -------- AST --------
		}


	// -------- AST of scope -------- (halfway correct)
	import Component from "./x.js";
	console.log($Focm$import$Component); // <---------------------------- worked

	var App =
	/*#__PURE__*/
	function (_Component) {
	  _inherits(App, _Component);

	  function App() {
	    _classCallCheck(this, App);

	    return _possibleConstructorReturn(this, _getPrototypeOf(App).apply(this, arguments));
	  }

	  return App;
	}(Component); // <--------------------------------------------------- ?????
	// -------- AST --------
}
```

Comment (mischnic) [reply packages/core/parcel-bundler/src/scope-hoisting/renamer.js]: Well, this would fix it as well - but I guess crawl isn't much better than traverse?

```diff
diff --git a/packages/core/parcel-bundler/src/scope-hoisting/hoist.js b/packages/core/parcel-bundler/src/scope-hoisting/hoist.js
index afc01e4..70b84a5 100644
--- a/packages/core/parcel-bundler/src/scope-hoisting/hoist.js
+++ b/packages/core/parcel-bundler/src/scope-hoisting/hoist.js
@@ -344,6 +344,8 @@ module.exports = {
   ImportDeclaration(path, asset) {
     // For each specifier, rename the local variables to point to the imported name.
     // This will be replaced by the final variable name of the resolved asset in the packager.
+    path.scope.crawl();
+
     for (let specifier of path.node.specifiers) {
       let id = getIdentifier(asset, 'import', specifier.local.name);
       rename(path.scope, specifier.local.name, id.name);
```

Comment (devongovett) [reply packages/core/parcel-bundler/src/scope-hoisting/renamer.js]: could you try putting that `scope.crawl()` call at the top in the `Program.enter` visitor? This way it will happen once at the beginning of the traversal rather than every time an import declaration is hit.

Comment (mischnic) [reply packages/core/parcel-bundler/src/scope-hoisting/renamer.js]: Still works

File: packages/core/parcel-bundler/src/scope-hoisting/hoist.js [hunk 2]
```diff
@@ -51,6 +51,8 @@ function hasSideEffects(asset, {sideEffects} = asset._package) {
 module.exports = {
   Program: {
     enter(path, asset) {
+      path.scope.crawl();
```
Comment (fathyb) [inline packages/core/parcel-bundler/src/scope-hoisting/hoist.js]: I don't get why we need this, isn't babel traverse going to `.crawl` for us already?

Comment (mischnic) [reply packages/core/parcel-bundler/src/scope-hoisting/hoist.js]: Here is an explanation: https://github.com/parcel-bundler/parcel/issues/1699#issuecomment-404248874

Comment (devongovett) [reply packages/core/parcel-bundler/src/scope-hoisting/hoist.js]: I think babel doesn't recrawl the scope automatically, only when the scope is first initialized. That happens before lots of babel transforms run which can modify references, in this case the class transform. Then we get to our hoisting transform and we need to re-crawl to make sure we have updated references since babel traverse doesn't do that automatically.
