### PR TITLE
Normalize case of SVG elements and attributes in HTML, and preserve accessibility attributes

### LINKED ISSUE #4675: Inline SVGs are modified, stripping out accessibility features on production builds
# 🐛 bug report

When an HTML file is built for production, inline SVGs are modified. In the _Code Sample_ section I have provided an example input and its output. As you can see, the `title` tag and `role` attributes are removed, but they should be [preserved for acccessibility](https://developer.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/).

## 🎛 Configuration (.babelrc, package.json, cli command)

**.htmlnanorc** (added due to #4649)
```json
{
  "minifySvg": {
    "plugins": [
      {
        "cleanupIDs": false
      }
    ]
  }
}
```

## 🤔 Expected Behavior

The inline SVG should not be tampered with, or at least accessibility features should not be stripped out.

## 😯 Current Behavior

Accessibility features (like `<title>` and `role="presentation"`) in SVGs are removed in production builds.

## 💁 Possible Solution

There should be an option not to optimize inline SVGs when building for production.

## 🔦 Context

When building for production, I have noticed my accessibility score to drop compared to development builds. The gradients in SVGs were broken (due to #4649).

## 💻 Code Sample

```bash
NODE_ENV=production parcel build src/index.html
```

```html
<!-- input index.html -->
<svg class="w-12 h-12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  <title>Generic code icon</title>
  <path role="presentation" d="M0 0h24v24H0V0z" fill="none" />
  <path
    role="presentation"
    d="M8.7 15.9L4.8 12l3.9-3.9c.39-.39.39-1.01 0-1.4-.39-.39-1.01-.39-1.4 0l-4.59 4.59c-.39.39-.39 1.02 0 1.41l4.59 4.6c.39.39 1.01.39 1.4 0 .39-.39.39-1.01 0-1.4zm6.6 0l3.9-3.9-3.9-3.9c-.39-.39-.39-1.01 0-1.4.39-.39 1.01-.39 1.4 0l4.59 4.59c.39.39.39 1.02 0 1.41l-4.59 4.6c-.39.39-1.01.39-1.4 0-.39-.39-.39-1.01 0-1.4z"
  />
</svg>

<!-- output index.html -->
<svg class="w-12 h-12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M8.7 15.9L4.8 12l3.9-3.9a.984.984 0 000-1.4.984.984 0 00-1.4 0l-4.59 4.59a.996.996 0 000 1.41l4.59 4.6c.39.39 1.01.39 1.4 0a.984.984 0 000-1.4zm6.6 0l3.9-3.9-3.9-3.9a.984.984 0 010-1.4.984.984 0 011.4 0l4.59 4.59c.39.39.39 1.02 0 1.41l-4.59 4.6a.984.984 0 01-1.4 0 .984.984 0 010-1.4z"/></svg>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | v12.16.1 |
| npm/Yarn         | 1.22.4 |
| Operating System | macOS Catalina 10.15.4 |

### LINKED ISSUE #5004: Using Parcel 2 SVG attributes are all getting lower cased
# 🐛 bug report

Using Parcel 2 when I build, my inline SVG graphics get their attributes lowercased. SVG is a case sensitive specification, so this is not desired.  

There are several other bug reports here about SVGO stripping out tags (like viewBox) which I believe is happening exactly because of this attribute lowercasing.

It feels like this is something that could be solved if I could get the correct configuration, but I've spent half a day on it and gotten nowhere... maybe someone here knows how to solve it?

(apart from this niggle I'm loving Parcel 2 so far)

## 🎛 Configuration

cli-command:     ```npx parcel build index.html  ```

#### package.json
```json
{
  "name": "parcel2-svg-test",
  "private": true,
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}
```
#### .posthtmlrc
```js
{
	"xmlMode": true,
	"recognizeSelfClosing": true,
	"lowerCaseAttributeNames": false,
}
```
#### .htmlnanorc
```js
{
	"minifySvg": false
}
```

## 🤔 Expected Behavior

Attributes in the <svg> specification should not be changed to lower case.

## 😯 Current Behavior

The svg gets all its attribute names converted to lower case:

```xml
<svg viewbox="1.8 2.4 2 2" preserveaspectratio="xMinYMin meet"> <defs> <filter id="blur"> <feGaussianBlur in="SourceGraphic" stddeviation="0.01"></feGaussianBlur> </filter> </defs> <g> <path d="M2 3C3 2 4 3 3 4" stroke-width="0.1" stroke="blue" fill="none" filter="url(#blur)"></path> </g> </svg>
```

## 💻 Code Sample

index.html
```html
<!DOCTYPE html><html lang="en"><head></head><body>

	<svg viewBox="1.8 2.4 2 2" preserveAspectRatio="xMinYMin meet">
		<defs>
			<filter id="blur">
				<feGaussianBlur in="SourceGraphic" stdDeviation="0.01" />
			</filter>
		</defs>
		<g>
			<path d="M2 3C3 2 4 3 3 4" stroke-width="0.1" stroke="blue" fill="none" filter="url(#blur)"/>
		</g>
	</svg>

</body></html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1|
| Node             |v14.4.0|
| npm         |6.14.5|
| Operating System | Windows 10|

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #4675. Fixes #5004.

HTML attributes and element names are case insensitive, including foreign content such as SVG. However, SVGO does not support this and expects case sensitive names. This normalizes element and attribute names within embedded SVG before running htmlnano so it works as expected.

In addition, this disables some SVGO options that remove accessibility attributes such as ARIA and `role`, as well as the `<title>` and `<desc>` elements. These should be preserved on SVG that is embedded within HTML.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.32s | +118.00ms |
| Cached | 484.00ms | +11.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 224.00ms | +15.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.90s | -140.00ms |
| Cached | 413.00ms | -17.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/304405000038122049)**

File: packages/core/integration-tests/test/html.js [hunk 1]
```diff
@@ -2322,8 +2322,16 @@ describe('html', function() {
   });
 
   it('should work with bundle names that have colons in them', async function() {
+    // Windows paths cannot contain colons, so write the file here (in memory).
+    await overlayFS.mkdirp(path.join(__dirname, 'integration/url-colon'));
```
Comment (AGawrys) [inline packages/core/integration-tests/test/html.js:2330]: Does this fix the colon issue? I notice the benchmarks still fail due to a invalid path with colons and I notice it on[ other PRs as well](https://github.com/parcel-bundler/parcel/pull/6514). Is that just a bug we introduced somewhere and is now in V2 ? 😟

Comment (devongovett) [reply packages/core/integration-tests/test/html.js:2330]: it should but it seems the test is still failing on windows. I will look into it

**Review by wbinnssmith — APPROVED** [review]
