### PR TITLE
Use local require for `@babel/core` and `postcss`

### LINKED ISSUE #5993: transformer-postcss default.fromJSON is not a function
# 🐛 bug report
I'm attempting to use SCSS/CSS modules with Parcel 2 beta 1 however, as soon as I add a module import, I get the following error:
```
🚨 Build failed.
@parcel/transformer-postcss: _postcss(...).default.fromJSON is not a function
TypeError: _postcss(...).default.fromJSON is not a function
    at Object.transform (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/config-default/node_modules/@parcel/transformer-postcss/lib/PostCSSTransformer.js:175:38)
    at async Transformation.runTransformer (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:830:5)
    at async Transformation.runPipeline (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:585:36)
    at async Transformation.runPipelines (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:413:40)
    at async Transformation.runPipelines (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:444:34)
    at async Transformation.run (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:316:19)
    at async Child.handleRequest (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/workers/lib/child.js:255:9)
✨  Done in 4.78s.

```

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```js
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-typescript",
        ["@babel/preset-react",
          {
            "runtime": "automatic"
          }
        ]
    ]
}
```

## 🤔 Expected Behavior
The module is correctly imported and compiled.

## 😯 Current Behavior
The build fails

## 🔦 Context
This is a React app with Typescript and I can't use Parcel 2 with css modules. If change it from a module to a plain CSS import, it works fine.

## 💻 Code Sample
Component.tsx
```
import {FunctionComponent} from "react";
import {NavLink, NavLinkProps} from 'react-router-dom';

import styles from '../../styles/components/SidenavItem.module.scss';
// I've also tried `* as styles`...

export const SidenavItem: FunctionComponent<Pick<NavLinkProps, "to">> = (props) => {
  return (
    <NavLink {...props} style={styles.a}>
      {props.children}
    </NavLink>
  )
};
```

SidenavItem.module.scss
```
a {
  color: red;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-beta.1`
| Node             | `14.15.1`
| npm/Yarn         | `1.22.10`
| Operating System | MacOS 11.2.2 on a MacBook Air M1

### PR DESCRIPTION
**Pull request by mischnic**
Closes T-877, Closes T-911, Closes https://github.com/parcel-bundler/parcel/issues/5993

This uses the approach we had some time ago: use the JSTransformer's `@babel/core` for it's default config, and the user's `@babel/config` (autoinstalled) for a custom babelrc.

Also makes the JSON parser for autoinstall more permissive, by just skipping messages that aren't valid JSON (to prevent that from bringing down the whole process).

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/298474691926950408)**

File: packages/transformers/babel/src/config.js [hunk 1]
```diff
@@ -59,6 +60,16 @@ export async function load(
     return;
   }
 
+  const babelCore: BabelCore = await options.packageManager.require(
```
Comment (devongovett) [inline packages/transformers/babel/src/config.js:63]: This won't get tracked for cache invalidation. We need to call `config.addDevDependency` here as well.

File: packages/transformers/postcss/src/PostCSSTransformer.js [hunk 2]
```diff
@@ -192,3 +198,11 @@ function createLoader(
     }
   };
 }
+
+function loadPostcss(options: PluginOptions, from: FilePath): Promise<Postcss> {
+  return options.packageManager.require('postcss', from, {
```
Comment (devongovett) [inline packages/transformers/postcss/src/PostCSSTransformer.js:203]: Same here

**Review by devongovett — CHANGES_REQUESTED** [review]

File: packages/core/package-manager/src/JSONParseStream.js [hunk 3]
```diff
@@ -17,7 +17,13 @@ export default class JSONParseStream extends Transform {
     callback: (err: ?Error, parsed: ?JSONObject) => mixed,
   ) {
     try {
-      callback(null, JSON.parse(chunk.toString()));
+      let parsed;
+      try {
+        parsed = JSON.parse(chunk.toString());
+      } catch (e) {
+        return;
```
Comment (wbinnssmith) [inline packages/core/package-manager/src/JSONParseStream.js:32]: Maybe a comment here that we're intentionally not calling the callback with these errors because some streaming JSON implementations leak non-json? (At least that's what I assume is going on here)

Additionally, maybe we could log these at verbose/debug levels of the logger?

Comment (mischnic) [reply packages/core/package-manager/src/JSONParseStream.js:32]: Exactly (this specific case in Yarn 2 will be fixed by https://github.com/yarnpkg/berry/pull/2883), I've added the comment.

Good idea to log it

File: packages/transformers/babel/src/babel7.js [hunk 4]
```diff
@@ -17,6 +17,14 @@ export default async function babel7(
   babelOptions: any,
   additionalPlugins: Array<any> = [],
 ): Promise<?AST> {
+  const babelCode = babelOptions.internal
```
Comment (devongovett) [inline packages/transformers/babel/src/babel7.js]: `babelCore` 😉

**Review by devongovett — APPROVED** [review]
lgtm other than the typo
