### PR TITLE
Add support for worklets and fix pipeline bugs

### LINKED ISSUE #1093: Loading script to AudioWorklet
❓Question:

I'm trying to use new AudioWorklet feature (enabled by default in Chrome 66 ->). Part of the process is to load a `WorkletProcessorScript` to a web worker from my main js file like this:

```
...
audioContext.audioWorklet.addModule('my-worklet-processor.js').then(() => {
  ...
});
```
So I'd need to keep `my-worklet-processor.js` as a separate file. Maybe this is already possible, but I can't find a way to do this. Any clues how to solve this? Big thanks! 🙏 

There's not yet good documentation on AudioWorklets, but [here](https://developers.google.com/web/updates/2017/12/audio-workletl) and [here](https://googlechromelabs.github.io/web-audio-samples/audio-worklet/) are some examples I've been using.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 8.9.4
| npm/Yarn         | npm 5.7.1
| Operating System | OSX 10.11.6

### LINKED ISSUE #2083: CSS paint worklet (Houdini) causes generic error
# 🐛 bug report

Houdini paint worklet causes cryptic `Uncaught (in promise) DOMException: The user aborted a request.` error

### package.json

```
{
  "name": "bruck",
  "version": "0.0.1",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html",
    "build": "parcel build index.html --out-dir docs"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Heydon/bruck.git"
  },
  "author": "Heydon Pickering <heydon@heydonworks.com> (http://www.heydonworks.com)",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/Heydon/bruck/issues"
  },
  "homepage": "https://github.com/Heydon/bruck#readme",
  "dependencies": {
    "components": "^0.1.0",
    "lib": "^3.0.2",
    "parcel-bundler": "^1.10.1"
  }
}
```

### Babel

Just using the default config

## 🤔 Expected Behavior

My CSS `paintWorklet` should be loaded and applied in my `app.js` file (see below).

```
/* Register paint workers */
if ('paintWorklet' in CSS) {
  CSS.paintWorklet.addModule('js/houdini/image-cross.js');
}
```

## 😯 Current Behavior

Note the error points to the `index.html` file:

Uncaught (in promise) DOMException: The user aborted a request.

## 💁 Possible Solution

Removing the worker/Houdini stopped the error, but obviously that's not ideal ;-) that's just how I know it was the provided code that triggered it (under **Expected behavior**)

## 🔦 Context

My code depends on paint workers in places. It's an experimental app but I was hoping Parcel could help with bundling.

## 💻 Code Sample

```
/* Register paint workers */
if ('paintWorklet' in CSS) {
  CSS.paintWorklet.addModule('js/houdini/image-cross.js');
}
```

(Note that the worklet path _should_ point from the root, not the JS file (`app.js`) in this case. I tried using the `~` syntax, but that didn't help.)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | 9.8.0
| npm/Yarn         | 6.4.1
| Operating System | macOS Sierra

### LINKED ISSUE #4174: Parcel 2: @parcel/transformer-raw problems
# 🐛 bug report
*https://github.com/Banou26/parcel-bug-4174*

When using this configuration as per https://github.com/parcel-bundler/parcel/issues/1080#issuecomment-557240449 and https://github.com/parcel-bundler/parcel/issues/501#issuecomment-557240714
`.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```

The end build isn't transpiled at all, for example in the repro, the `index.html` imports `index.ts` which contains 

```ts
import './foo.ts'

console.log('foo')
```
and the output build Parcel serves is

`/parcel-test.d7ebec59.ts`

```ts
import './foo.ts'

console.log('foo')
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```
`package.json`
```json
{
  "name": "parcel-raw-transform",
  "version": "0.0.1",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "parcel": "^2.0.0-nightly.116"
  },
  "scripts": {
    "dev": "parcel src/index.html"
  }
}
```

I tried with both the `2.0.0-alpha.3.2` and `2.0.0-nightly.116`

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #1093, Fixes #2083, Fixes #4174, Closes #5837, Closes #6510

This adds support for worklets including the `CSS.paintWorklet.addModule` syntax, as well as for audio worklets via the `worklet:` pipeline. The pipeline is needed in that case because the API is not statically analyzable. Worklets are a new environment context. While they are similar to web workers, they have some unique constraints: only ESM is supported (not scripts), but dynamic `import()` is _not_ supported (as with other networking APIs like fetch). Parcel will give you a build time error for this.

This also fixes several other issues that are somewhat related.

* Using the `url:` pipeline with a JavaScript file was broken because the `url:` pipeline did not run other transformers before the raw transformer, meaning the JS wasn't transformed.
* Using `new URL` with a JS file was also broken because the generated JS would never run its entry asset. This was because it was not marked as isolated, and so thought the parent bundle would `parcelRequire` it like with normal async imports. Also, it assumed it had access to the modules in parent bundles, but this wasn't necessarily true. We now mark URL dependencies in JS files as isolated. This required exposing `bundleBehavior` to dependencies like we do for assets.
* Referencing JS files with `bundle-text:` or other pipelines that trigger inline bundles was broken when HMR was enabled. This was because we took the first entry asset rather than the main entry when checking `asset.meta.inlineType`.
* Isolated bundles now affect the parallel request limit properly. Previously all isolated bundles were connected to the root in the graph rather than where they came from. This made some reachability checks easier, but meant that it wasn't possible to have an isolated bundle at a parallel priority, only at a lazy priority.
* Fixes usage of dynamic import with named pipelines. Previously, we ignored these as they appeared like URLs. But importing URLs was also broken and we'll need to find a different solution for that anyway.
* Adds support for dynamically importing a dependency that turns out to be inline (e.g. `import('bundle-text:./foo')`. Previously this was just broken, but now it returns a `Promise.resolve(contents)`.

### CODE REVIEW

File: packages/bundlers/default/src/DefaultBundler.js [hunk 1]
```diff
@@ -109,10 +109,11 @@ export default (new Bundler({
             let bundle = bundleGraph.createBundle({
               entryAsset: asset,
               isEntry:
+                dependency.bundleBehavior === 'inline' ||
                 asset.bundleBehavior === 'inline'
                   ? false
                   : dependency.isEntry || dependency.needsStableName,
-              isInline: asset.bundleBehavior === 'inline',
+              bundleBehavior: dependency.bundleBehavior ?? asset.bundleBehavior,
```
Comment (devongovett) [inline packages/bundlers/default/src/DefaultBundler.js:116]: Which one should win? 😉

File: packages/core/types/index.js [hunk 2]
```diff
@@ -474,6 +477,15 @@ export type DependencyOptions = {|
...
   +priority?: DependencyPriority,
+  /**
+   * Controls the behavior of the bundle the resolved asset is placed into. Use in combination with `priority`
+   * to determine when the bundle is loaded.
+   *   - inline: The resolved asset will be placed into a new inline bundle. Inline bundles are not written
+   *       to a separate file, but embedded into the parent bundle.
+   *   - isolated: The resolved asset will be isolated from its parents in a separate bundle.
+   *       Shared assets will be duplicated.
+   */
+  +bundleBehavior?: BundleBehavior,
```
Comment (devongovett) [inline packages/core/types/index.js:488]: API wise I'm not too sure about this. I considered combining bundleBehavior and priority, but I think it's possible to have an isolated bundle that is either parallel or lazy (but probably not sync), and it's possible to have an inline sync or async (though parallel vs lazy doesn't really matter). 🤔

File: packages/core/types/index.js [hunk 3]
```diff
@@ -1106,8 +1130,7 @@ export interface Bundle {
   +env: Environment;
   /** Whether this is an entry (e.g. should not be hashed). */
   +isEntry: ?boolean;
-  /** Whether this bundle should be inlined into the parent bundle(s), */
-  +isInline: ?boolean;
+  +bundleBehavior: ?BundleBehavior;
```
Comment (devongovett) [inline packages/core/types/index.js]: Is `bundle.bundleBehavior` too redundant? `bundle.behavior`??

File: packages/transformers/js/src/JSTransformer.js [hunk 4]
```diff
@@ -472,22 +483,57 @@ export default (new Transformer({
         }
       } else if (dep.kind === 'URL') {
         asset.addURLDependency(dep.specifier, {
+          bundleBehavior: 'isolated',
           loc: convertLoc(dep.loc),
         });
       } else if (dep.kind === 'File') {
         asset.invalidateOnFileChange(dep.specifier);
       } else {
-        if (dep.kind === 'DynamicImport' && isURL(dep.specifier)) {
```
Comment (devongovett) [inline packages/transformers/js/src/JSTransformer.js:480]: This was broken already because we already replaced the `import()` with a `require()` in rust. The isUrl check was interfering with usage of pipelines in dynamic import.

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.94s | +38.00ms |
| Cached | 459.00ms | +20.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.11s | +103.00ms |
| Cached | 398.00ms | -1.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/302258322580439565)**

File: packages/bundlers/default/src/DefaultBundler.js (hunk 1 above)
Comment (joeyslater) [reply packages/bundlers/default/src/DefaultBundler.js:116]: I would say keep it `bundleBehavior`, it's easier to search since it's all the same feature

Comment (wbinnssmith) [reply packages/bundlers/default/src/DefaultBundler.js:116]: I think @devongovett is asking if the dependency's behavior or asset's behavior should be preferred

**Review by wbinnssmith — APPROVED** [review]

File: packages/bundlers/default/src/DefaultBundler.js (hunk 1 above)
Comment (joeyslater) [reply packages/bundlers/default/src/DefaultBundler.js:116]: ... I must be going crazy, I swore I commented on the comment asking https://github.com/parcel-bundler/parcel/pull/6495#discussion_r655113675

Maybe the 👁️  doctor messed up this morning hah.

In this case, what's more regular case to test against an asset being inline or isolate or a dependency being inline or isolated? And what's the expectation if the dep and asset's bundle behavior were separate.

Comment (devongovett) [reply packages/bundlers/default/src/DefaultBundler.js:116]: yeah I think the dep should win because the importing code might have an expectation about what the asset exposes.
