### PR TITLE
Fork json-comments-rs and remove trailing commas

### LINKED ISSUE #9029: @parcel/resolver-default: Fails to parse tsconfig with trailing commas
# 🐛 bug report

tsconfig can contain trailing commas as well: https://github.com/microsoft/TypeScript/issues/20384#issuecomment-348552936
Currently the resolver throws a parsing error

## 🤔 Expected Behavior

Should accept both comments and trailing commas in tsconfig

## 😯 Current Behavior

```
@parcel/resolver-default: Error parsing JSON

  packages/core/integration-tests/test/integration/jsx-automatic-tsconfig/tsconfig.json:6:1
    5 |   },
  > 6 | }
  >   | ^ trailing comma at line 6 column 1
    7 | 
```

## 💁 Possible Solution

https://github.com/tmccombs/json-comments-rs/issues/10

## 💻 Code Sample

```jsonc
{
  "compilerOptions": {
    "jsxImportSource": "preact",
    // x
  },
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 35548666133d38181deda5fb472fc4ba9a2d33f6

### PR DESCRIPTION
**Pull request by mischnic**
Closes https://github.com/parcel-bundler/parcel/issues/9029

https://github.com/tmccombs/json-comments-rs plus
- https://github.com/tmccombs/json-comments-rs/pull/11
- https://github.com/devongovett/json-comments-rs/compare/strip_in_place...mischnic:json-comments-rs:trailing_comma

<br>

- [x] Integration test for trailing comma tsconfigs
- [ ] (Remove unused parts of that crate)

### CODE REVIEW

File: crates/json-comments-rs/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,546 @@
+//! `json_comments` is a library to strip out comments from JSON-like test. By processing text
```
Comment (devongovett) [inline crates/json-comments-rs/src/lib.rs:1]: new top-level folder? or should we put it in packages? should we move all the crates out of packages?

Comment (mischnic) [reply crates/json-comments-rs/src/lib.rs:1]: The idea being that stuffing all of the crates into `packages/utils` is getting more and more confusing, so I would suggest putting all of the somewhat general purpose crates into `crates` itself (so dev-dep-resolver and node-resolver-rs). But you wanted to move them out of the monorepo anyway 🤷 
Otherwise I can put this into `packages/utils` as well

Comment (devongovett) [reply crates/json-comments-rs/src/lib.rs:1]: Yeah that makes sense.

**Review by devongovett — APPROVED** [review]
We can pull out the unused stuff later.
