### PR TITLE
Fix dev server serving inline bundles

### LINKED ISSUE #6043: Parcel serve: Got unexpected null
# 🐛 bug report

I've been getting this error when running `parcel serve` a couple times today

```
ℹ️ Server running at http://localhost:1234
✨ Built in 3.71s
Error: Got unexpected null
    at nullthrows ([project_dir]node_modules/nullthrows/nullthrows.js:7:15)
    at PackagedBundle.get filePath [as filePath] ([project_dir]node_modules/@parcel/core/lib/public/Bundle.js:367:38)
    at [project_dir]node_modules/@parcel/reporter-dev-server/lib/Server.js:272:104
    at Array.find (<anonymous>)
    at Server.serveBundle ([project_dir]node_modules/@parcel/reporter-dev-server/lib/Server.js:272:45)
    at Server.respond ([project_dir]node_modules/@parcel/reporter-dev-server/lib/Server.js:219:19)
    at [project_dir]node_modules/@parcel/reporter-dev-server/lib/Server.js:440:14
    at call ([project_dir]node_modules/connect/index.js:239:7)
    at next ([project_dir]node_modules/connect/index.js:183:5)
    at Function.handle ([project_dir]node_modules/connect/index.js:186:3) {
  framesToPop: 1
}
npm ERR! code 1
npm ERR! path [project_dir]
npm ERR! command failed
npm ERR! command sh -c ./build_scripts/serve

```

I've tried cleaning the cache and it didn't help. It happens after like the 2nd or 3rd request.

Unfortunately when I tried to actively reproduce it it stopped and has been working since :( I'll update with more info if it happens again.
I have a new laptop so maybe something's not set up correctly.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "scripts": {
    "serve": "dotenv -e .env.development -- parcel serve --port 1234 --target dev --no-cache --no-hmr --dist-dir dev_dist/myscript src/main.ts",
  },
  "targets": {
    "dev": {
      "engines": {
        "browsers": "last 1 firefox version"
      }
    }
  },
  "devDependencies": {
    "@babel/cli": "latest",
    "@babel/core": "latest",
    "@babel/plugin-proposal-class-properties": "latest",
    "@babel/plugin-proposal-private-methods": "latest",
    "@babel/preset-typescript": "latest",
    "@parcel/babel-plugin-transform-runtime": "nightly",
    "@parcel/babel-preset-env": "nightly",
    "@parcel/optimizer-cssnano": "nightly",
    "@parcel/optimizer-htmlnano": "nightly",
    "@parcel/packager-css": "nightly",
    "@parcel/packager-html": "nightly",
    "@parcel/transformer-css": "nightly",
    "@parcel/transformer-html": "nightly",
    "@parcel/transformer-inline-string": "nightly",
    "@parcel/transformer-postcss": "nightly",
    "@parcel/transformer-posthtml": "nightly",
    "parcel": "nightly",
    "segfault-handler": "latest",
    "terser": "latest"
  },
  "dependencies": {
    "@babel/runtime": "latest",
    "@babel/runtime-corejs3": "latest",
    "dotenv-cli": "latest"
  }
}

```

.babelrc:
```
{
  "presets": ["@babel/preset-typescript", "@parcel/babel-preset-env"],
  "plugins": ["@parcel/babel-plugin-transform-runtime"]
}
```

## 🤔 Expected Behavior

Parcel serve should not crash.

## 😯 Current Behavior

It crashes sometimes.

## 💁 Possible Solution

Never crash.

## 🔦 Context

Wanted to continue developing my script and wondered why nothing happened.

## 💻 Code Sample

I'll post one if I manage to reproduce it with something that's not my whole code

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.630+ed726670|
| Node             |v15.12.0|
| npm         |7.6.3|
| Operating System | macOS Catalina 10.15.7 (19H15)|

### PR DESCRIPTION
**Pull request by martinsvoboda**
Fixes #6043. Fix recommended by @mischnic 

Dev server fails when serving inline bundle processed by @parcel/transformer-raw

I would consider this as regression bug, because it worked with parcel@2.0.0-beta.2 and @parcel/transformer-raw@2.0.0-beta.2

## 💻 Examples

package.json
```
{
    "name": "parcel-serve-fails-for-inlines",
    "scripts": {
        "serve": "parcel serve ./src/index.html"
    },
    "devDependencies": {
        "parcel": "2.0.0-nightly.632"
    }
}
```

.parcelrc
```
{
    "extends": "@parcel/config-default",
    "transformers": {
        "*.props": ["@parcel/transformer-raw"]
    },
}
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Test</h1>
    <div data-widget="TextFromImage">
        <script type="text/props">
            {
                "some": "value"
            }
        </script>
    </div>
</body>
</html>
```

## 🚨 Test instructions

I was unable to create the correct unit test. Reproducing the issue:

- Repo https://github.com/martinsvoboda/parcel-serve-fails-for-inlines
- Run `parcel serve ./src/index.html` it is finished successfully
- Open localhost:1234 in browser, serve process fails with following exception

```
parcel serve ./src/index.html

ℹ️ Server running at http://localhost:1234
✨ Built in 230ms
Error: Got unexpected null
    at nullthrows (/Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/nullthrows/nullthrows.js:7:15)
    at PackagedBundle.get filePath [as filePath] (/Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/@parcel/core/lib/public/Bundle.js:367:38)
    at /Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/@parcel/reporter-dev-server/lib/Server.js:272:104
    at Array.find (<anonymous>)
    at Server.serveBundle (/Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/@parcel/reporter-dev-server/lib/Server.js:272:45)
    at Server.respond (/Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/@parcel/reporter-dev-server/lib/Server.js:219:19)
    at /Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/@parcel/reporter-dev-server/lib/Server.js:441:14
    at call (/Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/connect/index.js:239:7)
    at next (/Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/martin.svoboda/workspace/parcel-serve-fails-for-inlines/node_modules/connect/index.js:186:3) {
  framesToPop: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-serve-fails-for-inlines@ serve: `parcel serve ./src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parcel-serve-fails-for-inlines@ serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
The test would look similar to this one

https://github.com/parcel-bundler/parcel/blob/59e6f1c8d364045e75d7291419d3a16395f6f171/packages/core/integration-tests/test/server.js#L61-L85

where a index.html with
```html
<!DOCTYPE html>
<style>
body {
	background: red
}
</style>
```
is requested.
That should also trigger the error

**Comment by martinsvoboda** [comment]
Thank you for the hint. Find the trigger for the error was tricky. Because "Error: Got unexpected null" was raised only when non-existing file was requested. Get default page scenario is actually covered by three tests (each is using integration/html/index.html template):
- should serve a default page if the main bundle is an HTML asset
- should serve a default page if the main bundle is an HTML asset even if it is not called index
- should serve a default page if the main bundle is an HTML asset with package.json#source

So I added inline style to integration/html/index.html and fixed missing inline bundles in other tests which also use this template.

File: packages/reporters/dev-server/src/Server.js [hunk 1]
```diff
@@ -207,6 +207,7 @@ export default class Server {
       let requestedPath = path.normalize(pathname.slice(1));
       let bundle = bundleGraph
         .getBundles()
```
Comment (wbinnssmith) [inline packages/reporters/dev-server/src/Server.js:209]: cc @devongovett and @mischnic we recently discussed changing this method to never return inline bundles

Comment (martinsvoboda) [reply packages/reporters/dev-server/src/Server.js:209]: I tried to filter inline bundles in `getBundles` method, but many tests failed and I didn't figure out how to fix them. This change is definitely out of my knowledge of Parcel. However this bug is blocking my development, so should I finish this pull request as a quick fix, or you change `getBundles` method soon?

Comment (mischnic) [reply packages/reporters/dev-server/src/Server.js:209]: I think we should merge this for now (as there are also various other places where we already do `getBundles().filter(b => !b.isInline)` and change `getBundles` later.

File: packages/core/integration-tests/test/server.js [hunk 2]
```diff
@@ -452,6 +452,11 @@ describe('server', function() {
         name: 'index.html',
         assets: ['index.html'],
       },
+      {
+        name: 'index.HASH_REF_2d285d6f29236f5b00e1db199488d505.css',
```
Comment (mischnic) [inline packages/core/integration-tests/test/server.js]: This hash isn't necessarily stable, it should work correctly even without the `name:` property.

Comment (martinsvoboda) [reply packages/core/integration-tests/test/server.js]: Perfect, I pushed the change. Probably there is a minor bug in assertBundles, because inline bundles have to be specified before index.html otherwise, assertBundles fails.

**Comment by martinsvoboda** [comment]
Tests passed, the fix is ready for merge.

**Review by mischnic — APPROVED** [review]
