### PR TITLE
Correctly set worker's output format if not support by environment

### LINKED ISSUE #6533: `import` tags generated for workers even when not supported by browserslist
# 🐛 bug report

(Works fine in dev mode)

## 🤔 Expected Behavior

Chrome 75 doesn't support module workers, so the worker bundle shouldn't be ESM.

## 😯 Current Behavior

The output contains `new Worker` without `type: module` but the worker bundle has `import "...";` declarations.

## 💻 Code Sample

```html
<script type="module" src="index.js"></script>
```
```js
// index.js
import x from "./lib.js";
console.log(x);
new Worker("./worker.js", { type: "module" });

// worker.js
import x from "./lib.js";
console.log(x);

// lib.js
export default 1235;
```

package.json:
```json
{
	"browserslist": "Chrome 75",
	"@parcel/bundler-default": {
		"minBundleSize": 0
	}
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 413a09364646811f6067be80065c15d7b6270236

### PR DESCRIPTION
**Pull request by mischnic**
@devongovett I hope [`281fde1` (#6534)](https://github.com/parcel-bundler/parcel/pull/6534/commits/281fde1357ab08b1a8dd272643cd8f1a48d017d8) does what you wanted to test? The value of the for loop was never actually used in the test

Closes https://github.com/parcel-bundler/parcel/issues/6533

### CODE REVIEW

File: packages/transformers/js/src/JSTransformer.js [hunk 1]
```diff
@@ -484,15 +484,17 @@ export default (new Transformer({
...
         // Use native ES module output if the worker was created with `type: 'module'` and all targets
-        // support native module workers. Only do this if the source type is changing from script to module
-        // though so that assets can be shared between workers and the main thread in the global output format.
-        let outputFormat = asset.env.outputFormat;
+        // support native module workers. Only do this if parent asset output format is also esmodule so that
+        // assets can be shared between workers and the main thread in the global output format.
+        let outputFormat;
         if (
-          asset.env.sourceType === 'script' &&
+          asset.env.outputFormat === 'esmodule' &&
```
Comment (mischnic) [inline packages/transformers/js/src/JSTransformer.js:491]: I couldn't figure out why the source type has an influence on how assets can be shared. This really only depends on the output format?

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 11.97s | +357.00ms |
| Cached | 526.00ms | +3.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 338.00ms | +18.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.01s | -7.00ms |
| Cached | 445.00ms | +9.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/302979300881072705)**

File: packages/transformers/js/src/JSTransformer.js (hunk 1 above)
Comment (devongovett) [reply packages/transformers/js/src/JSTransformer.js:491]: Yeah I think I probably just typed the wrong one... 😬

**Review by devongovett — APPROVED** [review]
