### PR TITLE
catch css file not found

### LINKED ISSUE #2168: Die after file is not found in css
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`foo.css`
```css
div {
    background: url(utils/dficon.svg); // some non existing file
} 
```

```
parcel foo.css
```

## 🤔 Expected Behavior
Expected error and wait new changes in code

## 😯 Current Behavior
```
⠸ Building dficon.svg...events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '.../dficon.svg'
```
and die

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | 10 
| npm/Yarn         | 8
| Operating System | macos

### PR DESCRIPTION
**Pull request by andrew-anguiano**
# ↪️ Pull Request
This should close #2168. The issue was that `md5.js` was trying to create a hash of a non-existent file and not catching the error. I believe I've fixed it by moving the error listener above the `pipe` and then adding a try/catch in `RawAsset` on `generateHash()`. I'm definitely open to suggestions on how to improve it. This is my first PR for Parcel and I haven't had a _ton_ of experience with Node apps 😉 

## 🚨 Test instructions
1. Create a CSS file that attempts to use a non-existent image (i.e. as a background-image)
2. Build said CSS file

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change **--> might need some pointers on this if necessary**

- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by andrew-anguiano** [comment]
Looks like tests exited with 1 on Windows but passed on all other platforms...?

**Comment by Taym95** [comment]
Only `Windows node_10_x`  weird!

**Comment by andrew-anguiano** [comment]
Looks like it's a corrupt binary? Looking at line 1685 of the console output. 
```
2018-10-27T02:32:15.7060230Z [==================================================] - 1 / 1-- CORRUPT BINARY - D:\a\1\s\packages\core\parcel-bundler\test\integration\elm\elm-stuff\0.19.0\Main.elmo
```

**Comment by DeMoorJasper** [comment]
Restarted the tests hopefully they pass now

**Comment by andrew-anguiano** [comment]
@DeMoorJasper looks like almost every PR has failing tests 😕

File: packages/core/parcel-bundler/src/assets/RawAsset.js [hunk 1]
```diff
@@ -27,7 +27,11 @@ class RawAsset extends Asset {
   }
 
   async generateHash() {
-    return await md5.file(this.name);
+    try {
+      return await md5.file(this.name);
+    } catch (err) {
+      throw new Error(err);
```
Comment (devongovett) [inline packages/core/parcel-bundler/src/assets/RawAsset.js]: Why do we need to catch and re-throw the error here? Isn't that the same as just not catching it in the first place?

File: packages/core/parcel-bundler/src/utils/md5.js [hunk 2]
```diff
@@ -11,11 +11,13 @@ function md5(string, encoding = 'hex') {
 md5.file = function(filename) {
   return new Promise((resolve, reject) => {
     fs.createReadStream(filename)
+      .on('error', function(error) {
+        reject(error);
```
Comment (devongovett) [inline packages/core/parcel-bundler/src/utils/md5.js]: I think you can write this like before by just passing `reject` directly as the callback instead of making a wrapper function

**Comment by andrew-anguiano** [comment]
@devongovett good points on both of your comments. Think I got it cleaned up now. Thanks!
