### PR TITLE
Fix bugs related to watching symlinks

### LINKED ISSUE #998: 🐛No hot module replacement with symlinks
🐛 bug report

I start up Parcel's development server with a command like this:
```
parcel ./public/symlink-index.html
```
I have a symlink at ./public/symlink-index.html which points to an index.html file (in any location). The hot module replacement does not occur when changes are made to the symlinked index.html file. Hot module replacement only occurs when the symlink itself changes.

### 🎛 Configuration (.babelrc, package.json, cli command)
My .babelrc
```js
{
  "plugins": [
    "transform-class-properties"
  ],
  "presets": ["env", "stage-0", "react"]
}
```

### 🤔 Expected Behavior

When a change is made to the symlinked index.html file, hmr should occur.

### 😯 Current Behavior

When a change is made to the symlinked index.html file, no hmr occurs. Dev server must be restarted for changes to take effect.

### 🔦 Context

We are using Bazel to build all of our projects. Bazel runs the parcel binary in a sandbox where it creates symlinks to all of the files in our app. 

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 9.7.1
| npm/Yarn         | 5.6.0
| Operating System | High Sierra

### PR DESCRIPTION
**Pull request by DeMoorJasper**
A cleaned up version of #1326

closes #1326
closes #998

### CODE REVIEW

File: src/Bundler.js [hunk 1]
```diff
@@ -377,24 +378,33 @@ class Bundler extends EventEmitter {
...
     if (!this.watcher) {
       return;
     }
 
-    if (!this.watchedAssets.has(path)) {
-      this.watcher.watch(path);
-      this.watchedAssets.set(path, new Set());
-    }
+    if (await fs.exists(path)) {
+      if ((await fs.lstat(path)).isSymbolicLink()) {
```
Comment (fathyb) [inline src/Bundler.js]: We should probably put `watch` and `unwatch` in a noop `try`/`catch` clause in case an error is thrown (eg. file locked by the anti-virus on Windows) to prevent unhandled promise rejections.

Comment (DeMoorJasper) [reply src/Bundler.js]: Yeah was thinking the same but than thought people would open issues for some failed watches.

Comment (DeMoorJasper) [reply src/Bundler.js]: What about just skipping (await fs.lstat(path)).isSymbolicLink() and just using await fs.realpath(path) instead? As it returns the original path if it's not a symbolic link? Seems to be faster as well

File: src/utils/fs.js [hunk 2]
```diff
@@ -7,7 +7,16 @@ exports.writeFile = promisify(fs.writeFile);
 exports.stat = promisify(fs.stat);
 exports.readdir = promisify(fs.readdir);
 exports.unlink = promisify(fs.unlink);
-exports.realpath = promisify(fs.realpath);
+exports.realpath = async function(path) {
```
Comment (DeMoorJasper) [inline src/utils/fs.js]: Not sure if this is safe as it overwrites a native fs function.

File: src/Bundler.js (hunk 1 above)
Comment (fathyb) [reply src/Bundler.js]: 👍 that's even better!

**Comment by curran** [comment]
CI is failing.
