### PR TITLE
Handle mutations of process.env

### LINKED ISSUE #5493: Broken output for `delete` on an process.env property
# 🐛 bug report

Don't replace `delete process.env.SOMETHING` with `delete undefined;`

## 🤔 Expected Behavior

Remove the whole statement or replace with an empty statement.

## 😯 Current Behavior

`delete undefined;` is invalid in strict mode. This is even verified by terser.

## 💁 Possible Solution

`process.env.*` is inlined here: https://github.com/parcel-bundler/parcel/blob/a4cf3e958ea1136b4829eb93615fba5328213471/packages/transformers/js/src/visitors/process.js#L26

This special case is described by `t.isUnaryExpression(path.parent, {operator: 'delete', argument: node})`.

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #5493. Fixes T-1036.

Mutating process.env properties can't be supported if we still want to statically replace them with their values at build time. In source code this is flagged as an error. In node_modules it is a warning in case the code isn't actually used at runtime. In that case, the behavior won't be as expected but at least it will compile.

In order to do this, the diagnostics in Rust now have a severity property, which can be `Error`, `Warning`, or `SourceError`. `SourceError` means error if `asset.isSource` and warning otherwise.

Also fixed an error message for script tags which had a copy/paste mistake I noticed.

### CODE REVIEW

File: packages/core/integration-tests/test/integration/env-computed/index.js [hunk 1]
```diff
@@ -1,3 +1,2 @@
 let name = "ABC";
-process.env[name] = "abc";
```
Comment (devongovett) [inline packages/core/integration-tests/test/integration/env-computed/index.js:2]: Do we still want to allow mutations with computed properties?? Seems weird to allow that but not static properties.

Comment (mischnic) [reply packages/core/integration-tests/test/integration/env-computed/index.js:2]: It will always be possible to mutate them anyway by assigning `process.env` to a variable and then changing that.

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.75s | -9.00ms |
| Cached | 490.00ms | +1.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.23s | -49.00ms |
| Cached | 409.00ms | -27.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/305669281499054658)**

File: packages/core/integration-tests/test/integration/env-computed/index.js (hunk 1 above)
Comment (devongovett) [reply packages/core/integration-tests/test/integration/env-computed/index.js:2]: Sure, but the process.env object won't have any properties besides the ones added at runtime, so it's not great to rely on that anyway. IMO better to be consistent when it's not assigned to a variable unless there's a really good reason to allow this.

**Review by mischnic — APPROVED** [review]

**Review by DeMoorJasper — APPROVED** [review]
