### PR TITLE
fix build not exiting in dev env

### LINKED ISSUE #1626: The process does not end after the completion of the custom environment variable packaging.
image
The environment variable is configured to define the interface address
```
let baseUrl = 'http://test-xxx.com';

if(process.env.NODE_ENV === 'production') baseUrl = 'http://xxx.com';
```
But after packaging , the process does not end;

Although my environment variable is not production, my command is build, so should end the process.

My project was deployed online through shell scripts, but your process was not closed, and I could not tell if the packaging was finished.

Hope to solve it quickly.

### PR DESCRIPTION
**Pull request by gorangajic**
When NODE_ENV is set to something else instead of `production` build was
not exiting. This bug was introduced in 1b6a93f3efa1d8a4e9e04beda1a5545770e9fb07

Closes #1626

### CODE REVIEW

File: src/cli.js [hunk 1]
```diff
@@ -177,6 +177,7 @@ async function bundle(main, command) {
   const Bundler = require('../');
 
   if (command.name() === 'build') {
+    command.watch = false;
```
Comment (devongovett) [inline src/cli.js]: I think we should set `command.production = true` here actually, which would implicitly disable watching as well. I believe #1600 was meant to keep environment variables as set by the user, not control actual build. That can be done with other command line flags, e.g. if you want to disable minification, use `--no-minify`.

**Comment by mohsen1** [comment]
FYI 
The hang did happen for me when running `parcel build` here: https://github.com/parcel-bundler/parcel/issues/1632
