### PR TITLE
Fixes bug where double slashes isn't parsed as host.

### LINKED ISSUE #577: The js and css cited in the build index.html do not support absolute paths.
I've tried executing the command **parcel index.html - public-url //cdn.test.com/**, but the final result reference is **/cdn.test.com/xxx** and the result I want is **//cdn. test.com/xxx**, would like to ask how to solve this problem?

### PR DESCRIPTION
**Pull request by iifeoluwa**
Fixes #577

### CODE REVIEW

File: src/utils/urlJoin.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ const path = require('path');
  * e.g. from \path\to\res.js to /path/to/res.js.
  */
 module.exports = function(publicURL, assetPath) {
-  const url = URL.parse(publicURL);
+  const url = URL.parse(publicURL, false, true);
```
Comment (brandon93s) [inline src/utils/urlJoin.js]: [Documentation](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost)

- 2nd param is `parseQueryString` which already defaults to false. 
- 3rd param is `slashesDenoteHost` which this changes to `true`
