### PR TITLE
Replace deferred `...$import$...` expressions

### LINKED ISSUE #3983: Importing sideeffect-free asset with reexports in multiple bundles leaves ...$import$...
# 🐛 bug report

Importing an asset with deferred reexports in a package that is marked `sideEffects: false` from multiple bundles (to bailout to using the `...$exports` object) leaves unresolved (and undefined!) `..id..$import$NAME` in the bundle output, e.g.:

```js
// ASSET: lib/lib.js
var $a049402fa143377408c8456dd9afaff9$exports = {};
var $a049402fa143377408c8456dd9afaff9$export$default = 1234;
$a049402fa143377408c8456dd9afaff9$exports.default = $a049402fa143377408c8456dd9afaff9$export$default;
$a049402fa143377408c8456dd9afaff9$exports.other = $a049402fa143377408c8456dd9afaff9$import$other; // the deferred reexport
console.log("index", $a049402fa143377408c8456dd9afaff9$export$default);
```

## 💻 Code Sample

```
.
├── index.js
├── lib
│   ├── lib.js
│   ├── lib2.js
│   └── package.json
└── other.js
```

```js
// index.js
import Foo from "./lib";

console.log("index", Foo);

import("./other.js");

// other.js
import Foo from "./lib"

console.log("other", Foo);
```
```json
// lib/package.json
{
	"main": "lib.js",
	"sideEffects": false
}
```

```js
// lib/lib.js
export default 1234;
export { default as other } from "./lib2.js";

// lib/lib2.js
export default 5678;
```

## 🔦 Context

I think @padmaia or @wbinnssmith were experiencing/investigating this? (I came across this in the ak-editor)

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Closes #3983, see issue for details.

This will add the missing piece for https://github.com/parcel-bundler/parcel/pull/3814 as well 🎉

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>packages/benchmarks/react-hn 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>packages/benchmarks/ak-editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/254353878729884170)**

**Comment by mischnic** [comment]
Mh, there are two ways a such an import expression can be left untouched by the early linking phase: it is deferred (where it should be removed) or it is excluded (where it should be left untouched to be replaced in the `Program.exit` visitor). But that information is lost in the the BundleGraph:

BundleGraph

File: packages/core/core/src/BundleGraph.js [hunk 1]
```diff
@@ -638,6 +638,11 @@ export function removeAssetGroups(
   for (let [, node] of assetGraph.nodes) {
     if (node.type === 'asset_group') {
       assetGroupIds.add(node.id);
+
+      let [depNode] = assetGraph.getNodesConnectedTo(node);
+      if (depNode && depNode.type === 'dependency') {
+        depNode.value.isDeferred = node.deferred;
```
Comment (mischnic) [inline packages/core/core/src/BundleGraph.js]: Is mutating a node's value fine?

File: packages/core/core/src/types.js [hunk 2]
```diff
@@ -57,6 +57,7 @@ export type Dependency = {|
   isOptional: boolean,
   isURL: boolean,
   isWeak: ?boolean,
+  isDeferred: boolean, // TODO, only meaningful in bundlegraph
```
Comment (mischnic) [inline packages/core/core/src/types.js]: Should I create a `BundleGraphDependency(Node)` type, because `isDeferred` isn't meaningful in the AssetGraph (at that point, the connected `AssetGroupNode` has that information.

**Comment by mischnic** [comment]
Ready for review.
In the AssetGraph, `Dependency#isDeferred` and `AssetGroupNode#deferred` are now consistent (I couldn't remove the latter because `AssetGraph#addNode` uses that flag to determine whether to mark that node incomplete).
