### PR TITLE
esm2cjs: var declarations can shadow outside the block

### LINKED ISSUE #5718: firebase.firestore doesn't work from parcel@2.0.0-nightly.485
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "firebase": "8.2.4",
    "parcel": "2.0.0-nightly.485"
  }
}
```

## 🤔 Expected Behavior

`firebase.firestore().collection('foobar')` should be invoked without returning any errors

## 😯 Current Behavior

`firebase.firestore().collection('foobar')` throws error

```
14:50:55.815 Uncaught TypeError: this.segments.slice is not a function
    rt prebuilt.js:1105
    ot prebuilt.js:1129
    toString prebuilt.js:1132
    Rs prebuilt.js:14145
    Hs prebuilt.js:14492
    collection prebuilt.js:17320
    ["5WHjR"]< index.js:6
    newRequire index.77429590.js:69
    <anonymous> index.77429590.js:118
    <anonymous> index.77429590.js:141
prebuilt.js:1105:29
    rt prebuilt.js:1105
    ot prebuilt.js:1129
    toString prebuilt.js:1132
    Rs prebuilt.js:14145
    Hs prebuilt.js:14492
    collection prebuilt.js:17320
    ["5WHjR"]< index.js:6
    newRequire index.77429590.js:69
    <anonymous> index.77429590.js:118
    <anonymous> index.77429590.js:141
```

## 🔦 Context

When using `parcel@2.0.0-nightly.481` (last available prior `485`), the problem doesn't occur.
I was looking into using the latest features of parcel _(.i.e: postcss 8)_ while keep using firebase.

#### index.html
```html
<!doctype html>
<script src="./index.js"></script>
```

#### index.js
```js
import firebase from 'firebase/app';
import 'firebase/firestore';

firebase.initializeApp({projectId: 'foo'});

firebase.firestore().collection('foobar');
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0@nightly.485
| Node             | 15.7.0
| npm/Yarn         | 6.14.11
| Operating System | linux

### PR DESCRIPTION
**Pull request by mischnic**
Closes #5718

Example:
```js
import { f } from "./b.js";
(function () {
	for (var f = [], i = 0; i < 10; i++) { // f is imported and also locally declared inside the loop head
		f[i] = i;
	}

	console.log(f);
})();
```

previously became: 

```js
var _bJs = require("./b.js");
(function () {
  for (var f = [], i = 0; i < 10; i++) {
    f[i] = i;
  }
  console.log(_bJs.f); // !!!
})();
```

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.53s | -84.00ms |
| Cached | 534.00ms | -48.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 553.00ms | +56.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 502.00ms | -120.00ms 🚀 |
| dist/legacy/index.9ff7c523.js | 1.11kb | +0.00b | 553.00ms | +43.00ms ⚠️ |
| dist/modern/index.f81b5b4b.js | 1.11kb | +0.00b | 533.00ms | -97.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 553.00ms | +43.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 533.00ms | -94.00ms 🚀 |
| dist/legacy/index.5859ab37.css | 77.00b | +0.00b | 870.00ms | +49.00ms ⚠️ |
| dist/modern/index.77ce15d4.css | 77.00b | +0.00b | 863.00ms | -65.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 45.00ms | -22.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 63.00ms | +19.00ms ⚠️ |
| dist/legacy/index.9ff7c523.js | 1.11kb | +0.00b | 63.00ms | -4.00ms 🚀 |
| dist/modern/index.f81b5b4b.js | 1.11kb | +0.00b | 63.00ms | -4.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 46.00ms | -24.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 63.00ms | -4.00ms 🚀 |
| dist/legacy/index.5859ab37.css | 77.00b | +0.00b | 45.00ms | -22.00ms 🚀 |
| dist/modern/index.77ce15d4.css | 77.00b | +0.00b | 63.00ms | -4.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 16.96s | -1.12s 🚀 |
| Cached | 7.50s | -150.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 483.35kb | +0.00b | 6.88s | -555.00ms 🚀 |
| dist/PermalinkedComment.1964b8bb.js | 4.20kb | +0.00b | 606.00ms | -53.00ms 🚀 |
| dist/UserProfile.f5fa9f60.js | 1.76kb | +0.00b | 607.00ms | -52.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 421.00ms | -49.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 483.35kb | +0.00b | 70.00ms | +22.00ms ⚠️ |
| dist/PermalinkedComment.1964b8bb.js | 4.20kb | +0.00b | 70.00ms | +22.00ms ⚠️ |
| dist/UserProfile.f5fa9f60.js | 1.76kb | +0.00b | 70.00ms | +22.00ms ⚠️ |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 53.00ms | +5.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.78m | -908.00ms |
| Cached | 2.62s | -32.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/pdfRenderer.b1a86a92.js | 1.11mb | +0.00b | 33.28s | -3.52s 🚀 |
| dist/editorView.94307fd1.js | 587.53kb | +0.00b | 46.24s | -4.34s 🚀 |
| dist/popup.1b0ce924.js | 169.24kb | +0.00b | 17.74s | +2.93s ⚠️ |
| dist/EmojiPickerComponent.b302072e.js | 139.01kb | +0.00b | 9.75s | -509.00ms 🚀 |
| dist/Toolbar.453ced4a.js | 99.77kb | +0.00b | 17.88s | +4.61s ⚠️ |
| dist/media-viewer.b4647ff4.js | 72.87kb | +0.00b | 9.92s | -680.00ms 🚀 |
| dist/card.92b0f4f9.js | 54.02kb | +0.00b | 7.88s | -886.00ms 🚀 |
| dist/card.43bef276.js | 51.77kb | +0.00b | 17.74s | +4.68s ⚠️ |
| dist/DatePicker.64b5aa93.js | 21.20kb | +0.00b | 7.87s | -451.00ms 🚀 |
| dist/smartMediaEditor.ab51c6dd.js | 16.85kb | +0.00b | 17.80s | +3.00s ⚠️ |
| dist/ui.bfd5ec70.js | 14.21kb | +0.00b | 7.59s | -689.00ms 🚀 |
| dist/card.89465567.js | 5.71kb | +0.00b | 8.45s | -689.00ms 🚀 |
| dist/media-viewer.114c1cc8.js | 4.01kb | +0.00b | 9.92s | -637.00ms 🚀 |
| dist/EmojiPickerComponent.5d345edd.js | 3.62kb | +0.00b | 6.15s | -750.00ms 🚀 |
| dist/index.10f02a5e.css | 3.46kb | +0.00b | 33.27s | -26.68s 🚀 |
| dist/Modal.19c70720.js | 3.14kb | +0.00b | 837.00ms | -158.00ms 🚀 |
| dist/clipboard.84ebdbd2.js | 2.97kb | +0.00b | 10.01s | -1.12s 🚀 |
| dist/16.624bbe22.js | 2.49kb | +0.00b | 836.00ms | -159.00ms 🚀 |
| dist/ResourcedEmojiComponent.470ee09d.js | 2.15kb | +0.00b | 7.56s | -673.00ms 🚀 |
| dist/card.4188bb6a.js | 2.15kb | +0.00b | 8.79s | -657.00ms 🚀 |
| dist/feedback.80c8a178.js | 1.86kb | +0.00b | 7.87s | -451.00ms 🚀 |
| dist/16.342e69d2.js | 1.86kb | +0.00b | 3.60s | -194.00ms 🚀 |
| dist/browser.00e50e54.js | 1.82kb | +0.00b | 9.99s | -1.38s 🚀 |
| dist/workerHasher.cbff2c2b.js | 1.75kb | +0.00b | 10.60s | -2.51s 🚀 |
| dist/code.6d1ec8ce.js | 1.61kb | +0.00b | 3.77s | -230.00ms 🚀 |
| dist/16.23a6fba4.js | 1.46kb | +0.00b | 3.83s | +311.00ms ⚠️ |
| dist/16.186663a4.js | 1.45kb | +0.00b | 837.00ms | -158.00ms 🚀 |
| dist/heading5.fe670803.js | 1.40kb | +0.00b | 4.14s | -1.11s 🚀 |
| dist/expand.739e3b88.js | 1.38kb | +0.00b | 7.87s | -451.00ms 🚀 |
| dist/16.263c691c.js | 1.34kb | +0.00b | 836.00ms | -159.00ms 🚀 |
| dist/16.b7512655.js | 1.32kb | +0.00b | 3.60s | -261.00ms 🚀 |
| dist/16.436e2680.js | 1.27kb | +0.00b | 836.00ms | -159.00ms 🚀 |
| dist/16.19a76383.js | 1.26kb | +0.00b | 3.83s | +311.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.3d09fdec.js | 1.23kb | +0.00b | 8.32s | -773.00ms 🚀 |
| dist/16.cd483156.js | 1.18kb | +0.00b | 4.02s | +349.00ms ⚠️ |
| dist/heading1.a939a2da.js | 1.18kb | +0.00b | 5.14s | +1.04s ⚠️ |
| dist/table.4e67906a.js | 1.09kb | +0.00b | 4.38s | +385.00ms ⚠️ |
| dist/panel-success.a2e1eac9.js | 1.05kb | +0.00b | 4.04s | -337.00ms 🚀 |
| dist/media-card-analytics-error-boundary.ef6306e0.js | 999.00b | +0.00b | 7.88s | -934.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.880deb8d.js | 995.00b | +0.00b | 8.76s | -604.00ms 🚀 |
| dist/simpleHasher.b4d19bac.js | 755.00b | +0.00b | 10.60s | -4.19s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.c574a14b.js | 2.46mb | +0.00b | 499.00ms | -29.00ms 🚀 |
| dist/pdfRenderer.b1a86a92.js | 1.11mb | +0.00b | 541.00ms | -34.00ms 🚀 |
| dist/editorView.94307fd1.js | 587.53kb | +0.00b | 558.00ms | -40.00ms 🚀 |
| dist/popup.84cf10de.js | 169.24kb | +0.00b | 554.00ms | -40.00ms 🚀 |
| dist/Toolbar.453ced4a.js | 99.77kb | +0.00b | 558.00ms | -40.00ms 🚀 |
| dist/media-viewer.b4647ff4.js | 72.87kb | +0.00b | 541.00ms | -34.00ms 🚀 |
| dist/card.43bef276.js | 51.77kb | +0.00b | 551.00ms | -38.00ms 🚀 |
| dist/Modal.507a0880.js | 39.18kb | +0.00b | 499.00ms | -29.00ms 🚀 |
| dist/component.e862677c.js | 30.82kb | +0.00b | 426.00ms | -103.00ms 🚀 |
| dist/component.c1c3a8ff.js | 22.54kb | +0.00b | 436.00ms | -43.00ms 🚀 |
| dist/smartMediaEditor.ab51c6dd.js | 16.85kb | +0.00b | 558.00ms | -40.00ms 🚀 |
| dist/js.63570256.js | 16.55kb | +0.00b | 435.00ms | -44.00ms 🚀 |
| dist/dropzone.80bdf184.js | 16.06kb | +0.00b | 551.00ms | -38.00ms 🚀 |
| dist/component.dd6e8cc9.js | 6.20kb | +0.00b | 436.00ms | -44.00ms 🚀 |
| dist/card.89465567.js | 5.71kb | +0.00b | 541.00ms | -34.00ms 🚀 |
| dist/media-viewer.114c1cc8.js | 4.01kb | +0.00b | 541.00ms | -48.00ms 🚀 |
| dist/png-chunks-extract.8c8d635d.js | 3.55kb | +0.00b | 436.00ms | -43.00ms 🚀 |
| dist/index.10f02a5e.css | 3.46kb | +0.00b | 556.00ms | -44.00ms 🚀 |
| dist/dropzone.c3746b5e.js | 3.44kb | +0.00b | 554.00ms | -40.00ms 🚀 |
| dist/Modal.19c70720.js | 3.14kb | +0.00b | 499.00ms | +34.00ms ⚠️ |
| dist/clipboard.84ebdbd2.js | 2.97kb | +0.00b | 551.00ms | -38.00ms 🚀 |
| dist/16.624bbe22.js | 2.49kb | +0.00b | 426.00ms | -38.00ms 🚀 |
| dist/card.4188bb6a.js | 2.15kb | +0.00b | 554.00ms | -40.00ms 🚀 |
| dist/date.57372c70.js | 1.96kb | +0.00b | 468.00ms | -35.00ms 🚀 |
| dist/images.c36248a4.js | 1.90kb | +0.00b | 475.00ms | -32.00ms 🚀 |
| dist/16.342e69d2.js | 1.86kb | +0.00b | 453.00ms | -42.00ms 🚀 |
| dist/browser.00e50e54.js | 1.82kb | +0.00b | 551.00ms | -38.00ms 🚀 |
| dist/16.d173f3df.js | 1.79kb | +0.00b | 444.00ms | -43.00ms 🚀 |
| dist/workerHasher.cbff2c2b.js | 1.75kb | +0.00b | 557.00ms | -41.00ms 🚀 |
| dist/list-number.9bb92c49.js | 1.68kb | +0.00b | 482.00ms | -28.00ms 🚀 |
| dist/code.6d1ec8ce.js | 1.61kb | +0.00b | 468.00ms | -35.00ms 🚀 |
| dist/link.cda9435d.js | 1.53kb | +0.00b | 475.00ms | -32.00ms 🚀 |
| dist/heading3.dede5b4c.js | 1.51kb | +0.00b | 497.00ms | -33.00ms 🚀 |
| dist/16.9e858e4a.js | 1.51kb | +0.00b | 453.00ms | -41.00ms 🚀 |
| dist/16.adfefbb7.js | 1.46kb | +0.00b | 444.00ms | -44.00ms 🚀 |
| dist/16.23a6fba4.js | 1.46kb | +0.00b | 444.00ms | -44.00ms 🚀 |
| dist/emoji.5072e4af.js | 1.45kb | +0.00b | 475.00ms | -31.00ms 🚀 |
| dist/16.186663a4.js | 1.45kb | +0.00b | 426.00ms | -39.00ms 🚀 |
| dist/16.2c3c2005.js | 1.44kb | +0.00b | 461.00ms | -37.00ms 🚀 |
| dist/16.45c1cffe.js | 1.40kb | +0.00b | 461.00ms | -37.00ms 🚀 |
| dist/16.8ff06a1d.js | 1.36kb | +0.00b | 460.00ms | -38.00ms 🚀 |
| dist/16.263c691c.js | 1.34kb | +0.00b | 426.00ms | -38.00ms 🚀 |
| dist/heading2.5c4ee285.js | 1.33kb | +0.00b | 497.00ms | -33.00ms 🚀 |
| dist/16.b7512655.js | 1.32kb | +0.00b | 460.00ms | -38.00ms 🚀 |
| dist/16.262b91f7.js | 1.31kb | +0.00b | 468.00ms | -35.00ms 🚀 |
| dist/mention.76dc783a.js | 1.29kb | +0.00b | 482.00ms | -28.00ms 🚀 |
| dist/heading4.8bbff8c5.js | 1.29kb | +0.00b | 497.00ms | -33.00ms 🚀 |
| dist/Modal.d58fb436.js | 1.28kb | +0.00b | 435.00ms | -44.00ms 🚀 |
| dist/16.436e2680.js | 1.27kb | +0.00b | 426.00ms | -38.00ms 🚀 |
| dist/layout.d9b11ad1.js | 1.27kb | +0.00b | 475.00ms | -32.00ms 🚀 |
| dist/16.eaa9cadb.js | 1.27kb | +0.00b | 453.00ms | -42.00ms 🚀 |
| dist/16.06e8a68f.js | 1.26kb | +0.00b | 444.00ms | -43.00ms 🚀 |
| dist/16.19a76383.js | 1.26kb | +0.00b | 453.00ms | -41.00ms 🚀 |
| dist/16.e5432caf.js | 1.26kb | +0.00b | 453.00ms | -42.00ms 🚀 |
| dist/16.62eaafc3.js | 1.26kb | +0.00b | 444.00ms | -44.00ms 🚀 |
| dist/divider.2e62a51b.js | 1.25kb | +0.00b | 475.00ms | -31.00ms 🚀 |
| dist/component.3edf7abd.js | 1.23kb | +0.00b | 499.00ms | -29.00ms 🚀 |
| dist/action.8161ba48.js | 1.23kb | +0.00b | 468.00ms | -35.00ms 🚀 |
| dist/16.0629cb86.js | 1.23kb | +0.00b | 499.00ms | -29.00ms 🚀 |
| dist/media-card-analytics-error-boundary.3d09fdec.js | 1.23kb | +0.00b | 541.00ms | -34.00ms 🚀 |
| dist/decision.cdcb6e3b.js | 1.21kb | +0.00b | 468.00ms | -35.00ms 🚀 |
| dist/16.cd483156.js | 1.18kb | +0.00b | 461.00ms | -37.00ms 🚀 |
| dist/list.e0e1a7a9.js | 1.18kb | +0.00b | 482.00ms | -28.00ms 🚀 |
| dist/heading1.a939a2da.js | 1.18kb | +0.00b | 497.00ms | -32.00ms 🚀 |
| dist/panel-error.210bc7a0.js | 1.11kb | +0.00b | 482.00ms | -28.00ms 🚀 |
| dist/table.4e67906a.js | 1.09kb | +0.00b | 497.00ms | -32.00ms 🚀 |
| dist/panel-note.8e008c33.js | 1.05kb | +0.00b | 482.00ms | -28.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.a20da0c5.js | 1003.00b | +0.00b | 554.00ms | -44.00ms 🚀 |
| dist/media-card-analytics-error-boundary.889a764d.js | 999.00b | +0.00b | 551.00ms | -47.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.880deb8d.js | 995.00b | +0.00b | 554.00ms | -39.00ms 🚀 |
| dist/simpleHasher.b4d19bac.js | 755.00b | +0.00b | 557.00ms | -41.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 426.00ms | -38.00ms 🚀 |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 12.36s | -314.00ms |
| Cached | 541.00ms | -5.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/288897902534722061)**

**Review by wbinnssmith — APPROVED** [review]

File: packages/utils/babylon-walk/src/scope.js [hunk 1]
```diff
@@ -161,18 +167,16 @@ export let scopeVisitor: Visitors<ScopeState> = {
...
-          scope.addBinding(id, node);
-        }
+        type = node.kind;
+      } else if (isClassDeclaration(node)) {
+        type = 'let';
+      }
+
+      let ids = t.getBindingIdentifiers(node);
+      for (let id in ids) {
+        scope.addBinding(id, node, type);
```
Comment (devongovett) [inline packages/utils/babylon-walk/src/scope.js:179]: I think this is changing the binding from the `VariableDeclarator` to the `VariableDeclaration` node. Was that intentional?

Comment (mischnic) [reply packages/utils/babylon-walk/src/scope.js:179]: No, it wasn't. I missed that `decl` is passed instead of `node`.

But doesn't it make more sense to have 
```diff
 for (let decl of node.declarations) {
-    let ids = t.getBindingIdentifiers(node);
+    let ids = t.getBindingIdentifiers(decl);
     for (let id in ids) {
         scope.addBinding(id, decl);
     }
 }
```

instead? Right now, every declarator is registered for every binding name in the whole declaration.

Comment (devongovett) [reply packages/utils/babylon-walk/src/scope.js:179]: Heh. It may not matter with our current usage then.

Comment (mischnic) [reply packages/utils/babylon-walk/src/scope.js]: Fixed

**Review by devongovett — APPROVED** [review]
