### PR TITLE
Fix for id$exports being undefined

### LINKED ISSUE #8792: $78fb23f46eb09f80$exports is not defined
We run into this problem after we added [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels) to our project. When serving the result from `parcel build` we get the runtime error:

```
    Uncaught ReferenceError: $78fb23f46eb09f80$exports is not defined
    <anonymous> http://0.0.0.0:8000/index.059a8e3e.js:25
```
Disabling scope hoisting (`--no-scope-hoist`) makes it work. Parcel 2.7 works, 2.8.0 does not.

Removing the following line from package.json in chartjs-plugin-datalabels also makes it work:
```
"module": "dist/chartjs-plugin-datalabels.esm.js",
```
not sure if it's relevant.

A minimal example for reproducing the error: https://ommej.se/files/tmp/parcel-6711.tar.gz.
Steps to reproduce:
`$ npm install`
`$ npm run build`
`$ cd dist`
`$ python3 -m http.server` (or some other way to serve the files)
visit the page in a browser, for example localhost:8000, the console will show the exception

_Originally posted by @lanker in https://github.com/parcel-bundler/parcel/issues/6711#issuecomment-1403472548_

### PR DESCRIPTION
**Pull request by thebriando**
# ↪️ Pull Request

Fixes #8792 where doing an `import * as` from a library with `export *` in some cases would result in a `id$exports` being undefined

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.02s | +51.00ms |
| Cached | 356.00ms | +27.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.ff03421b.js | 1.48kb | +0.00b | 549.00ms | +45.00ms ⚠️ |
| dist/legacy/index.e9bb1616.js | 1.06kb | +0.00b | 548.00ms | +44.00ms ⚠️ |
| dist/modern/index.4a29d309.js | 921.00b | +0.00b | 548.00ms | +44.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 333.00ms | -21.00ms 🚀 |
| dist/legacy/index.html | 826.00b | +0.00b | 530.00ms | -31.00ms 🚀 |
| dist/modern/index.html | 749.00b | +0.00b | 529.00ms | -31.00ms 🚀 |
| dist/legacy/index.b8ae99ba.css | 94.00b | +0.00b | 345.00ms | -21.00ms 🚀 |
| dist/modern/index.31cedca9.css | 94.00b | +0.00b | 344.00ms | -21.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 5.49s | +349.00ms ⚠️ |
| Cached | 572.00ms | +96.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 459.11kb | +0.00b | 1.41s | +126.00ms ⚠️ |
| dist/PermalinkedComment.e9dc4a75.js | 3.92kb | +0.00b | 470.00ms | +24.00ms ⚠️ |
| dist/UserProfile.8945a243.js | 1.38kb | +0.00b | 470.00ms | +24.00ms ⚠️ |
| dist/NotFound.8b44a81d.js | 269.00b | +0.00b | 470.00ms | +25.00ms ⚠️ |
| dist/logo.8dd07848.png | 244.00b | +0.00b | 339.00ms | +21.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 459.11kb | +0.00b | 1.42s | +146.00ms ⚠️ |
| dist/PermalinkedComment.e9dc4a75.js | 3.92kb | +0.00b | 524.00ms | +28.00ms ⚠️ |
| dist/UserProfile.8945a243.js | 1.38kb | +0.00b | 524.00ms | +29.00ms ⚠️ |
| dist/NotFound.8b44a81d.js | 269.00b | +0.00b | 523.00ms | +27.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 49.87s | +676.00ms |
| Cached | 2.91s | -71.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.7ba584cd.js | 3.78mb | +28.00b ⚠️ | 23.87s | -78.00ms |
| dist/refractor.3e0cc31b.js | 598.96kb | +0.00b | 17.32s | +962.00ms ⚠️ |
| dist/media-viewer.e993d1a1.js | 536.13kb | +0.00b | 17.32s | +965.00ms ⚠️ |
| dist/popup.a77286c1.js | 321.45kb | +11.00b ⚠️ | 17.32s | +963.00ms ⚠️ |
| dist/ConfigPanelFieldsLoader.182d39bc.js | 303.43kb | +0.00b | 12.42s | +1.03s ⚠️ |
| dist/EmojiPickerComponent.1e4c5464.js | 188.61kb | +0.00b | 17.32s | +954.00ms ⚠️ |
| dist/card.d06de810.js | 138.91kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/ConfigPanelFieldsLoader.3b50a158.js | 82.73kb | +0.00b | 17.32s | +954.00ms ⚠️ |
| dist/mobile-upload.63ab2b72.js | 66.34kb | +0.00b | 7.55s | +496.00ms ⚠️ |
| dist/esm.34897092.js | 62.95kb | +11.00b ⚠️ | 17.32s | +963.00ms ⚠️ |
| dist/ElementBrowser.e8f01080.js | 61.94kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/archive.c374f622.js | 59.90kb | +0.00b | 12.41s | -3.95s 🚀 |
| dist/esm.271a6e34.js | 59.30kb | +11.00b ⚠️ | 12.42s | +1.04s ⚠️ |
| dist/component-lazy.51d1dec9.js | 58.94kb | -15.00b 🚀 | 8.00s | +528.00ms ⚠️ |
| dist/component.ea8ea9a2.js | 57.16kb | +0.00b | 7.53s | +484.00ms ⚠️ |
| dist/DatePicker.042aeb21.js | 47.46kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/esm.cb0d3833.js | 39.11kb | +11.00b ⚠️ | 17.32s | +961.00ms ⚠️ |
| dist/Modal.fa93d531.js | 27.83kb | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/DatePicker.e51a79b1.js | 24.96kb | +0.00b | 8.97s | +619.00ms ⚠️ |
| dist/smartMediaEditor.efa59853.js | 21.68kb | +0.00b | 17.32s | +963.00ms ⚠️ |
| dist/esm.fedda0d0.js | 20.43kb | +0.00b | 17.32s | +963.00ms ⚠️ |
| dist/component.f7f8c338.js | 18.68kb | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/js.e1035d4d.js | 17.15kb | +0.00b | 7.53s | +486.00ms ⚠️ |
| dist/ConfigPanelFieldsLoader.3384e28b.js | 15.74kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/ui.8c117104.js | 14.48kb | +0.00b | 12.41s | +1.04s ⚠️ |
| dist/ConfigPanelFieldsLoader.aa7dd375.js | 13.63kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/dropzone.464b3150.js | 13.40kb | +0.00b | 17.32s | +962.00ms ⚠️ |
| dist/pdfRenderer.a0700f46.js | 11.90kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/dropzone.1c15cdc1.js | 11.48kb | +0.00b | 17.32s | +962.00ms ⚠️ |
| dist/Toolbar.4d256e97.js | 9.36kb | +0.00b | 17.32s | +963.00ms ⚠️ |
| dist/clipboard.400013a2.js | 7.92kb | +0.00b | 17.32s | +963.00ms ⚠️ |
| dist/mobile-upload.3747b689.js | 7.79kb | +0.00b | 7.52s | +481.00ms ⚠️ |
| dist/mobile-upload.3baad8e4.js | 7.79kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/mobile-upload.7a892a37.js | 7.79kb | +0.00b | 12.42s | +1.03s ⚠️ |
| dist/mobile-upload.2102debb.js | 7.79kb | +0.00b | 17.32s | +963.00ms ⚠️ |
| dist/browser.0009c8b4.js | 7.19kb | +0.00b | 17.32s | +962.00ms ⚠️ |
| dist/Modal.850345b4.js | 3.86kb | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/component.360dba95.js | 3.20kb | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.60bdaa4c.js | 3.18kb | +0.00b | 17.32s | +964.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.c493f011.js | 3.18kb | +0.00b | 17.32s | +962.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.74e0c7f9.js | 3.18kb | +0.00b | 17.32s | +964.00ms ⚠️ |
| dist/png-chunks-extract.92497b2d.js | 3.06kb | +0.00b | 7.52s | +479.00ms ⚠️ |
| dist/ru.0cf3f40e.js | 2.81kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/uk.282f23b1.js | 2.76kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/codeViewerRenderer.51140ec8.js | 2.61kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/th.137e1013.js | 2.60kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/ResourcedEmojiComponent.9a253c26.js | 2.47kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/pl.bce591be.js | 2.25kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/cs.bf42283b.js | 2.23kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/de.90d5c4fa.js | 2.17kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/fr.ff5d335f.js | 2.13kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/es.80bf0476.js | 2.12kb | +0.00b | 8.97s | +619.00ms ⚠️ |
| dist/hu.223c2cde.js | 2.10kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/fi.98bb8fa8.js | 2.09kb | +0.00b | 8.97s | +619.00ms ⚠️ |
| dist/ja.7d4156df.js | 2.09kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/vi.b46097db.js | 2.09kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/pt_BR.b9e37d37.js | 2.06kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/tr.c85d90a9.js | 2.03kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/ko.9c6bf469.js | 1.98kb | +0.00b | 8.97s | +619.00ms ⚠️ |
| dist/sv.1c06c95c.js | 1.98kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/it.04edb54a.js | 1.97kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/nb.9bd6db78.js | 1.96kb | +0.00b | 8.97s | +619.00ms ⚠️ |
| dist/date.139a08b0.js | 1.95kb | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/da.d2d8303e.js | 1.95kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/nl.c4d12122.js | 1.94kb | +0.00b | 8.97s | +619.00ms ⚠️ |
| dist/images.774ef3be.js | 1.90kb | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/zh_TW.b7c55aa6.js | 1.86kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/zh.b01fe721.js | 1.84kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/feedback.4b745631.js | 1.76kb | +0.00b | 8.97s | +615.00ms ⚠️ |
| dist/status.20808f9b.js | 1.67kb | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/code.3ce450f8.js | 1.56kb | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/workerHasher.4f6584da.js | 1.56kb | +0.00b | 7.52s | +481.00ms ⚠️ |
| dist/workerHasher.540c9790.js | 1.56kb | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/workerHasher.c840c607.js | 1.56kb | +0.00b | 12.42s | +1.03s ⚠️ |
| dist/workerHasher.730f3766.js | 1.56kb | +0.00b | 17.32s | +963.00ms ⚠️ |
| dist/workerHasher.9b1fcdbf.js | 1.56kb | +0.00b | 17.32s | +961.00ms ⚠️ |
| dist/workerHasher.02b63a21.js | 1.56kb | +0.00b | 17.32s | +962.00ms ⚠️ |
| dist/list-number.fdc97a50.js | 1.47kb | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/heading6.e6e03f52.js | 1.36kb | +0.00b | 8.97s | +615.00ms ⚠️ |
| dist/16.4998f52b.js | 1.35kb | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/heading3.73972e33.js | 1.35kb | +0.00b | 8.00s | +530.00ms ⚠️ |
| dist/16.330880f6.js | 1.29kb | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/link.71e06c5e.js | 1.28kb | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/emoji.8f9f45dc.js | 1.25kb | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/heading5.d2f94d9d.js | 1.23kb | +0.00b | 8.97s | +615.00ms ⚠️ |
| dist/expand.c983e90a.js | 1.18kb | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/heading2.c27d912d.js | 1.17kb | +0.00b | 8.00s | +530.00ms ⚠️ |
| dist/heading4.be08fc9e.js | 1.12kb | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/mention.f4723418.js | 1.09kb | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/layout.b5e3a7ef.js | 1.05kb | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/divider.7bb33712.js | 1.04kb | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/action.c407ac14.js | 1.02kb | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/heading1.d7caae19.js | 1.02kb | +0.00b | 8.00s | +530.00ms ⚠️ |
| dist/16.371e251f.js | 1.00kb | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/list.bd698aa0.js | 1011.00b | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/quote.d6bda47a.js | 1011.00b | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/decision.a17a0d00.js | 992.00b | +0.00b | 8.00s | +528.00ms ⚠️ |
| dist/16.8adad466.js | 980.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.71432140.js | 980.00b | +0.00b | 7.53s | +484.00ms ⚠️ |
| dist/panel-warning.772e8569.js | 968.00b | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/16.e5f05248.js | 960.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.549c63e3.js | 955.00b | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/table.e0e68580.js | 946.00b | +0.00b | 8.00s | +530.00ms ⚠️ |
| dist/16.79864de1.js | 920.00b | +0.00b | 7.55s | +495.00ms ⚠️ |
| dist/panel.45c00b08.js | 887.00b | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/panel-error.bfda44fb.js | 864.00b | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/16.7d7d7930.js | 862.00b | +0.00b | 7.53s | +478.00ms ⚠️ |
| dist/16.4556c00f.js | 834.00b | +0.00b | 7.53s | +478.00ms ⚠️ |
| dist/16.a44bb474.js | 827.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.bf9fb66d.js | 821.00b | +0.00b | 8.00s | +530.00ms ⚠️ |
| dist/panel-success.4afcba7a.js | 805.00b | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/panel-note.58ef2b52.js | 795.00b | +0.00b | 8.00s | +530.00ms ⚠️ |
| dist/16.dffb58fe.js | 782.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.0118b1f8.js | 776.00b | +0.00b | 7.53s | +484.00ms ⚠️ |
| dist/16.9a311f76.js | 776.00b | +0.00b | 7.53s | +484.00ms ⚠️ |
| dist/16.edf70d70.js | 775.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.4af9f37f.js | 774.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.aa70dcce.js | 773.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.c715b7e1.js | 746.00b | +0.00b | 8.00s | +529.00ms ⚠️ |
| dist/16.54ffa2b2.js | 725.00b | +0.00b | 7.53s | +485.00ms ⚠️ |
| dist/16.d7c3881b.js | 697.00b | +0.00b | 7.55s | +495.00ms ⚠️ |
| dist/sk.4be9c93f.js | 656.00b | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/pt_PT.e211e609.js | 635.00b | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/et.88ef7cb4.js | 633.00b | +0.00b | 8.97s | +619.00ms ⚠️ |
| dist/simpleHasher.09765db3.js | 589.00b | +0.00b | 7.52s | +481.00ms ⚠️ |
| dist/simpleHasher.c14e20b4.js | 589.00b | +0.00b | 12.41s | +1.03s ⚠️ |
| dist/simpleHasher.23db7a52.js | 589.00b | +0.00b | 12.42s | +1.03s ⚠️ |
| dist/simpleHasher.eefc98b4.js | 589.00b | +0.00b | 17.32s | +963.00ms ⚠️ |
| dist/simpleHasher.47b9c809.js | 589.00b | +0.00b | 17.32s | +961.00ms ⚠️ |
| dist/simpleHasher.cadc19c6.js | 589.00b | +0.00b | 17.32s | +962.00ms ⚠️ |
| dist/is.5f045a22.js | 495.00b | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/ro.8d5b380a.js | 482.00b | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/en_GB.4c40e6c6.js | 472.00b | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/en.e1d21f6d.js | 469.00b | +0.00b | 8.97s | +618.00ms ⚠️ |
| dist/index.html | 248.00b | +0.00b | 8.99s | -7.67s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.7ba584cd.js | 3.78mb | +28.00b ⚠️ | 22.78s | -544.00ms |
| dist/popup.a77286c1.js | 321.45kb | +11.00b ⚠️ | 16.05s | -154.00ms |
| dist/esm.34897092.js | 62.95kb | +11.00b ⚠️ | 16.05s | -154.00ms |
| dist/esm.271a6e34.js | 59.30kb | +11.00b ⚠️ | 11.22s | -204.00ms |
| dist/component-lazy.51d1dec9.js | 58.94kb | -15.00b 🚀 | 8.42s | -197.00ms |
| dist/esm.cb0d3833.js | 39.11kb | +11.00b ⚠️ | 16.05s | -154.00ms |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 4.05s | +71.00ms |
| Cached | 398.00ms | -14.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/379403475731087941)**

File: packages/core/core/src/BundleGraph.js [hunk 1]
```diff
@@ -282,6 +299,34 @@ export default class BundleGraph {
...
+                  invariant(isReexportAll);
+                  let local = `${node.value.id}$rewrite$${asset}$${from}`;
+                  symbols.set(from, {
+                    isWeak: true,
+                    local,
+                    loc: reexportAllLoc,
+                  });
+                  // It might already exist with multiple export-alls causing ambiguous resolution
+                  if (sourceAssetSymbols && !sourceAssetSymbols.has(as)) {
+                    sourceAssetSymbols.set(as, {
```
Comment (mischnic) [inline packages/core/core/src/BundleGraph.js]: Why does this change the symbols of some asset in the asset graph, as opposed to the new `symbols` map?

Comment (thebriando) [reply packages/core/core/src/BundleGraph.js]: So the symbols map is for the current asset, but we need to set the symbols for the source asset using the node id from the current node in the loop. Not sure if there's a better way to do this though

Comment (mischnic) [reply packages/core/core/src/BundleGraph.js]: I think a big problem is that this actually mutates the asset graph, so running `BundleGraph.fromAssetGraph` multiple times isn't safe (which would happen in watch mode).

So at least it should be something like this: https://github.com/parcel-bundler/parcel/commit/908467af6149a89f27cc925390160dc0ec1bd37e
(Not sure how much the added `new Map(...)` affects performance.)

Comment (thebriando) [reply packages/core/core/src/BundleGraph.js]: Isn't this still mutating the asset graph? https://github.com/parcel-bundler/parcel/commit/908467af6149a89f27cc925390160dc0ec1bd37e#diff-b2e31de6fe476821294b35d7fb17106cf1fc48b37ebe5800448dcb3608348b6cR306-R315

Comment (mischnic) [reply packages/core/core/src/BundleGraph.js]: That does (pseudocode):
```js
      let sourceAssetId = translateAssetGraphToBundleGraphNodeId(node.value.sourceAssetId);
      let sourceAsset = bundeGraph.getNode(sourceAssetId)) // a node in the bundle graph
      let sourceAssetSymbols = sourceAsset.value.symbols;
      sourceAssetSymbols.set(...)
```

And then [this](https://github.com/parcel-bundler/parcel/commit/908467af6149a89f27cc925390160dc0ec1bd37e#diff-b2e31de6fe476821294b35d7fb17106cf1fc48b37ebe5800448dcb3608348b6cR367) makes sure that the node is copied before adding to the bundle graph, otherwise the `sourceAssetSymbols.set` would still mutate the asset graph. (As I've said, I hope that copying doesn't affect performance)

Comment (thebriando) [reply packages/core/core/src/BundleGraph.js]: I see, lgtm then. I didn't see any noticeable perf regressions on our large projects

**Review by AGawrys — APPROVED** [review]
