### PR TITLE
Prevent nameclashes with internal variables

### LINKED ISSUE #1699: Tree shaking and React
# 🐛 bug report

I am experiencing a faulty behavior when generating a production bundle using the experimental tree shaking feature.

[I have already logged this in the Spectrum channel](https://spectrum.chat/?t=811287bb-429b-4843-9f37-40c576a1e0d6) but decided to open a proper bug report as well.

## 🎛 Configuration (.babelrc, package.json, cli command)

I put together a repository so you can reproduce the same behavior I am experiencing: https://github.com/rafaelrinaldi/parcel-tree-shaking-jsx-error

## 🤔 Expected Behavior

Tree shaking should work just fine.

## 😯 Current Behavior

Tree shaking kinda works but seems to bypass React, logging "React is not defined" in the console.

## 💁 Possible Solution

I believe that this could be two of the following:

1. "React" is imported whenever JSX is used but not necessarily is being referenced, so the tree shaking might be skipping it for that reason (even though the `babel-plugin-transform-react-jsx` plugin added by the `babel-preset-react` should be replacing JSX nodes by `React.createElement()` calls, therefore notifying the tree shaking algorithm that the module is being used)
2. It might be an module load ordering/evaluation issue in Parcel. Perhaps even solved by #1694 

## 🔦 Context

I'm trying to get the experimental tree shaking feature to work in a project that uses a route-based code splitting strategy using react router and react loadable.

## 💻 Code Sample

I put together a repository so you can reproduce the same behavior I am experiencing: https://github.com/rafaelrinaldi/parcel-tree-shaking-jsx-error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4 |
| Node             | v10.6.0 |
| npm         | 6.1.0 |
| Operating System | macOS High Sierra |

### PR DESCRIPTION
**Pull request by fathyb**
Fixes #1699

Found in [`core-js` code](https://cdn.jsdelivr.net/npm/core-js/modules/_wks.js) 
```js
var $exports = module.exports = function (name) {
  return store[name] || (store[name] =
    USE_SYMBOL && Symbol[name] || (USE_SYMBOL ? Symbol : uid)('Symbol.' + name));
};

$exports.store = store;
```

### CODE REVIEW

File: src/scope-hoisting/hoist.js [hunk 1]
```diff
@@ -121,7 +121,7 @@ module.exports = {
         // Rename each binding in the top-level scope to something unique.
         for (let name in scope.bindings) {
           if (!name.startsWith('$' + t.toIdentifier(asset.id))) {
-            let newName = getName(asset, 'var', name);
+            let newName = getName(asset, 'var', name, '$');
```
Comment (devongovett) [inline src/scope-hoisting/hoist.js]: I don't think this should clash with anything. This would generate e.g. `$id$var$exports` vs our internal which is just `$id$exports`. Seems like the problem might be something else though I'm not sure why this would fix it...

**Comment by devongovett** [comment]
Turns out the regex matching exports variables was wrong. Fixed it.
