### PR TITLE
Let terser eliminate transpiled classes

### LINKED ISSUE #3322: .terserrc does not work in conjunction with `--experimental-scope-hoisting`
# 🐛 bug report

I have a .terserrc file in my project to keep license comments around
```Javascript
{
  "output": {
    "comments": "/license/"
  }
}
```

This works as intended when I don't have `--experimental-scope-hoisting` enabled. When it's enabled the comments are stripped. Monitoring the `outputCode` for each file during compilation, I can see the correct output but each file seems to go through multiple compilation steps, one of which removes the comments.

## 🎛 Configuration (.babelrc, package.json, cli command)

cli command `node_modules/parcel/bin/cli.js build resources/web/docs_js/index.js -d out/ -o docs.js --no-source-maps --experimental-scope-hoisting`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12
| Node             | 10

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

A statement like this doesn't get tree shaken because it does look pure (without looking at the comment).
```js
var $fa7e8a5a8249ace53223ae89975fffbd$export$default =
/*#__PURE__*/
function () {
  function XYZ() {
    $fa7e8a5a8249ace53223ae89975fffbd$var$_classCallCheck(this, XYZ);
  }

  $fa7e8a5a8249ace53223ae89975fffbd$var$_createClass(XYZ, [{
    key: "method",
    value: function method() {
      return "abc";
    }
  }]);
  return XYZ;
}();
```

By outputting comments when generating the code after scopehoisting (and before terser), we can leverage terser to remove everything.

This also makes it possible to allow certain comments to be preserved by terser (e.g. license headers): fixes #3322

---

We could a handle these comments in `treeShake`, but I'm not sure if there is an advantage to doing that?
`+` Smaller cache size, less data to serialize (both to cache and AST->code)
`-` larger error surface, would need more tests

```diff
diff --git a/packages/shared/scope-hoisting/src/shake.js b/packages/shared/scope-hoisting/src/shake.js
index c3b3d09a..7a87f25d 100644
--- a/packages/shared/scope-hoisting/src/shake.js
+++ b/packages/shared/scope-hoisting/src/shake.js
@@ -67,7 +67,9 @@ function isPure(binding) {
       init.isPure() ||
       init.isIdentifier() ||
       init.isThisExpression() ||
-      binding.path.node.id.name === '$parcel$global'
+      binding.path.node.id.name === '$parcel$global' ||
+      (init.isCallExpression() &&
+        init.node.leadingComments.filter(v => v.value === '#__PURE__'))
     );
   }

```
(it might be more complicated than that: https://github.com/rollup/rollup/pull/2429)

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.28s | -427.00ms |
| Cached | 8.20s | +283.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 172.00ms | -39.00ms 🚀 |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 171.00ms | -39.00ms 🚀 |
| dist/modern/index.js | 794.00b | +0.00b | 462.00ms | -24.00ms 🚀 |
| dist/legacy/index.js | 252.00b | +0.00b | 457.00ms | -32.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 12.00ms | -1.00ms 🚀 |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 10.00ms | -2.00ms 🚀 |
| dist/legacy/index.js | 252.00b | +0.00b | 23.00ms | -3.00ms 🚀 |
| dist/legacy/index.css | 29.00b | +0.00b | 10.00ms | -2.00ms 🚀 |
| dist/modern/index.css | 29.00b | +0.00b | 10.00ms | -1.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/react-hn</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 14.71s | -90.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/245479216786702862)**

File: packages/shared/scope-hoisting/src/generate.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ export function generate(
 ) {
   let {code} = babelGenerate(ast, {
     minified: options.minify,
```
Comment (wbinnssmith) [inline packages/shared/scope-hoisting/src/generate.js]: @mischnic what does this tell babel to do? Should it also just be left to terser?

Comment (mischnic) [reply packages/shared/scope-hoisting/src/generate.js]: AFAICT, it only compresses whitespaces:

```js
var generate = require("@babel/generator").default
var parse = require("@babel/parser").parse

const AST = parse(`const ABCDEF = "hel" + "lo";`);
console.log(generate(AST, {minified: true}).code);
// const ABCDEF="hel"+"lo";
```
