### PR TITLE
Serve non index.html files if it's the only html entrypoint

### LINKED ISSUE #5752: Parcel 2 improperly serves entry files named other than index.html
# 🐛 bug report

Parcel 2 improperly serves entry files named other than index.html.
If I run cli with `parcel src/entry/popup/popup.html --open`
Shows 404 Not found instead of åctual html.

If I rename popup.html to index.html and then run cli with `parcel src/entry/popup/index.html --open` - all is good.
## 🎛 Configuration (.babelrc, package.json, cli command)

```js
.babelrc - I dont have
.parcelrc:
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}

```

## 🤔 Expected Behavior
Should accept any entry file name

## 😯 Current Behavior
See bug description.

## 🔦 Context
Just building a simple html.

## 💻 Code Sample
src/entry/popup/popup.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <div id="ExtnPopup">This is the popup UI</div>

    <script src="./popup.ts"></script>
  </body>
</html>
```
src/entry/popup/popup.ts
```
// empty
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.0.0-nightly.562
| Parcel           |   ^2.0.0-beta.1

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

This PR changes the serving logic to serve the index file if there's multiple html entrypoints and serve the html entrypoint if there's only one.

Closes #5752

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.14s | -65.00ms |
| Cached | 602.00ms | -26.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 562.00ms | -71.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 718.00ms | +85.00ms ⚠️ |
| dist/legacy/index.33d06174.js | 1.11kb | +0.00b | 606.00ms | -58.00ms 🚀 |
| dist/modern/index.9e1f1458.js | 1.11kb | +0.00b | 726.00ms | +63.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 722.00ms | +59.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 57.00ms | -3.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 82.00ms | -8.00ms 🚀 |
| dist/legacy/index.33d06174.js | 1.11kb | +0.00b | 83.00ms | -8.00ms 🚀 |
| dist/modern/index.9e1f1458.js | 1.11kb | +0.00b | 83.00ms | -7.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 60.00ms | -4.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 83.00ms | -7.00ms 🚀 |
| dist/legacy/index.44edca46.css | 77.00b | +0.00b | 58.00ms | -3.00ms 🚀 |
| dist/modern/index.0bc656bc.css | 77.00b | +0.00b | 83.00ms | -7.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 21.19s | +372.00ms |
| Cached | 9.39s | +96.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/NotFound.d769112d.js | 530.00b | +0.00b | 256.00ms | +38.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 483.35kb | +0.00b | 50.00ms | -9.00ms 🚀 |
| dist/PermalinkedComment.77f121c4.js | 4.20kb | +0.00b | 50.00ms | -9.00ms 🚀 |
| dist/UserProfile.125b5ebe.js | 1.76kb | +0.00b | 50.00ms | -9.00ms 🚀 |
| dist/NotFound.d769112d.js | 530.00b | +0.00b | 42.00ms | -17.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 49.00ms | -10.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.07m | -25.35s 🚀 |
| Cached | 2.89s | -181.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.d51fa13e.js | 2.46mb | +0.00b | 1.14m | -12.47s 🚀 |
| dist/pdfRenderer.ded75111.js | 1.11mb | +0.00b | 42.26s | -38.15s 🚀 |
| dist/editorView.2ca486fc.js | 587.53kb | +0.00b | 56.34s | -37.19s 🚀 |
| dist/EmojiPickerComponent.90b741d3.js | 139.01kb | +0.00b | 10.86s | -2.71s 🚀 |
| dist/Toolbar.57f2e74b.js | 99.69kb | +0.00b | 17.62s | -1.71s 🚀 |
| dist/media-viewer.d1cb7a32.js | 72.87kb | +0.00b | 13.81s | -2.04s 🚀 |
| dist/card.ecae978d.js | 54.02kb | +0.00b | 12.14s | +1.31s ⚠️ |
| dist/card.86f6e816.js | 51.77kb | +0.00b | 17.51s | +1.42s ⚠️ |
| dist/component.fa4e42d1.js | 30.82kb | +0.00b | 2.37s | -1.76s 🚀 |
| dist/esm.6bc5d42c.js | 27.67kb | +0.00b | 8.71s | -4.57s 🚀 |
| dist/component.63b8a376.js | 22.54kb | +0.00b | 4.53s | -558.00ms 🚀 |
| dist/DatePicker.cbcf2d18.js | 21.20kb | +0.00b | 10.19s | +1.95s ⚠️ |
| dist/smartMediaEditor.70ca3661.js | 16.85kb | +0.00b | 18.52s | +1.09s ⚠️ |
| dist/js.4b5d27df.js | 16.55kb | +0.00b | 4.53s | -554.00ms 🚀 |
| dist/dropzone.a58778e7.js | 16.06kb | +0.00b | 13.96s | -3.98s 🚀 |
| dist/ui.bda48e80.js | 14.21kb | +0.00b | 11.98s | +1.65s ⚠️ |
| dist/workerHasher.09e24457.js | 11.90kb | +0.00b | 8.71s | -4.53s 🚀 |
| dist/card.1a9729d8.js | 5.71kb | +0.00b | 13.19s | -1.01s 🚀 |
| dist/EmojiPickerComponent.ca69a3c9.js | 3.62kb | +0.00b | 8.71s | -1.50s 🚀 |
| dist/png-chunks-extract.e6351d92.js | 3.55kb | +0.00b | 4.53s | -554.00ms 🚀 |
| dist/index.ece3a13e.css | 3.46kb | +0.00b | 42.26s | -38.31s 🚀 |
| dist/Modal.00beb515.js | 3.14kb | +0.00b | 4.68s | +3.32s ⚠️ |
| dist/clipboard.1be7d5c2.js | 2.97kb | +0.00b | 14.59s | -3.35s 🚀 |
| dist/16.cf92dee6.js | 2.49kb | +0.00b | 2.35s | +994.00ms ⚠️ |
| dist/ResourcedEmojiComponent.0df891ba.js | 2.15kb | +0.00b | 11.98s | +1.65s ⚠️ |
| dist/date.f35453a2.js | 1.96kb | +0.00b | 5.80s | +329.00ms ⚠️ |
| dist/images.861d8ede.js | 1.90kb | +0.00b | 5.28s | -303.00ms 🚀 |
| dist/feedback.ddd45d32.js | 1.86kb | +0.00b | 10.17s | +4.08s ⚠️ |
| dist/16.4dbc75f9.js | 1.86kb | +0.00b | 4.92s | -369.00ms 🚀 |
| dist/workerHasher.afb52a72.js | 1.75kb | +0.00b | 10.46s | -2.78s 🚀 |
| dist/workerHasher.42458950.js | 1.75kb | +0.00b | 18.44s | +1.31s ⚠️ |
| dist/list-number.95becf64.js | 1.68kb | +0.00b | 5.94s | +356.00ms ⚠️ |
| dist/status.5568e78d.js | 1.68kb | +0.00b | 5.61s | -331.00ms 🚀 |
| dist/link.b4c4afb6.js | 1.53kb | +0.00b | 5.94s | +356.00ms ⚠️ |
| dist/heading3.0c0fe1f4.js | 1.51kb | +0.00b | 5.70s | -1.86s 🚀 |
| dist/16.01c01dd6.js | 1.46kb | +0.00b | 4.73s | -475.00ms 🚀 |
| dist/emoji.4f12a585.js | 1.45kb | +0.00b | 5.28s | -303.00ms 🚀 |
| dist/16.81d1aa0c.js | 1.45kb | +0.00b | 2.35s | +989.00ms ⚠️ |
| dist/16.897e8807.js | 1.44kb | +0.00b | 5.11s | -710.00ms 🚀 |
| dist/16.c2dce044.js | 1.40kb | +0.00b | 5.11s | -711.00ms 🚀 |
| dist/heading5.bde11017.js | 1.40kb | +0.00b | 5.70s | -383.00ms 🚀 |
| dist/expand.ca6be77b.js | 1.38kb | +0.00b | 10.17s | +4.09s ⚠️ |
| dist/16.ac96fdd0.js | 1.36kb | +0.00b | 4.92s | -366.00ms 🚀 |
| dist/16.620d8c15.js | 1.34kb | +0.00b | 2.35s | +989.00ms ⚠️ |
| dist/heading2.1511a751.js | 1.33kb | +0.00b | 5.70s | -1.86s 🚀 |
| dist/16.e0980eea.js | 1.32kb | +0.00b | 4.92s | -366.00ms 🚀 |
| dist/16.990be6f2.js | 1.31kb | +0.00b | 5.12s | -932.00ms 🚀 |
| dist/mention.e2501ad0.js | 1.29kb | +0.00b | 5.44s | -340.00ms 🚀 |
| dist/heading4.1abfeb0a.js | 1.29kb | +0.00b | 5.70s | -383.00ms 🚀 |
| dist/Modal.b44f65e1.js | 1.28kb | +0.00b | 4.53s | -554.00ms 🚀 |
| dist/16.30ebc170.js | 1.27kb | +0.00b | 2.35s | +989.00ms ⚠️ |
| dist/layout.6a9de36b.js | 1.27kb | +0.00b | 5.31s | -270.00ms 🚀 |
| dist/16.3ba7b0ec.js | 1.27kb | +0.00b | 4.92s | -369.00ms 🚀 |
| dist/16.2ec03e4f.js | 1.26kb | +0.00b | 4.72s | -343.00ms 🚀 |
| dist/16.98030c60.js | 1.26kb | +0.00b | 5.24s | -415.00ms 🚀 |
| dist/quote.be70ca39.js | 1.25kb | +0.00b | 5.56s | -380.00ms 🚀 |
| dist/component.3a931beb.js | 1.23kb | +0.00b | 4.68s | +577.00ms ⚠️ |
| dist/action.88cd1e67.js | 1.23kb | +0.00b | 5.12s | -353.00ms 🚀 |
| dist/16.7b2e1497.js | 1.23kb | +0.00b | 4.68s | +577.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.c2d3f430.js | 1.23kb | +0.00b | 13.19s | -1.01s 🚀 |
| dist/panel-warning.9b047bba.js | 1.21kb | +0.00b | 5.49s | -1.91s 🚀 |
| dist/16.c890a474.js | 1.18kb | +0.00b | 4.92s | -364.00ms 🚀 |
| dist/heading1.cf012b35.js | 1.18kb | +0.00b | 5.64s | -298.00ms 🚀 |
| dist/panel-error.0c73ee4f.js | 1.11kb | +0.00b | 5.44s | -340.00ms 🚀 |
| dist/panel.53ea0317.js | 1.10kb | +0.00b | 5.56s | -381.00ms 🚀 |
| dist/table.23e2141c.js | 1.09kb | +0.00b | 5.61s | -331.00ms 🚀 |
| dist/panel-success.b56c18fb.js | 1.05kb | +0.00b | 5.44s | -337.00ms 🚀 |
| dist/panel-note.d5e6a337.js | 1.05kb | +0.00b | 5.44s | -337.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.16608041.js | 1003.00b | +0.00b | 13.96s | -3.98s 🚀 |
| dist/media-card-analytics-error-boundary.64c19024.js | 999.00b | +0.00b | 11.99s | +989.00ms ⚠️ |
| dist/simpleHasher.931d48e8.js | 755.00b | +0.00b | 8.71s | -4.53s 🚀 |
| dist/simpleHasher.d4526885.js | 755.00b | +0.00b | 18.44s | +1.16s ⚠️ |
| dist/index.html | 119.00b | +0.00b | 2.14s | -1.14s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/card.ecae978d.js | 54.02kb | +0.00b | 650.00ms | +39.00ms ⚠️ |
| dist/Modal.a2c499cb.js | 39.18kb | +0.00b | 574.00ms | +32.00ms ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 14.65s | +148.00ms |
| Cached | 597.00ms | -33.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 580.59kb | +0.00b | 101.00ms | -11.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/289887979844928008)**

File: packages/reporters/dev-server/src/Server.js [hunk 1]
```diff
@@ -149,29 +149,29 @@ export default class Server {
...
-          }
-        },
-      );
+      let htmlBundleFilePaths = [];
+      this.bundleGraph.traverseBundles(bundle => {
+        if (bundle.type !== 'html' || !bundle.isEntry) {
+          return;
+        }
+
+        htmlBundleFilePaths.push(bundle.filePath);
```
Comment (mischnic) [inline packages/reporters/dev-server/src/Server.js:158]:
```suggestion
        if (bundle.type === 'html' && bundle.isEntry) {
          htmlBundleFilePaths.push(bundle.filePath);
        }
```

File: packages/reporters/dev-server/src/Server.js [hunk 2]
```diff
@@ -149,29 +149,29 @@ export default class Server {
...
+      });
 
-      if (htmlBundle) {
+      let indexFilePath =
+        htmlBundleFilePaths.length > 1
+          ? htmlBundleFilePaths
+              .sort((a, b) => {
+                return a.length - b.length;
+              })
```
Comment (mischnic) [inline packages/reporters/dev-server/src/Server.js:166]: I'm guessing you did this so that index files that aren't in subdirectories are preferred?

Maybe the strings themselves should be sorted as well, the order might not be stable across builds.

File: packages/reporters/dev-server/src/Server.js [hunk 3]
```diff
@@ -149,29 +149,29 @@ export default class Server {
...
+              .find(f => {
+                return path.basename(f).startsWith('index');
+              })
+          : htmlBundleFilePaths[0];
+      if (indexFilePath) {
         req.url = `/${path.relative(
           this.options.distDir,
-          nullthrows(htmlBundle.filePath),
+          nullthrows(indexFilePath),
```
Comment (mischnic) [inline packages/reporters/dev-server/src/Server.js:174]: Looks like the `nullthrows` can be removed now.

File: packages/reporters/dev-server/src/Server.js (hunk 2 above)
Comment (DeMoorJasper) [reply packages/reporters/dev-server/src/Server.js]: Yeah it's to ensure the most upper level index file gets served, added a second sort for sorting alphabetically as well (if length is the same

**Review by mischnic — APPROVED** [review]
