### PR TITLE
Fix HMR failure with js error on load, take 2

### LINKED ISSUE #879: 🐛Uncaught Error: Cannot find module '21'
### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc:
```json
{
  "presets": ["env"],
  "plugins": [
    ["babel-plugin-root-import", {
      "rootPathSuffix": "js",
      "rootPathPrefix": "@"
    }]
  ]
}
```

package.json:
```json
{
  "name": "hwm-parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "makmm",
  "license": "MIT",
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-root-import": "^5.1.0"
  }
}
```

### 🤔 Expected Behavior

Run `$ parcel index.html`, go to `localhost:1234`, change something in the code and the browser should get the new code and load it

### 😯 Current Behavior

Run `$ parcel index.html`, go to `localhost:1234`, **console shows correct sourcemaps:** 
image

change something in the code and this error comes up:
image

Refresh, now sourcemaps are broken:
image

### 💁 Possible Solution

No idea! <.<

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2 |
| Node             | 9.5.0 |
| npm         | 5.6.0 |
| Operating System | Debian sid |

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

See example.

I'm not sure if my changes have some side effect?
*Might* have a negative effect on scope-hoisting build sizes.

Fixes #879, previous attempt: #898

## 💻 Examples
On first load:
```js
throw new Error("STOP");

console.log("test");
```
Removing the Error line doesn't hmr successfully.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

File: packages/core/parcel-bundler/src/builtins/prelude.js [hunk 1]
```diff
@@ -103,5 +111,12 @@ parcelRequire = (function (modules, cache, entry, globalName) {
   }
 
   // Override the current require with this new one
+  parcelRequire = newRequire;
```
Comment (devongovett) [inline packages/core/parcel-bundler/src/builtins/prelude.js]: This seems dangerous. Why are we overwriting the global variable here? Won't that already happen when the function returns?

Comment (mischnic) [reply packages/core/parcel-bundler/src/builtins/prelude.js]: Because returning doesn't work if an error is thrown:

https://github.com/parcel-bundler/parcel/blob/75a71be0abe5082ca759680217ac128d2779b97d/packages/core/parcel-bundler/src/builtins/prelude.js#L114-L121

And this overwrites a global variable as well: 
https://github.com/parcel-bundler/parcel/blob/75a71be0abe5082ca759680217ac128d2779b97d/packages/core/parcel-bundler/src/builtins/prelude.js#L10
