### PR TITLE
Serve nearest index.html in case the applications has multiple index files

### LINKED ISSUE #4142: Client side routing with multiple entrypoints
# 🐛 bug report

(I think this problem description is simple enough that the full template is a bit overkill.)

I'm running with multiple entrypoints on the dev server, when an HMR reload is triggered, I get a 404 because it attempts to resolve the exact path (something like `/myapp.html/some/route`) rather than simply serving `/myapp.html` and allowing the client-side routing to take over for the `/some/route` portion.

Is this supported currently?

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

Some users were trying to serve multiple SPA applications at various sub-folders, this PR should fix the serving behaviour for this by serving the nearest index file.

Fixes #4142

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/298504293144592906)**

File: packages/reporters/dev-server/src/Server.js [hunk 1]
```diff
@@ -165,23 +174,31 @@ export default class Server {
...
+      let indexFilePath = null;
+      if (htmlBundleFilePaths.length === 1) {
+        indexFilePath = htmlBundleFilePaths[0];
+      } else {
+        let reqDirectory = getUrlDirectory(req.url);
+        indexFilePath = htmlBundleFilePaths
+          .filter(v => {
+            let dir = getUrlDirectory(v);
+            let filename = v.replace(dir, '');
+            let withoutExtension = filename.replace(path.extname(filename), '');
```
Comment (mischnic) [inline packages/reporters/dev-server/src/Server.js]: `v` is always a url to that bundle,
so `withoutExtension` could just be `path.posix.basename(v, path.posix.extname(v))`? 

Which is actually also the same as `v.endsWith("/index.html")`

**Review by devongovett — APPROVED** [review]

**Review by mischnic — APPROVED** [review]
