### PR TITLE
Fix HMR bugs

### LINKED ISSUE #3112: Hot reload only reload one line of parents
# 🐛 bug report

It appear that hot reload only refresh one line of dependant modules instead of all of dependant modules

## 💻 Code Sample

````javascript
// index.js
const render = async () => {
  const {App} = await import("./app");
  ReactDom.render(<App />, document.getElementById("app"));
}

render()
module.hot.accept(render)

// app.js
import "a";
import "b";

export const App = () => null;

// a.js
import {cpt} from "c";
console.log("a", cpt);

// b.js
import {cpt} from "c";
console.log("b", cpt);

// c.js
export const cpt = 1;
````
## 🤔 Expected Behavior

When cpt value is changed (to 2 for example) we expect to get the following logs
a 2
b 2

## 😯 Current Behavior

But we get only
b 2

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 12.3.0
| yarn         | 1.16.0
| ubuntu | 18.4

### LINKED ISSUE #4801: HMR only updates first component type when shared local dependency is saved
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "dependencies": {
    "parcel": "^2.0.0-beta.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}


```

## 🤔 Expected Behavior

When having `<Foo>` and `<Bar>` components with both importing a string `sample` from `./sample.js` and changing that 
string by saving `./sample.js` I would like both `Foo` and `Bar` being updated with the new string.

## 😯 Current Behavior
Only one of the components will be updated. i.e: If we have 2 x `<Foo/>` and 2 x `<Bar/>`, only 2 x `<Foo/>` will be updated.

## 🔦 Context

I would like to have HMR when saving local dependencies which are not React components and just provide data support for the components to consume.

## 💻 Code Sample

# app.js
```jsx
import React from 'react';
import {render} from 'react-dom';
import Foo from './foo';
import Bar from './bar';

const App = () => <>
    <Foo/>
    <Bar/>
    <Foo/>
</>;

module.hot?.accept();

const container = document.querySelector('.app');
container && render(<App/>, container);
```

# foo.js
```jsx
import React from 'react';
import sample from './sample';
const Foo = () => <div>{sample}</div>;
export default Foo;
```

# bar.js
```jsx
import React from 'react';
import sample from './sample';
const Bar = () => <div>{sample}</div>;
export default Bar;
```

# sample.js
```js
export default 'OLD'
```

By updating `sample.js` to `export default 'NEW'`, I then get on my browser:

```
NEW
OLD
NEW
```
instead of 
```
NEW
NEW
NEW
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |tested on 1.12.4  and ^2.0.0-beta.1
| Node             | 14.4.0
| npm/Yarn         |1.22.4
| Operating System | linux

### LINKED ISSUE #6685: Parcel 2: HMR Broken?
# 🐛 bug report

As per the unresolved issue #6586 I also get:

>the browser console just says "console cleared" - have to manually refresh? Also, until there is a code change this shows in browser console - [parcel] 🚨 Connection to the HMR server was lost

## 🤔 Expected Behavior

This used to update in place on the page a few weeks ago.

## 😯 Current Behavior

No changes are made but the console was cleared.

## 💁 Possible Solution

Not sure. How would I debug this? It's hard to see what's happening esp with the console clearing.

## 🔦 Context
Slowing down dev times.

## 💻 Code Sample
N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc0
| Node             | 14.15.0
| npm/Yarn         | berry (3.0.0)
| Operating System | mac

## Similar issues?

* https://github.com/parcel-bundler/parcel/issues/6586
* https://github.com/parcel-bundler/parcel/issues/6061
* https://github.com/parcel-bundler/parcel/issues/5660 with possible solution?
* https://github.com/parcel-bundler/parcel/issues/6026
* https://github.com/parcel-bundler/parcel/issues/6334
* https://github.com/parcel-bundler/parcel/issues/6235
* https://github.com/parcel-bundler/parcel/issues/6229
* https://github.com/parcel-bundler/parcel/issues/5998
* https://github.com/parcel-bundler/parcel/issues/5796
* https://github.com/parcel-bundler/parcel/issues/4801
* https://github.com/parcel-bundler/parcel/issues/4453
* https://github.com/parcel-bundler/parcel/issues/3112
* https://github.com/parcel-bundler/parcel/issues/2804

If there's suggestions on how the community can help debug these please provide some insight.

Thanks!

### LINKED ISSUE #7171: Regression: HMR issue with SolidJS and Parcel 2.0.0 release
# 🐛 bug report

When using Parcel 2.0.0 final release along with [SolidJS](https://github.com/solidjs), without calling module.hot.accept, the root node is duplicated in the page upon saving a file, rather than the page being reloaded as expected. For example, when using the [Solid Parcel Starter](https://gitlab.com/enom/solid-parcel-starter), you'll see the following duplication after saving a file.

```
Solid Parcel Starter

Solid Parcel Starter
```

This was previously discussed in [issue 289](https://github.com/parcel-bundler/parcel/issues/289), and the fix for it was working up until the 2.0.0 release.

The issue doesn't happen when using Parcel 2.0.0-rc.0.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["solid"]
}
```

## 🤔 Expected Behavior

Upon saving a file, if module.hot.accept hasn't been called, Parcel should perform a window.location.reload.

## 😯 Current Behavior

The root node of the page is duplicated, as if module.hot.accept has been called, even though it hasn't been.

## 💻 Steps to reproduce

1. Download Solid Parcel Starter from https://gitlab.com/enom/solid-parcel-starter
2. `npm i` and `npm run dev`
3. Make a change to index.js and observe that the page reloads in the browser as expected.
4. Stop server, then update parcel in package.json from "next" to "2.0.0."
5. `npm i` and `npm run dev`
6. Make a change to index.js and observe that the root node is duplicated rather than the page reloading.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 17.0.1
| npm/Yarn         | 8.1.0
| Operating System | Windows 10

### LINKED ISSUE #7241: Parcel 2.0.0 not reloading page on change anymore (Parcel 2.0.0-rc.0 still works fine)
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`

```js
{
  "extends": [
    "@parcel/config-default"
  ],
  "reporters": [
    "...",
    "parcel-reporter-static-files-copy"
  ],
  "resolvers": [
    "@parcel/resolver-glob",
    "..."
  ],
  "transformers": {
    "*.{js,mjs,jsx,cjs,ts,tsx}": [
      "@parcel/transformer-js"
    ]
  }
}
```

`package.json` relevant lines
```
"@parcel/core": "^2.0.0",
"@parcel/resolver-glob": "^2.0.0",
"@parcel/transformer-image": "^2.0.0",
"parcel": "^2.0.0",
"parcel-reporter-static-files-copy": "^1.3.0",
```

## 🤔 Expected Behavior

Page should reload when editing a file.

## 😯 Current Behavior

Nothing changes, but the browser console gets cleared. No new code gets injected. Have to manually refresh to see code changes.

## 💁 Possible Solution

No idea how to fix this, but I suspect it's related to this if statement branching differently between 2.0.0 and 2.0.0-rc.0:
https://github.com/parcel-bundler/parcel/blob/v2.0.0/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L113

Downgrading my packages to 2.0.0-rc.0 corrects the issue for me.

## 🔦 Context

This is for a pixi.js game project.

## 💻 Code Sample

I'll try to make a minimal example later that reproduces this issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 16.12.0
| Yarn         | 1.22.15
| Operating System | Linux Mint

### LINKED ISSUE #7307: Parcel does not reload when module is not accepted
# 🐛 bug report

My `index.html` file references `main.js`, which does not accept any hot updates:

```javascript
console.log("module loaded 1");
window.addEventListener("load", () => { console.log("onload"); });
```

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration is present.

## 🤔 Expected Behavior

In this configuration, modifying the code (e.g. changing "1" to "2") should reload the page, since the hot update cannot be accepted.

## 😯 Current Behavior

Instead, the hot update is accepted, the console is cleared, and the page is not reloaded. This is caused by [this check](https://github.com/parcel-bundler/parcel/blame/e0440dcbe6d6e419a412c8c568d94715cdb4282a/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L339) returning true.

## 💁 Possible Solution

I don't know enough about the blame commit to propose a solution, unfortunately.

## 🔦 Context

A workaround is to manually accept the hot update and forcibly reload the page. However, this requires knowing that this is happening, so it's confusing for new users of Parcel, like myself. Additionally, this is a waste of a few cycles, since the updated module gets evaluated by the browser only to immediately reload the page and redo that work.

An example of the workaround code:

```javascript
if (module.hot) {
  module.hot.accept(() => {
    window.location.reload();
  });
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | 14.17.0 |
| npm/Yarn         | 1.22.17 |
| Operating System | macOS |

### LINKED ISSUE #7386: Neither HMR nor page reload is working for helper functions imported in more than one component
# 🐛 bug report

HMR is not working for helper function imported in more than one component

## Steps to reproduce

I created a small repo to reproduce the bug: https://github.com/windheart/parcel-hmr-bug

1. Run `yarn install && yarn start`
2. Open browser and go to http://localhost:3000
3. Change packages/utils/fn1.ts return value to something else
4. See HMR is working
5. Change packages/utils/fn2.ts return value to something else
6. See HMR is not working (and reload too)

If we use fn1 both for Test1.tsx and Test2.tsx - HMR is working only for Test1.tsx

## 🤔 Expected Behavior

HMR (or reload) should be working for all imports 

## 😯 Current Behavior

Neither HMR nor reload is not working for second import

## 💁 Possible Solution

Difficult to say - if you give me some guidance, I can submit a PR

## 🔦 Context

I have a lot of helper functions in my codebase, it affects all of them

## 💻 Code Sample

https://github.com/windheart/parcel-hmr-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             |  14.18.1
| Yarn         |  1.22.4
| Operating System | Mac OS Monterey

### LINKED ISSUE #7409: Parcel 2: Browser is not updated when the source changes
Summary: When I start Parcel dev server via `parcel serve src/pages/*.html` it works fine for the very first time.
But when I make a change in the .tsx file, the browser is not updated.
Things that I have tried:
1. Force refresh browser
2. Change the file using another editor (Sublime, vim)
3. Stop and restart Parcel
4. `rm -rf dist` and `.parcel-cache`

After several tries, it just starts working fine (but for one time, later changes are again not shown).

My package.json:
```
{
  "name": "socialmonitr-front-end",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "private": true,
  "scripts": {
    "build": "parcel build src/pages/*.html --no-source-maps --no-scope-hoist",
    "serve": "parcel serve src/pages/*.html"
  },
  "keywords": [],
  "author": "",
  "license": "Commercial",
  "packageManager": "yarn@3.1.1",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.1",
    "@types/react": "17.0.34",
    "@types/react-dom": "17.0.11",
    "parcel": "2.0.1",
    "typescript": "4.4.3"
  },
  "dependencies": {
    "@emotion/react": "^11.7.0",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.2.0",
    "@mui/material": "^5.2.1",
    "@mui/x-data-grid": "^5.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  }
}

```

The source file can be any simple tsx:
```
export const Index = () => {
    return <>
        this is a test
    </>

}
```

index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>My Parcel App</title>
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    />
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />

</head>
<body>
<div id="app"></div>
<script type="module" src="index.js"></script>
</body>
</html>
```

index.js:
```
import ReactDOM from "react-dom"
import { Index } from "../components"

ReactDOM.render(<Index />, document.getElementById("app"));
```

Parcel: 2.0.1
Yarn: 3.1.1
Node: 16.11.0

I use IntelliJ to edit files but as I mentioned, even editing the TSX source using other browsers does not fix the issue.

P.S: Somehow I suspect this is related to Yarn 3 (PnP) because I downgraded to yarn v1 and (at least for now) it is working fine.

### PR DESCRIPTION
**Pull request by devongovett**
* Fixes #7386. Fixes #3112. Previously, we stopped traversing if _any_ parent accepted the update. We also collect a list of assets that need to be re-executed during this process, and if there were multiple parents of an asset, only one path may be added. Now, we traverse breadth first rather than depth first, and ensure that _all_ ancestries of an asset accept an update, and otherwise reload the whole page.
Fixes https://github.com/parcel-bundler/parcel/issues/4801
* Fixes #7307. Fixes #7171. Fixes #7241. Fixes #7409. This was a regression from 7468864f5ef8404309f4c681a2aa104d400cf5fc, where we assumed that if an asset has no parents then it is new and we should not perform a full page reload since the dependent asset may accept the update. This logic is incorrect, because entry assets also have no parents. Therefore, changing the entry asset caused the page not to be reloaded properly. Now, we instead check if the module exists in the cache already. However, this requires properly deleting orphaned assets when a dependency is removed so that when adding an asset back that was previously removed we also don't trigger a full page reload.

Possibly also fixes #6685, but I couldn't find a reproduction in that issue that didn't already work...

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.56s | +146.00ms ⚠️ |
| Cached | 414.00ms | +35.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 738.00ms | +41.00ms ⚠️ |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 746.00ms | +48.00ms ⚠️ |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 746.00ms | +48.00ms ⚠️ |
| dist/legacy/index.0a5c751e.js | 1.59kb | +0.00b | 1.08s | +75.00ms ⚠️ |
| dist/legacy/index.8aaa89c9.js | 1.20kb | +0.00b | 1.08s | +75.00ms ⚠️ |
| dist/modern/index.6be20f01.js | 1.13kb | +0.00b | 1.08s | +75.00ms ⚠️ |
| dist/legacy/index.html | 826.00b | +0.00b | 1.25s | +70.00ms ⚠️ |
| dist/modern/index.html | 749.00b | +0.00b | 1.25s | +70.00ms ⚠️ |
| dist/legacy/index.c1bc86aa.css | 94.00b | +0.00b | 1.42s | +86.00ms ⚠️ |
| dist/modern/index.57a95cbe.css | 94.00b | +0.00b | 1.41s | +83.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 767.00ms | +84.00ms ⚠️ |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 769.00ms | +83.00ms ⚠️ |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 768.00ms | +81.00ms ⚠️ |
| dist/legacy/index.0a5c751e.js | 1.59kb | +0.00b | 1.12s | +95.00ms ⚠️ |
| dist/legacy/index.8aaa89c9.js | 1.20kb | +0.00b | 1.12s | +96.00ms ⚠️ |
| dist/modern/index.6be20f01.js | 1.13kb | +0.00b | 1.12s | +97.00ms ⚠️ |
| dist/legacy/index.html | 826.00b | +0.00b | 1.31s | +115.00ms ⚠️ |
| dist/modern/index.html | 749.00b | +0.00b | 1.31s | +115.00ms ⚠️ |
| dist/legacy/index.c1bc86aa.css | 94.00b | +0.00b | 1.50s | +156.00ms ⚠️ |
| dist/modern/index.57a95cbe.css | 94.00b | +0.00b | 1.50s | +157.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 12.02s | -170.00ms |
| Cached | 507.00ms | -37.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.29m | -595.00ms |
| Cached | 1.73s | +211.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/editorView.124f5fc0.js | 594.92kb | +0.00b | 57.96s | +13.71s ⚠️ |
| dist/popup.64bc9a82.js | 209.67kb | +0.00b | 57.97s | +13.73s ⚠️ |
| dist/Toolbar.1af0e801.js | 107.23kb | +0.00b | 57.96s | +13.71s ⚠️ |
| dist/Modal.cd71eaf3.js | 45.33kb | +0.00b | 57.97s | +13.73s ⚠️ |
| dist/ui.5d3f7adc.js | 14.94kb | +0.00b | 57.97s | +13.72s ⚠️ |
| dist/smartMediaEditor.48c8cf63.js | 13.25kb | +0.00b | 57.96s | +13.71s ⚠️ |
| dist/dropzone.39132d0c.js | 12.16kb | +0.00b | 57.95s | +13.71s ⚠️ |
| dist/EmojiPickerComponent.0482d6c0.js | 3.73kb | +0.00b | 57.97s | +13.72s ⚠️ |
| dist/dropzone.55bef257.js | 3.29kb | +0.00b | 57.97s | +13.73s ⚠️ |
| dist/clipboard.df70240c.js | 2.93kb | +0.00b | 57.95s | +13.71s ⚠️ |
| dist/ResourcedEmojiComponent.667554b4.js | 2.12kb | +0.00b | 57.97s | +13.72s ⚠️ |
| dist/browser.4e039ed7.js | 1.69kb | +0.00b | 57.96s | +13.71s ⚠️ |
| dist/media-card-analytics-error-boundary.c718a9a7.js | 1.12kb | +0.00b | 57.95s | +13.71s ⚠️ |
| dist/media-picker-analytics-error-boundary.8b2547e5.js | 966.00b | +0.00b | 57.95s | +13.71s ⚠️ |
| dist/simpleHasher.fc0d6100.js | 643.00b | +0.00b | 57.97s | +13.72s ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/editorView.af442747.js | 594.92kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/popup.64bc9a82.js | 209.67kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/Toolbar.1af0e801.js | 107.23kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/Modal.cd71eaf3.js | 45.33kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/ui.5d3f7adc.js | 14.94kb | +0.00b | 43.50s | -16.08s 🚀 |
| dist/smartMediaEditor.48c8cf63.js | 13.25kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/dropzone.39132d0c.js | 12.16kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/EmojiPickerComponent.0482d6c0.js | 3.73kb | +0.00b | 43.50s | -16.08s 🚀 |
| dist/dropzone.55bef257.js | 3.29kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/clipboard.df70240c.js | 2.93kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/ResourcedEmojiComponent.667554b4.js | 2.12kb | +0.00b | 43.50s | -16.08s 🚀 |
| dist/browser.4e039ed7.js | 1.69kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/media-card-analytics-error-boundary.c718a9a7.js | 1.12kb | +0.00b | 43.49s | -16.10s 🚀 |
| dist/media-picker-analytics-error-boundary.8b2547e5.js | 966.00b | +0.00b | 43.49s | -16.10s 🚀 |
| dist/simpleHasher.fc0d6100.js | 643.00b | +0.00b | 43.50s | -16.08s 🚀 |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.56s | +201.00ms |
| Cached | 451.00ms | +10.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 579.68kb | +0.00b | 5.88s | -399.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/319636319968952914)**

File: packages/runtimes/hmr/src/loaders/hmr-runtime.js [hunk 1]
```diff
@@ -300,10 +315,73 @@ function hmrApply(bundle /*: ParcelRequire */, asset /*:  HMRAsset */) {
...
+        break;
+      }
+      parents.push(...p);
+    }
+  }
+
+  return accepted;
+}
+
+function hmrAcceptCheckOne(
```
Comment (mischnic) [inline packages/runtimes/hmr/src/loaders/hmr-runtime.js:381]: So I guess the idea was that `hmrAcceptCheck` does the parent traversal and `hmrAcceptCheckOne` just checks if the single asset accepts, without the ancestry? But `hmrAcceptCheckOne` still calls `hmrAcceptCheck`, is that intentional?

Comment (devongovett) [reply packages/runtimes/hmr/src/loaders/hmr-runtime.js:381]: I think it should be ok because it only happens for the initial bundle, not when finding parents (because `depsByBundle` is null then).

**Review by mischnic — APPROVED** [review]

**Comment by Systemcluster** [comment]
Is this PR included in `parcel 2.0.0-nightly.961` / `@parcel/runtime-browser-hmr 2.0.0-nightly.963`?

**Comment by mischnic** [comment]
Yes

**Comment by Nikruto** [comment]
```
import React from "react";
import { render } from "react-dom";
import "./index.css";

render(<div>Heyyo</div>, document.getElementById("root"));

```
using 2.0.0-nightly.961 and hmr still not working for css

**Comment by devongovett** [comment]
@Nikruto your example works fine for me
