### PR TITLE
Unhandled HMR updates should cause a page reload

### LINKED ISSUE #289: 🙋 Regular Browser Reload on File Save
🙋

Hi there! I'd like to start exploring Parcel as a workflow for creative coding (WebGL, Canvas2D, etc). I'm trying to migrate some programs I've written for non-HMR workflow to this new HMR workflow, and I'm hitting huge performance issues since the code (which is doing things like creating a WebGL/Canvas context) was not designed to be re-run multiple times.

### 🎛 Configuration 

Take a simple program like this:

```js
const canvas = document.createElement('canvas');
const ctx = canvas.getContext('2d');

document.body.appendChild(canvas);
```

### 🤔 Expected Behavior

I'd like to develop with the same way that a JS file runs/loads in the browser (i.e. once, not many times). If possible, I'd like a way to replace JavaScript HMR with a simple `window.location.reload()` functionality. However, other features (like CSS) should still use HMR / inject without hard reload.

### 😯 Current Behavior

Currently the above code, when saved several times, will create several canvas elements in the body.

### 💁 Possible Solution

A way of turning on/off regular hot reload. I am assuming this may already exist, but I couldn't find it, so perhaps it's more an issue of documentation?

### LINKED ISSUE #2455: Hot Module Reload incompatible with some widgets libraries
# 🐛 bug report

I'm trying to use the excellent [Webix components library](https://stackoverflow.com/questions/200284/what-are-alternatives-to-extjs) with Parcel. The problem is that Parcel apparently doesn't fully unload the nodes created by Webix, so after HMR triggers, Webix complains about "Non unique view id"s. Full repro on CodeSandbox.

[Parcel + webix](https://codesandbox.io/s/6l5nr5r4zn)

### LINKED ISSUE #2509: HMR with reacts appends a new app instance instead of replace the current
I have a parcel + react + css modules project. Whenever I save a file, the entire application gets re-rendered and appended to the #root container instead of replacing the whole thing.

This is what my index.js file looks like:

```javascript
import React, { StrictMode } from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom';
import { ApolloProvider } from 'react-apollo';
import './index.css';
import App from './app';
import client from './apollo-client';

ReactDOM.createRoot(document.getElementById('root')).render(
  <StrictMode>
    <Router>
      <ApolloProvider client={client}>
        <App />
      </ApolloProvider>
    </Router>
  </StrictMode>,
);

```

This is what it looks like when I save the same file three times.

screen shot 2019-01-04 at 12 10 09

What am I doing wrong?

### LINKED ISSUE #2606: Hot reload with setInterval
# 🐛 bug report

1. When I start up a parcel server;
2. In index.js i write this line of code:
`setInterval(console.log, 1000, 'hello')`
3. Then i change this line with:
`setInterval(console.log, 1000, 'how are you')`
4. Then i save changes.
5. After reloading i get both intervals going at the same time.

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json
```json
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "parcel-test",
  "main": "index.js",
  "scripts": {
  	"dev": "parcel serve src/index.html",
  	"build": "parcel build src/index.html",
  	"help": "parcel help",
    "test": "test"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.11.0"
  }
}
```

## 🤔 Expected Behavior

Previous interval should be cleared.

## 😯 Current Behavior

Previous interval is not cleared.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 8.11.2
| npm/Yarn         | 5.6.0
| Operating System | Windows 10

### LINKED ISSUE #2675: Page reload doesn't work with lit-element
# 🐛 bug report

Im working on a simple single page application build with lit-element. I bundle everything together using parcel and that works pretty good. But in live development, whenever I change something inside of a custom element, the page won't refresh and I geht this issue:
"Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry"

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "dev": "parcel watch src/index.html",
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "dependencies": {
    "lit-element": "^2.0.1",
    "lit-element-router": "^1.0.0"
  },
  "devDependencies": {
    "parcel-bundler": "^1.11.0"
  },
  "browserslist": [
    "Chrome 72"
  ]
}
```

## 🤔 Expected Behavior

The custom element should be reloaded and I should just see the changes I made.

## 😯 Current Behavior

I get this error message instead:
"Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry"
And there is no reload. If I refresh the page myself, everything works just fine... until I change something else.

## 💁 Possible Solution

No idea :(

## 🔦 Context

I also tried out my project on webpack and everything works there, except I don't like how webpack manages assets etc.
So it seems to be a parcel issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 11.10.0
| npm        | 6.7.0
| Operating System | Windows 10

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

As mentioned in https://github.com/parcel-bundler/parcel/issues/289#issuecomment-379529297

Closes #289, closes #2675, closes #2606, closes #2455, closes #2509

## 💻 Examples

Would case a full reload:
```js
document.body.innerHTML += "Test21213asdadsd<br>";
```

Would not:
```js
document.body.innerHTML += "Test21213asdadsd<br>";

if(module.hot){
	module.hot.accept(()=>{
		console.log("Hello");
	})
}
```

## 🚨 Test instructions

See example

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
I just noticed a major flaw: this breaks the "React HMR just works" feature, because re-executing all Javascript is fine with React. But it doesn't work with setInterval (#2606) or HTML custom elements (#2675).

One possible solution: disabling this change when react is used, or only adding the reload flag.

**Comment by DeMoorJasper** [comment]
If this breaks react it will likely break a lot more libraries/frameworks.

I think the reload flag would probably be our best bet in this case

**Comment by mischnic** [comment]
Closing as this change would break the other half of libraries (current React et al. work and setTimeout etc. don't).

File: packages/core/parcel-bundler/src/builtins/hmr-runtime.js [hunk 1]
```diff
@@ -36,11 +36,16 @@ if ((!parent || !parent.isParcelRequire) && typeof WebSocket !== 'undefined') {
         hmrApply(global.parcelRequire, asset);
       });
 
+      var handled = false;
       data.assets.forEach(function (asset) {
         if (!asset.isNew) {
-          hmrAccept(global.parcelRequire, asset.id);
+          handled = handled || hmrAccept(global.parcelRequire, asset.id);
```
Comment (devongovett) [inline packages/core/parcel-bundler/src/builtins/hmr-runtime.js]: I think this will cause updates to stop after the first asset accepts. Then handled will be true and hmrAccept won’t get called on other assets. I think we need to ensure that hmrAccept is still called for all assets, and just keep track of handled separately.

Comment (mischnic) [reply packages/core/parcel-bundler/src/builtins/hmr-runtime.js]: Fixed,
another way to fix this would have been:
```js
handled = hmrAccept(global.parcelRequire, asset.id) || handled;
```
But I think it doesn't really convey the intention as well (at first glance).

**Comment by mischnic** [comment]
A downside: everything runs twice, before the reload and after the reload. Might still be an issue in some infinite loop situations.

bildschirmfoto 2019-03-03 um 21 48 39

**Comment by devongovett** [comment]
mmm, so really what we should do is do two passes: 1 to check if any module will accept, and another to actually re-execute the modules if so, or reload the page if not.

**Comment by mischnic** [comment]
> to check if any module will accept

= does any `accept` or `dispose` callback exist. I *think* that's correct

File: packages/core/parcel-bundler/src/builtins/hmr-runtime.js [hunk 2]
```diff
@@ -29,21 +29,36 @@ if ((!parent || !parent.isParcelRequire) && typeof WebSocket !== 'undefined') {
...
-      data.assets.forEach(function (asset) {
-        hmrApply(global.parcelRequire, asset);
+      var handled = false;
+      data.assets.forEach(function(asset) {
+        handled =
+          handled ||
+          (global.parcelRequire.cache[asset.id] &&
+            (Boolean(global.parcelRequire.cache[asset.id].hot._acceptCallbacks.length) ||
+             Boolean(global.parcelRequire.cache[asset.id].hot._disposeCallbacks.length)
+             )
```
Comment (devongovett) [inline packages/core/parcel-bundler/src/builtins/hmr-runtime.js]: This isn't quite enough. You need to traverse upward from the asset to the root asset and check if any of the parents accept the update as well as the asset itself. Basically, we need to split `hmrAccept` up into two functions. One that traverses upward and checks if an update should be accepted, but without actually re-executing them. It can also keep track of all of the assets that need to be re-executed in a list. Then, if an update is accepted, go through the list we tracked earlier, and re-execute them.

Comment (mischnic) [reply packages/core/parcel-bundler/src/builtins/hmr-runtime.js]: Done: extracted the actual execution into `hmrAcceptRun` and kept track of them in `assetsToAccept`

**Comment by louh** [comment]
Hey, I wanted to comment here because when we updated our `parcel-bundler` to 1.12.3 we found that HMR is broken. (issue: https://github.com/streetmix/streetmix/pull/1357#issuecomment-505055425) Only by reverting to an earlier version we would get it back, but that's what let me down this rabbit hole to try and find what might have broken in 1.12.x.

When we adopted Parcel initially, we did have issues with the HMR (as many people have) but we gradually resolved each of our issues and now HMR works quite well with our app. As a result, it was upsetting to discover that default HMR functionality completely broke. Usually, when an API changes in a library, I expect to see a large, bold "BREAKING CHANGE" notice in the Changelog, which would have given us context and an ability to properly handle the change. Ideally, this would have also been a major version bump as this functionality was introduced without being backwards-compatible. (I think, as a minor version bump, the ideal solution would have been to disable HMR with a flag, instead of changing the default.)

I now know what to do, but I think the fix shouldn't have been hidden in a comment in another issue (https://github.com/parcel-bundler/parcel/issues/289#issuecomment-469536807).

I'll be looking into making a pull request to update your documentation and Changelog for people who might be running into similar issues. Thanks for your work on Parcel!

**Comment by wyozi** [comment]
#2509 still a problem in 2.0.0-alpha.3.2, so not sure this PR fixed that
