### PR TITLE
Scope hoisting: register individual exports of intermediate side-effect-free reexports

### LINKED ISSUE #6300: Dynamic imports do not work with non-default imports in the dynamic module
# 🐛 bug report

**Bug only happens after creating production build**

There is a weird bug in Parcel 2 (`2.0.0-nightly.671`) when trying to use dynamic imports. So in theory it does correct code splitting with dynamic imports. But when in the imported module I use import like `import { makeStyles } from "@material-ui/styles";` then it crashes application but only after building production version. It works in development. The error says that it can't find module when importing `makeStyles`.

The problem goes away if I don't use dynamic imports, so it doesn't look like an issue with material-ui. Also possible solution is to not use named import but default import in the dynamic module. So instead of writing
```import { makeStyles } from "@material-ui/styles";```
I have to write
```import makeStyles from "@material-ui/styles/makeStyles";```
and then it works.

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration. Just default Parcel 2 project with TypeScript + React

package.json

```json
{
  "name": "parcel2-bug",
  "version": "1.0.0",
  "license": "MIT",
  "dependencies": {
    "@loadable/component": "^5.15.0",
    "@material-ui/core": "^4.11.4",
    "@material-ui/styles": "^4.11.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2"
  },
  "devDependencies": {
    "@types/loadable__component": "^5.13.3",
    "@types/react": "^17.0.5",
    "@types/react-dom": "^17.0.5",
    "@types/react-router": "^5.1.14",
    "@types/react-router-dom": "^5.1.7",
    "parcel": "2.0.0-nightly.671",
    "typescript": "^4.2.4"
  },
  "scripts": {
    "build": "parcel build src/index.html --detailed-report --cache-dir .cache --no-cache",
    "start": "yarn build; npx http-serve -p 3000 ./dist/"
  }
}
```

## 🤔 Expected Behavior

Working dynamic imports with non-default imports in the imported module.

## 😯 Current Behavior

Error throw in the browser console:

```
index.b0a2e93c.js:1 Uncaught Error: Cannot find module '5Pkhs'
    at a (index.b0a2e93c.js:1)
    at Object.<anonymous> (clsx.m.js:39)
    at a (index.b0a2e93c.js:1)
    at getThemeProps.js:22
    at index.tsx:9
```

## 💁 Possible Solution

As I mentioned there is a way to write workaround for it but I would have to change named imports to default imports in the entire project.

## 🔦 Context

Dynamic module imports should just work no matter what I'm importing in the dynamic module. It looks like there is some problem with tree shaking, I guess?

## 💻 Code Sample

Reproduction repository: https://github.com/lukejagodzinski/parcel2-bug
```
yarn
yarn start
```
It will create production build and run local sever

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.671
| Node             | 12 and 14
| npm/Yarn         | Yarn 1.22.10
| Operating System | MacOS Catalina 10.15.7

### PR DESCRIPTION
**Pull request by wbinnssmith**
Fixes #6300

This fixes an issue where a wrapped side-effect-free reexport of a side-effect-free reexport would result in "Cannot find module". When packaging, only check directly wrapped assets instead of assets that are wrapped recursively.

Test Plan: Added an integration test

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.88s | -69.00ms |
| Cached | 415.00ms | -19.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.0aef9bfa.js | 2.00kb | +0.00b | 1.01s | -63.00ms 🚀 |
| dist/modern/index.4f9cafee.js | 2.00kb | +0.00b | 1.01s | -63.00ms 🚀 |
| dist/legacy/index.607396a1.css | 77.00b | +0.00b | 1.01s | -61.00ms 🚀 |
| dist/modern/index.9523eca2.css | 77.00b | +0.00b | 1.01s | -61.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 59.00ms | -6.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 77.00ms | -9.00ms 🚀 |
| dist/legacy/index.0aef9bfa.js | 2.00kb | +0.00b | 78.00ms | -9.00ms 🚀 |
| dist/modern/index.4f9cafee.js | 2.00kb | +0.00b | 78.00ms | -8.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 77.00ms | -10.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 78.00ms | -9.00ms 🚀 |
| dist/legacy/index.607396a1.css | 77.00b | +0.00b | 77.00ms | -10.00ms 🚀 |
| dist/modern/index.9523eca2.css | 77.00b | +0.00b | 78.00ms | -8.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 12.15s | +123.00ms |
| Cached | 690.00ms | -62.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/PermalinkedComment.0c75a695.js | 4.19kb | +0.00b | 437.00ms | +26.00ms ⚠️ |
| dist/UserProfile.031c1548.js | 1.56kb | +0.00b | 437.00ms | +26.00ms ⚠️ |
| dist/NotFound.c3254f12.js | 417.00b | +0.00b | 437.00ms | +26.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 491.15kb | +0.00b | 90.00ms | -8.00ms 🚀 |
| dist/PermalinkedComment.0c75a695.js | 4.19kb | +0.00b | 90.00ms | -7.00ms 🚀 |
| dist/UserProfile.031c1548.js | 1.56kb | +0.00b | 90.00ms | -7.00ms 🚀 |
| dist/NotFound.c3254f12.js | 417.00b | +0.00b | 90.00ms | -8.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 69.00ms | +5.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.35m | -440.00ms |
| Cached | 3.22s | +121.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.08f5b63e.js | 2.60mb | +224.00b ⚠️ | 1.05m | -444.00ms |
| dist/smartMediaEditor.520ca4a5.js | 13.25kb | +0.00b | 26.89s | +1.81s ⚠️ |
| dist/16.fe096c73.js | 1.33kb | +0.00b | 4.03s | +212.00ms ⚠️ |
| dist/expand.c97517e7.js | 1.29kb | +0.00b | 5.40s | +356.00ms ⚠️ |
| dist/simpleHasher.5278a07e.js | 641.00b | +0.00b | 26.89s | +1.81s ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.0602e74b.js | 2.60mb | +247.00b ⚠️ | 189.00ms | +13.00ms ⚠️ |
| dist/pdf.worker.19255c11.js | 727.98kb | +0.00b | 307.00ms | +53.00ms ⚠️ |
| dist/editorView.8a137ee4.js | 594.99kb | +0.00b | 308.00ms | +47.00ms ⚠️ |
| dist/pdfRenderer.cb376b35.js | 411.56kb | +0.00b | 307.00ms | +53.00ms ⚠️ |
| dist/popup.927a8cf2.js | 209.85kb | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/EmojiPickerComponent.412ee5a3.js | 147.28kb | +0.00b | 302.00ms | +47.00ms ⚠️ |
| dist/Toolbar.a209217c.js | 107.27kb | +0.00b | 308.00ms | +47.00ms ⚠️ |
| dist/media-viewer.c62ffe63.js | 74.99kb | +0.00b | 307.00ms | +53.00ms ⚠️ |
| dist/card.e7d7c250.js | 62.67kb | +0.00b | 307.00ms | +52.00ms ⚠️ |
| dist/card.f65239d6.js | 60.71kb | +0.00b | 308.00ms | +47.00ms ⚠️ |
| dist/Modal.07838ef5.js | 45.33kb | +0.00b | 195.00ms | +19.00ms ⚠️ |
| dist/component.669627f8.js | 37.59kb | +0.00b | 195.00ms | +19.00ms ⚠️ |
| dist/esm.1a8ccc42.js | 33.24kb | +0.00b | 302.00ms | +48.00ms ⚠️ |
| dist/component.642b7085.js | 24.95kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/DatePicker.f59b61d9.js | 22.99kb | +0.00b | 288.00ms | +71.00ms ⚠️ |
| dist/js.85def1c2.js | 17.33kb | +0.00b | 196.00ms | +20.00ms ⚠️ |
| dist/ui.e7f1a4ff.js | 14.94kb | +0.00b | 307.00ms | +52.00ms ⚠️ |
| dist/smartMediaEditor.520ca4a5.js | 13.25kb | +0.00b | 308.00ms | +49.00ms ⚠️ |
| dist/dropzone.6a0faa90.js | 12.15kb | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/workerHasher.95f27d4e.js | 11.81kb | +0.00b | 302.00ms | +48.00ms ⚠️ |
| dist/component.9e1648d9.js | 6.82kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/card.006509f3.js | 5.96kb | +0.00b | 307.00ms | +53.00ms ⚠️ |
| dist/media-viewer.b1bdbe97.js | 4.51kb | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/media-viewer.9cc3198b.js | 3.98kb | +0.00b | 307.00ms | +53.00ms ⚠️ |
| dist/EmojiPickerComponent.2bfbf673.js | 3.72kb | +0.00b | 307.00ms | +53.00ms ⚠️ |
| dist/png-chunks-extract.26a58e9e.js | 3.58kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/index.e7480283.css | 3.46kb | +0.00b | 312.00ms | +47.00ms ⚠️ |
| dist/dropzone.0f7eb4e4.js | 3.29kb | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/Modal.97b7b979.js | 3.15kb | +0.00b | 195.00ms | +19.00ms ⚠️ |
| dist/clipboard.6dd872f2.js | 2.93kb | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/16.ca688077.js | 2.36kb | +0.00b | 190.00ms | +15.00ms ⚠️ |
| dist/ResourcedEmojiComponent.425492a2.js | 2.12kb | +0.00b | 307.00ms | +52.00ms ⚠️ |
| dist/card.1653aa06.js | 2.06kb | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/date.13837189.js | 1.86kb | +0.00b | 219.00ms | +18.00ms ⚠️ |
| dist/images.a51e31c2.js | 1.80kb | +0.00b | 230.00ms | +29.00ms ⚠️ |
| dist/feedback.a4084b43.js | 1.77kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/16.b8c83009.js | 1.75kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/browser.cede5d10.js | 1.69kb | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/16.f48613ba.js | 1.68kb | +0.00b | 195.00ms | +12.00ms ⚠️ |
| dist/workerHasher.a91c28d5.js | 1.63kb | +0.00b | 302.00ms | +48.00ms ⚠️ |
| dist/workerHasher.a70276d4.js | 1.63kb | +0.00b | 308.00ms | +49.00ms ⚠️ |
| dist/list-number.494da4e7.js | 1.59kb | +0.00b | 232.00ms | +30.00ms ⚠️ |
| dist/status.8783408d.js | 1.59kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/code.677bd70c.js | 1.51kb | +0.00b | 219.00ms | +18.00ms ⚠️ |
| dist/heading6.2df789d9.js | 1.51kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/heading3.99e77e15.js | 1.49kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/link.eecf8ee1.js | 1.43kb | +0.00b | 231.00ms | +30.00ms ⚠️ |
| dist/16.0f105e82.js | 1.40kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/heading5.c9eff376.js | 1.38kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/emoji.e0bb5bdd.js | 1.36kb | +0.00b | 230.00ms | +29.00ms ⚠️ |
| dist/16.2475b7ab.js | 1.35kb | +0.00b | 195.00ms | +12.00ms ⚠️ |
| dist/16.24ecf6d5.js | 1.35kb | +0.00b | 195.00ms | +11.00ms ⚠️ |
| dist/16.fe096c73.js | 1.33kb | +0.00b | 194.00ms | +20.00ms ⚠️ |
| dist/16.9c0dd14e.js | 1.33kb | +0.00b | 195.00ms | +19.00ms ⚠️ |
| dist/heading2.689c1725.js | 1.32kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/16.f6f07bdf.js | 1.29kb | +0.00b | 198.00ms | +13.00ms ⚠️ |
| dist/expand.c97517e7.js | 1.29kb | +0.00b | 235.00ms | +18.00ms ⚠️ |
| dist/heading4.a48496c5.js | 1.27kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/16.abb96752.js | 1.25kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/16.8a916ec3.js | 1.22kb | +0.00b | 190.00ms | +15.00ms ⚠️ |
| dist/16.5ab0c52f.js | 1.21kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/16.17b379b7.js | 1.20kb | +0.00b | 218.00ms | +17.00ms ⚠️ |
| dist/mention.7513d265.js | 1.20kb | +0.00b | 234.00ms | +27.00ms ⚠️ |
| dist/layout.a2215d1e.js | 1.18kb | +0.00b | 231.00ms | +30.00ms ⚠️ |
| dist/Modal.71b21a38.js | 1.17kb | +0.00b | 195.00ms | +19.00ms ⚠️ |
| dist/16.dc7fba57.js | 1.16kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/heading1.53882705.js | 1.16kb | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/16.4947d5d2.js | 1.16kb | +0.00b | 190.00ms | +15.00ms ⚠️ |
| dist/divider.61f72909.js | 1.16kb | +0.00b | 229.00ms | +28.00ms ⚠️ |
| dist/quote.ac356b63.js | 1.15kb | +0.00b | 235.00ms | +20.00ms ⚠️ |
| dist/16.61848cd9.js | 1.15kb | +0.00b | 195.00ms | +11.00ms ⚠️ |
| dist/16.f88600cd.js | 1.15kb | +0.00b | 195.00ms | +11.00ms ⚠️ |
| dist/16.3457832f.js | 1.15kb | +0.00b | 196.00ms | +12.00ms ⚠️ |
| dist/16.59da43e0.js | 1.15kb | +0.00b | 195.00ms | +12.00ms ⚠️ |
| dist/action.03622130.js | 1.13kb | +0.00b | 219.00ms | +18.00ms ⚠️ |
| dist/component.0faea072.js | 1.12kb | +0.00b | 189.00ms | +13.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.92f81a75.js | 1.12kb | +0.00b | 307.00ms | +53.00ms ⚠️ |
| dist/decision.e8963abf.js | 1.12kb | +0.00b | 219.00ms | +18.00ms ⚠️ |
| dist/panel-warning.d87689fa.js | 1.11kb | +0.00b | 234.00ms | +26.00ms ⚠️ |
| dist/16.71584d67.js | 1.11kb | +0.00b | 190.00ms | +15.00ms ⚠️ |
| dist/list.452d2378.js | 1.08kb | +0.00b | 232.00ms | +30.00ms ⚠️ |
| dist/16.d79d0001.js | 1.07kb | +0.00b | 196.00ms | +11.00ms ⚠️ |
| dist/panel-error.2d1266a1.js | 1.01kb | +0.00b | 234.00ms | +27.00ms ⚠️ |
| dist/panel.2fa2f198.js | 1.01kb | +0.00b | 234.00ms | +26.00ms ⚠️ |
| dist/table.5143dd29.js | 1022.00b | +0.00b | 235.00ms | +19.00ms ⚠️ |
| dist/panel-success.8c4cf740.js | 978.00b | +0.00b | 234.00ms | +26.00ms ⚠️ |
| dist/panel-note.aa22bfaa.js | 974.00b | +0.00b | 234.00ms | +27.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.c51589b7.js | 964.00b | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.3cb68a8b.js | 964.00b | +0.00b | 308.00ms | +54.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.b94e1438.js | 960.00b | +0.00b | 307.00ms | +52.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.a9392a91.js | 960.00b | +0.00b | 308.00ms | +49.00ms ⚠️ |
| dist/simpleHasher.74d2cfec.js | 641.00b | +0.00b | 302.00ms | +48.00ms ⚠️ |
| dist/simpleHasher.5278a07e.js | 641.00b | +0.00b | 308.00ms | +49.00ms ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.22s | -38.00ms |
| Cached | 635.00ms | +16.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/299806063264268808)**

File: packages/core/integration-tests/test/scope-hoisting.js [hunk 1]
```diff
@@ -3609,6 +3609,18 @@ describe('scope hoisting', function() {
 
       assert.deepEqual(await run(b), 42);
     });
+
+    it('registers intermediate wrapped reexports', async () => {
```
Comment (devongovett) [inline packages/core/integration-tests/test/scope-hoisting.js]: Should we change the name of this test + the integration directory?

**Review by devongovett — APPROVED** [review]
