### PR TITLE
Add AppVeyor CI & fix tests on Windows

### LINKED ISSUE #174: Tests Fail on Windows | +AppVeyor
**Choose one:**   &nbsp;&nbsp;&nbsp;&nbsp;  🐛

### 🤔 Expected Behavior

Tests pass on all platforms.

### 😯 Current Behavior

Currently, ~50% of the tests are failing on Windows ([see AppVeyor results](https://ci.appveyor.com/project/brandon93s/parcel)). Some of these are due to a failure in a `beforeEach` hook, but others are legitimate failures. **The test failures could mean that `parcel` isn't working correctly on Windows. (e.g. #86)**

### 💁 Possible Solution

1) Add AppVeyor alongside Travis.ci
2) Start working through and correcting the failures

### 🌍 Your Environment

Occurring on Windows 10 (local) and Windows Server 2012/2016 (AppVeyor).
Occurring on Node.js v9.2.0 (local) and Node.js v8.x.x (AppVeyor).

### PR DESCRIPTION
**Pull request by brandon93s**
**PR:**
- Added AppVeyor config. Will need to be toggle on (@devongovett)
- Fixed broken tests on Windows (css, glob, javascript, watcher, html and hmr)
- The changes proposed in #159 fix the failing stylus tests

**Notes:**
- Most issues were path related to Window's vs Unix paths (`\` vs `/`). Need to leverage `path.join()` going forward over string concatenation for compatibility.
- Odd formatting is from `prettier`

**Closes #174**

### CODE REVIEW

File: src/assets/GlobAsset.js [hunk 1]
```diff
@@ -12,8 +12,15 @@ class GlobAsset extends Asset {
   }
 
   async load() {
-    let files = await globPromise(this.name, {strict: true, nodir: true});
-    let re = micromatch.makeRe(this.name, {capture: true});
+    let regularExpressionSafeName = this.name;
+    if (process.platform === 'win32')
+      regularExpressionSafeName = regularExpressionSafeName.replace(/\\/g, '/');
+
```
Comment (brandon93s) [inline src/assets/GlobAsset.js]: `\` is an escape in regex; converting to unix style paths here. The `glob` module does the transform internally but `micromatch` doesn't. Doing it here ensures consistency. This was more than just the tests, globs didn't work on Windows.

File: test/css.js [hunk 2]
```diff
@@ -137,10 +137,14 @@ describe('css', function() {
```
Comment (brandon93s) [inline test/css.js]: Windows "randomly generated" class is not `1ezyc`. Update tests to:

- Check for the pattern `_index_[0-9a-z]+_1`
- Extract the found pattern to find it in the output css

File: test/html.js [hunk 3]
```diff
@@ -73,7 +73,11 @@ describe('html', function() {
     });
 
     let html = fs.readFileSync(__dirname + '/dist/index.html');
```
Comment (brandon93s) [inline test/html.js]: Styling prettier is applying here is kinda hard to read, so to explain:

Check for `\` OR `/` in the path. It will be different on Windows vs Other.

**Comment by davidnagli** [comment]
Note: Waiting on #159 to be merged

**Comment by brandon93s** [comment]
@davidnagli #159 landed. This should be good to go now.

**Comment by devongovett** [comment]
Awesome, thanks!

File: test/html.js [hunk 4]
```diff
@@ -73,7 +73,11 @@ describe('html', function() {
...
-    assert(/<link rel="stylesheet" href="\/dist\/[a-f0-9]+\.css">/.test(html));
+    assert(
+      /<link rel="stylesheet" href="[\/\\]{1}dist[\/\\]{1}[a-f0-9]+\.css">/.test(
```
Comment (devongovett) [inline test/html.js]: hmm, this seems weird actually. URLs should always use `/`. Might be a bug.
