### PR TITLE
Fix absolute path importing in sass

### LINKED ISSUE #2431: Sass "Absolute Path" Module Resolution Fails
# 🐛 bug report

Importing Sass files fails when using the [absolute path](https://parceljs.org/module_resolution.html#absolute-paths) approach to module resolution.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel-1403-reproduction-sass",
  "scripts": {
    "serve": "parcel src/index.html"
  },
  "devDependencies": {
    "parcel": "^1.10.3",
    "sass": "^1.15.2"
  },
  "dependencies": {
    "normalize.css": "^8.0.1"
  }
}
```

## 🤔 Expected Behavior

Sass imports should work with absolute path-style module resolution.

## 😯 Current Behavior

An error is thrown:

```
> parcel src/index.html

Server running at http://localhost:1234
🚨  /Users/evan/Code/parcel-1403-reproduction-sass/src/styles/index.scss:3:9: Can't find stylesheet to import.
@import '/styles/_variables.scss';
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  stdin 3:9  root stylesheet
Error: Can't find stylesheet to import.
@import '/styles/_variables.scss';
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  stdin 3:9  root stylesheet
```

## 💁 Possible Solution

I'm not sure, but does the sass package not use the same module resolution algorithm? The [docs suggest that all supported asset types](https://parceljs.org/module_resolution.html#module-resolution) should work.

## 🔦 Context

I ran into this while attempting to reproduce issue #1403 which I came to because I'm unable to import normalize.css into a project.

## 💻 Code Sample

https://github.com/evanleck/parcel-1403-reproduction-sass

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 10.14.0
| npm/Yarn         | npm 6.5.0
| Operating System | macOS 10.14.2

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

For some reason the sass compiler adds `file://` to absolute paths, this PR removes that as file paths should be resolved by parcel...

Fixes #2431

### CODE REVIEW

File: packages/core/parcel-bundler/src/assets/SASSAsset.js [hunk 1]
```diff
@@ -45,6 +45,7 @@ class SASSAsset extends Asset {
       ? opts.importer
       : [opts.importer];
     opts.importer.push((url, prev, done) => {
+      url = url.replace('file://', '');
```
Comment (devongovett) [inline packages/core/parcel-bundler/src/assets/SASSAsset.js]: probably should only replace it if it is at the beginning

Comment (DeMoorJasper) [reply packages/core/parcel-bundler/src/assets/SASSAsset.js]: Updated :)

**Comment by evanleck** [comment]
Sorry to pester but is there any chance of this getting merged? I opened issue #2431 that this fixes.
