### PR TITLE
Fix live bindings and `this` of external CommonJS modules

### LINKED ISSUE #6241: Scope hoisting replaces `obj.hasOwnProperty` with `hasOwnProperty`
# 🐛 bug report

Scope hoisting replaces `obj.hasOwnProperty` with `hasOwnProperty`. This results in the following error:

The error:
```js
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
```

I hit this in Node-graceful-fs although it will be fixed in:
https://github.com/isaacs/node-graceful-fs/pull/206

Here is the minimal reproduction:
```js
const constants = require('constants')

console.log(constants.hasOwnProperty('O_SYMLINK'))

```
Gives:
```js
var hasOwnProperty = require("constants").hasOwnProperty;
console.log(hasOwnProperty('O_SYMLINK'));

//# sourceMappingURL=a.js.map
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "test": "./a.js",
  "scripts" : {
    "build":  "parcel build --no-optimize --target test ./a.source.js"
  },
  "targets": {
    "test": {
      "context": "node"
    }
  }
}
```

## 🤔 Expected Behavior

Keep the `obj.`

## 😯 Current Behavior

Removes `obj.`

## 💁 Possible Solution

1. Don't use scope hoisting for now.
2. Don't bundle fs-graceful

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.653
| Node             | 16
| npm/Yarn         | 6
| Operating System | Win10

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #6241. Fixes T-1057.

Makes external CJS modules always use property lookups rather than destructuring the imported symbols. This ensures live bindings work properly, and also that `this` references are correct.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 11.05s | -149.00ms |
| Cached | 530.00ms | +12.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.91s | +192.00ms |
| Cached | 433.00ms | -14.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/303505269927707201)**

**Review by mischnic — APPROVED** [review]

File: packages/packagers/js/src/ScopeHoistingPackager.js [hunk 1]
```diff
@@ -569,24 +577,51 @@ ${code}
...
-            renamed = local;
-          } else if (imported === 'default' || imported === '*') {
-            renamed = this.getTopLevelName(
-              `$${this.bundle.publicId}$${dep.specifier}`,
-            );
+          // For CJS output, always use a property lookup so that exports remain live.
+          // For ESM output, use named imports which are always live.
+          if (this.bundle.env.outputFormat === 'commonjs') {
+            renamed = external.get('*');
+            if (!renamed) {
```
Comment (wbinnssmith) [inline packages/packagers/js/src/ScopeHoistingPackager.js:584]: nit: sketchy null check, though empty string makes no sense here

**Review by wbinnssmith — APPROVED** [review]
