### PR TITLE
Throw helpful error on wrong reexport in entry for bundle exports

### LINKED ISSUE #3813: Missing export not detected
# 🐛 bug report

Why don't we detect that `b.js` doesn't export `a`? Instead, the packager fails because everything was (correctly) deferred.

```json
{
    "main": "build.js",
    "sideEffects": false
}
```

```js
// a.js (entry point)
export {a} from "./b.js";

// b.js
export {default as c1} from "./c1.js";
export {default as c2} from "./c2.js";

// c1.js
export default "foo";

// c2.js
export default "bar";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Fixes #3813

## 💻 Examples

`{"sideEffects": false}`

```js
// index.js
export { Foo } from "./other.js";

// other.js
export const Bar = 1234;
```
would result in an empty bundle or a cryptic build error (depending on output format). Now it says `other.js does not export 'Foo'`

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.00s | -228.00ms |
| Cached | 3.63s | +301.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 202.00ms | +27.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 201.00ms | +27.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 336.00ms | +318.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 334.00ms | +318.00ms ⚠️ |
| dist/legacy/index.js | 460.00b | +0.00b | 340.00ms | +316.00ms ⚠️ |
| dist/modern/index.js | 452.00b | +0.00b | 334.00ms | +316.00ms ⚠️ |
| dist/legacy/index.css | 29.00b | +0.00b | 334.00ms | +318.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 333.00ms | +318.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.56s | -463.00ms |
| Cached | 3.67s | -145.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/module/index.js | 34.33kb | +0.00b | 12.00ms | -351.00ms 🚀 |
| dist/main/index.js | 34.08kb | +0.00b | 18.00ms | -351.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.29m | -1.27s |
| Cached | 6.13s | +110.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +4.00b ⚠️ | 1.93m | -1.55s |
| dist/Toolbar.1e87337e.js | 105.85kb | +0.00b | 1.08m | -13.35s 🚀 |
| dist/media-viewer.81fbeba4.js | 87.56kb | +0.00b | 8.59s | +449.00ms ⚠️ |
| dist/card.c0473744.js | 76.88kb | +0.00b | 8.59s | +450.00ms ⚠️ |
| dist/card.f99e1597.js | 5.92kb | +0.00b | 14.81s | +919.00ms ⚠️ |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 8.53s | +428.00ms ⚠️ |
| dist/card.2c902906.js | 1.73kb | +0.00b | 14.81s | +920.00ms ⚠️ |
| dist/card.aae6ebb9.js | 1.04kb | +0.00b | 14.81s | +918.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.dd752a9e.js | 779.00b | +0.00b | 14.81s | +919.00ms ⚠️ |
| dist/esm.976debcc.js | 180.00b | +0.00b | 8.50s | +428.00ms ⚠️ |
| dist/dropzone.976debcc.js | 179.00b | +1.00b ⚠️ | 15.92s | -1.69m 🚀 |
| dist/clipboard.976debcc.js | 179.00b | +1.00b ⚠️ | 41.79s | +272.00ms |
| dist/browser.976debcc.js | 179.00b | +1.00b ⚠️ | 1.08m | +23.32s ⚠️ |
| dist/editorView.976debcc.js | 179.00b | -1.00b 🚀 | 1.92m | +52.93s ⚠️ |
| dist/media-card-analytics-error-boundary.976debcc.js | 178.00b | -5.00b 🚀 | 42.67s | +26.77s ⚠️ |
| dist/16.976debcc.js | 176.00b | -5.00b 🚀 | 41.79s | -596.00ms |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.34mb | +4.00b ⚠️ | 294.00ms | +28.00ms ⚠️ |
| dist/smartMediaEditor.678dca17.js | 602.09kb | +0.00b | 130.00ms | +10.00ms ⚠️ |
| dist/popup.ab87d357.js | 259.28kb | +0.00b | 168.00ms | +9.00ms ⚠️ |
| dist/EmojiPickerComponent.6fc09ddc.js | 105.94kb | +0.00b | 124.00ms | +9.00ms ⚠️ |
| dist/Toolbar.1e87337e.js | 105.85kb | +0.00b | 120.00ms | +9.00ms ⚠️ |
| dist/card.c0473744.js | 76.88kb | +0.00b | 164.00ms | +9.00ms ⚠️ |
| dist/ui.c85d9c1b.js | 73.78kb | +0.00b | 122.00ms | +10.00ms ⚠️ |
| dist/smartMediaEditor.25b0ed57.js | 67.38kb | +0.00b | 121.00ms | +9.00ms ⚠️ |
| dist/component.10b390dc.js | 46.04kb | +0.00b | 152.00ms | +16.00ms ⚠️ |
| dist/DatePicker.0242ec52.js | 27.54kb | +0.00b | 121.00ms | +8.00ms ⚠️ |
| dist/EmojiPickerComponent.bcce358c.js | 24.31kb | +0.00b | 121.00ms | +7.00ms ⚠️ |
| dist/workerHasher.d7e20c98.js | 11.57kb | +0.00b | 120.00ms | +8.00ms ⚠️ |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 120.00ms | +7.00ms ⚠️ |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 150.00ms | +15.00ms ⚠️ |
| dist/index.css | 3.38kb | +0.00b | 106.00ms | +7.00ms ⚠️ |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 151.00ms | +15.00ms ⚠️ |
| dist/EmojiUploadComponent.0460cc59.js | 2.92kb | +0.00b | 120.00ms | +7.00ms ⚠️ |
| dist/component.ab65829f.js | 2.30kb | +0.00b | 151.00ms | +15.00ms ⚠️ |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 144.00ms | +15.00ms ⚠️ |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 141.00ms | +16.00ms ⚠️ |
| dist/16.de3f3184.js | 1.63kb | +0.00b | 149.00ms | +15.00ms ⚠️ |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 139.00ms | +16.00ms ⚠️ |
| dist/feedback.01d7bcf7.js | 1.53kb | +0.00b | 122.00ms | +8.00ms ⚠️ |
| dist/workerHasher.854262ce.js | 1.49kb | +0.00b | 120.00ms | +8.00ms ⚠️ |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 135.00ms | +17.00ms ⚠️ |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 138.00ms | +16.00ms ⚠️ |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 146.00ms | +16.00ms ⚠️ |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 149.00ms | +15.00ms ⚠️ |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 148.00ms | +17.00ms ⚠️ |
| dist/code.092e0137.js | 1.28kb | +0.00b | 141.00ms | +16.00ms ⚠️ |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 143.00ms | +16.00ms ⚠️ |
| dist/16.51bbc68e.js | 1.24kb | +0.00b | 143.00ms | +16.00ms ⚠️ |
| dist/component.8351f228.js | 1.23kb | +0.00b | 151.00ms | +14.00ms ⚠️ |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 138.00ms | +16.00ms ⚠️ |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 123.00ms | +9.00ms ⚠️ |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 143.00ms | +15.00ms ⚠️ |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 133.00ms | +17.00ms ⚠️ |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 148.00ms | +15.00ms ⚠️ |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 143.00ms | +15.00ms ⚠️ |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 142.00ms | +16.00ms ⚠️ |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 142.00ms | +18.00ms ⚠️ |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 145.00ms | +16.00ms ⚠️ |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 147.00ms | +16.00ms ⚠️ |
| dist/16.24165259.js | 1.09kb | +0.00b | 148.00ms | +16.00ms ⚠️ |
| dist/16.74510c56.js | 1.09kb | +0.00b | 147.00ms | +16.00ms ⚠️ |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 146.00ms | +16.00ms ⚠️ |
| dist/16.a79db876.js | 1.09kb | +0.00b | 150.00ms | +16.00ms ⚠️ |
| dist/heading5.2f045997.js | 1.07kb | +0.00b | 132.00ms | +17.00ms ⚠️ |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 150.00ms | +15.00ms ⚠️ |
| dist/expand.13380081.js | 1.05kb | +0.00b | 122.00ms | +9.00ms ⚠️ |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 142.00ms | +15.00ms ⚠️ |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 133.00ms | +16.00ms ⚠️ |
| dist/mention.9fdad24e.js | 983.00b | +0.00b | 137.00ms | +16.00ms ⚠️ |
| dist/fallback.305c8864.js | 982.00b | +0.00b | 134.00ms | +16.00ms ⚠️ |
| dist/heading4.63d1ca06.js | 978.00b | +0.00b | 132.00ms | +17.00ms ⚠️ |
| dist/layout.6f66c2da.js | 964.00b | +0.00b | 139.00ms | +16.00ms ⚠️ |
| dist/divider.160f3108.js | 942.00b | +0.00b | 143.00ms | +17.00ms ⚠️ |
| dist/quote.88bfdca4.js | 938.00b | +0.00b | 136.00ms | +17.00ms ⚠️ |
| dist/action.146450ba.js | 921.00b | +0.00b | 141.00ms | +16.00ms ⚠️ |
| dist/decision.06254b93.js | 900.00b | +0.00b | 140.00ms | +14.00ms ⚠️ |
| dist/panel-warning.59c8ef3f.js | 893.00b | +0.00b | 136.00ms | +16.00ms ⚠️ |
| dist/list.4f623de3.js | 872.00b | +0.00b | 137.00ms | +16.00ms ⚠️ |
| dist/heading1.65fb8482.js | 866.00b | +0.00b | 133.00ms | +16.00ms ⚠️ |
| dist/panel-error.c2479698.js | 793.00b | +0.00b | 137.00ms | +16.00ms ⚠️ |
| dist/panel.23cd7224.js | 790.00b | +0.00b | 136.00ms | +17.00ms ⚠️ |
| dist/table.4ace5843.js | 782.00b | +0.00b | 134.00ms | +16.00ms ⚠️ |
| dist/panel-success.6a7b97d7.js | 730.00b | +0.00b | 137.00ms | +17.00ms ⚠️ |
| dist/panel-note.5ff85bdc.js | 729.00b | +0.00b | 137.00ms | +17.00ms ⚠️ |
| dist/simpleHasher.884d4eb6.js | 450.00b | +0.00b | 120.00ms | +9.00ms ⚠️ |
| dist/esm.976debcc.js | 179.00b | -1.00b 🚀 | 158.00ms | +5.00ms |
| dist/media-card-analytics-error-boundary.976debcc.js | 179.00b | -1.00b 🚀 | 156.00ms | +6.00ms |
| dist/dropzone.976debcc.js | 179.00b | -1.00b 🚀 | 153.00ms | +6.00ms |
| dist/clipboard.976debcc.js | 179.00b | -1.00b 🚀 | 152.00ms | +6.00ms |
| dist/browser.976debcc.js | 179.00b | -1.00b 🚀 | 151.00ms | +5.00ms |
| dist/16.976debcc.js | 179.00b | -1.00b 🚀 | 142.00ms | +16.00ms ⚠️ |
| dist/editorView.976debcc.js | 179.00b | -1.00b 🚀 | 118.00ms | +8.00ms ⚠️ |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/255913546179674634)**

File: packages/shared/scope-hoisting/src/formats/commonjs.js [hunk 1]
```diff
@@ -276,13 +284,16 @@ export function generateExports(
...
     } else {
-      for (let {exportSymbol, symbol} of bundleGraph.getExportedSymbols(
+      for (let {exportSymbol, symbol, asset} of bundleGraph.getExportedSymbols(
         entry,
       )) {
-        if (symbol) {
-          symbol = replacements.get(symbol) || symbol;
+        if (!symbol) {
+          let relativePath = relative(options.inputFS.cwd(), asset.filePath);
+          throw new Error(`${relativePath} does not export '${exportSymbol}'`);
```
Comment (devongovett) [inline packages/shared/scope-hoisting/src/formats/commonjs.js]: Do we have enough information to show a diagnostic?

Comment (mischnic) [reply packages/shared/scope-hoisting/src/formats/commonjs.js]: Ideally we would include a codeFrame of the relevant sections, but that isn't possible without your AST reusing PR.

I've now added a diagnostic with `messages` and `filePath` and modified `prettyDiagnostic` to use `filePath` as a fallback for `stack` (@DeMoorJasper ?):

Bildschirmfoto 2020-02-05 um 16 14 23
