### PR TITLE
fix: allow msapplication-* with real content

### LINKED ISSUE #8821: mstile causing bundle duplication
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No special configuration options, just the parcel@2 logo from the parcel website and an HTML file:
```html
<head>
  <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="parcel.png?width=144&height=144" />
    <meta name="msapplication-square70x70logo" content="parcel.png?width=70&height=70" />
    <meta name="msapplication-square150x150logo" content="parcel.png?width=150&height=150" />
    <meta name="msapplication-square310x310logo" content="parcel.png?width=310&height=310" />
</head>
```

## 🤔 Expected Behavior

mstile should work as expected and not cause an error

## 😯 Current Behavior

```
Error: Bundles must have unique names

  AssertionError [ERR_ASSERTION]: Bundles must have unique names
      at BundlerRunner.nameBundles (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:390:23)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async BundlerRunner.bundle (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:341:7)
      at async Object.run (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:156:17)
      at async RequestTracker.runRequest (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async Object.run (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:56:7)
      at async RequestTracker.runRequest (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async Parcel._build (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/Parcel.js:400:11)
      at async Parcel.run (/workspace/parcel-triage-mstile/node_modules/@parcel/core/lib/Parcel.js:276:18)
      at async run (/workspace/parcel-triage-mstile/node_modules/parcel/lib/cli.js:376:7)
```

## 🔦 Context

I would like to allow my site to be added as a microsoft application, and that requires mstile metadata

## 💻 Code Sample

https://github.com/LeoDog896/parcel-triage-mstile

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 16.19.0
| npm/Yarn         | 8.19.3 / 1.22.19
| Operating System | Linux

### PR DESCRIPTION
**Pull request by tristan-f-r**
# ↪️ Pull Request

Fixes #8821, allowing mstile assets to not be duplicated

## 💻 Examples

```html
<head>
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="parcel.png?width=144&height=144" />
  <meta name="msapplication-square70x70logo" content="parcel.png?width=70&height=70" />
  <meta name="msapplication-square150x150logo" content="parcel.png?width=150&height=150" />
  <meta name="msapplication-square310x310logo" content="parcel.png?width=310&height=310" />
</head>
```
## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Included links to related issues/PRs

### CODE REVIEW

File: packages/core/integration-tests/test/html.js [hunk 1]
```diff
@@ -304,6 +304,10 @@ describe('html', function () {
         name: 'logo.svg',
         assets: ['logo.svg'],
       },
+      {
+        name: 'logo.14afa1de.svg',
```
Comment (tristan-f-r) [inline packages/core/integration-tests/test/html.js]: I'm sure theres a better way to do this, but I'm not sure what's good in the test suite for that.

Comment (mischnic) [reply packages/core/integration-tests/test/html.js]:
```suggestion
        type: 'svg',
```

File: packages/core/integration-tests/test/html.js [hunk 2]
```diff
@@ -312,6 +316,11 @@ describe('html', function () {
     );
     assert(html.includes(`<meta name="msapplication-config" content="none">`));
     assert(html.includes(`<meta property="og:image" content="/logo.svg">`));
+    assert(
+      html.includes(
+        `<meta name="msapplication-TileImage" content="/logo.14afa1de.svg">`,
```
Comment (mischnic) [inline packages/core/integration-tests/test/html.js]: This has to be a regex check instead `/<meta name="msapplication-TileImage" content="/logo\.[0-9a-f]+\.svg">`/`

**Review by mischnic — APPROVED** [review]
