### PR TITLE
Multiple css bundles in Entry bundle groups issue

### LINKED ISSUE #8813: Improve the handling of entry bundle collisions
# 🐛 bug report

1. Bundle names collide under certain circumstances, but it is unclear to the user which asset(s) cause the problem, or why, or what to do to fix it.  Suggestions would be helpful.  I notice parcel > 2.8.3 had a recent commit to output asset names, which is an improvement.  However, in a larger app, with many dynamic imports, or other conditional code paths, it would difficult to know *what* happened and how to deal with it.

2. Parcel appears to be failing to invalidate the cache when code changes.

Given a source tree which does not bundle on first run (no cache, etc.):

If the code is changed so that parcel can bundle it, and parcel writes a cache during that successful compilation, and the code change is then reverted (such that it should fail to bundle as it originally did), parcel will in fact succeed -- by virtue of the cache created during the previous successful build.

## 🎛 Configuration (.babelrc, package.json, cli command)

Out of the box parcel, no additional configuration.

## 🤔 Expected Behavior

Tell me exactly which assets are the problem, and why (dynamic import and where in the tree, etc.).

Ideally though, for some cases parcel would simply know what to do.  The real-world code which caused this problem is much more complicated, although it does build with webpack 4 (as part of a `create-react-app`).

## 😯 Current Behavior

Parcel outputs an `AssertionError` and aborts.

## 💁 Possible Solution

Output enough information that I might be able to fix it.

Unsure how parcel could automatically handle this; I'm not sure what webpack is doing (but it does bundle).

## 🔦 Context

I am trying to move a `create-react-app` to Parcel without making any Parcel specific changes to the source.

In the app, which the code is slightly different, I was actually able to "solve" this problem by changing the export list of the module which is causing the problem, and consequently the import method as well.  But, it took me quite a long time to understand what was happening whatsoever, because the error message was uninformative.

## 💻 Code Sample

Both issues are described in the README and `src/index.js` of a small re-pro project.  I included Graphviz PNG dumps as well.

https://github.com/richardkmichael/parcel-repro

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             |  16.19.0
| npm/Yarn         | 8.19.3
| Operating System | macOS 11.7.2

### PR DESCRIPTION
**Pull request by AGawrys**
# ↪️ Pull Request

This PR aims to fix #8813 , or, the issue of having multiple css/ type change bundles in one entry bundlegroup. Currently we only merge if those bundles share the same bundleGroups, this isn't perfect because it may result in sibling type change bundles within one bundlegroup. 

The solution below duplicates assets of the "offending" bundle in favor of maintaining the "1 type change bundle per bundlegroup" rule, and does so based on the overlap of bundleGroups. 

~~This changes the current behavior in a non-significant way, so I have a couple questions about if this change is okay, specifically for the affected test cases.~~

**Update** Tests now align with **v2** as we don't merge or duplicate assets if not `needsStableName`

## 💻 Examples & Questions

Here are the graphs of the reproduction from  issue #8813: 

**Before:** 
`AssertionError [ERR_ASSERTION]: Bundle group cannot have more than one entry bundle of the same type` 
**After:**
<p align="center">

</p>

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x]  Add test case mentioned in question 3 & Potentially expand feature to support scenario( where shared css sibling bundle can neither be merged nor duplicated, i.e. each shares a bundle group, but also each have their own unique bundle groups)
- [x] Included links to related issues/PRs

### Update: 

Only merging in the case of, `needsStableName` bundles, and only duplicating `css` assets **iff** they cannot be merged.
**Affected Test cases** have been reverted since they no longer meet the conditions of `needsStableName` for merging

### CODE REVIEW

File: packages/core/integration-tests/test/css-modules.js [hunk 1]
```diff
@@ -547,7 +547,7 @@ describe('css modules', () => {
       },
     ]);
   });
-  // Forked because experimental bundler will not merge bundles of same types if they do not share all their bundlegroups
```
Comment (AGawrys) [inline packages/core/integration-tests/test/css-modules.js]: Removing this comment because this feature changes the behavior to match legacy bundler

File: packages/core/integration-tests/test/html.js [hunk 2]
```diff
@@ -2213,7 +2213,7 @@ describe('html', function () {
       },
       {
         type: 'css',
-        assets: ['shared.css'],
+        assets: ['shared.css', 'other.css'], //We've duplicated 'other' to maintain 1 css bundle per entry
```
Comment (devongovett) [inline packages/core/integration-tests/test/html.js]: Shouldn't this only apply to bundles with `needsStableName`? In this case, `other.css` is moved into a shared bundle which is fine because it's in HTML and not an entry.

Comment (AGawrys) [reply packages/core/integration-tests/test/html.js]: Thank you for reviewing! My confusion is when exactly css bundles should be merged. In this example, there are technically only two bundlegroups right? Since the type change bundles are not bundleGroups. So we have a.html and b.html bundleGroup. And I guess my assumption was that all bundles in an entry bundleGroup have `needsStableName` . 

I think that's where I'm unsure of what the behavior should be. cc: @devongovett

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.49s | +52.00ms |
| Cached | 269.00ms | +2.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.html | 826.00b | +0.00b | 418.00ms | +21.00ms ⚠️ |
| dist/legacy/index.b8ae99ba.css | 94.00b | +0.00b | 290.00ms | +28.00ms ⚠️ |
| dist/modern/index.31cedca9.css | 94.00b | +0.00b | 289.00ms | +28.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 251.00ms | -17.00ms 🚀 |
| dist/legacy/index.b8ae99ba.css | 94.00b | +0.00b | 260.00ms | -21.00ms 🚀 |
| dist/modern/index.31cedca9.css | 94.00b | +0.00b | 260.00ms | -21.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 4.01s | -15.00ms |
| Cached | 419.00ms | -7.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.8dd07848.png | 244.00b | +0.00b | 232.00ms | -15.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.8dd07848.png | 244.00b | +0.00b | 265.00ms | +25.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 35.91s | -709.00ms |
| Cached | 2.39s | +30.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/component-lazy.aeb22f50.js | 59.50kb | +0.00b | 5.82s | -511.00ms 🚀 |
| dist/codeViewerRenderer.7d374cd5.js | 2.61kb | +0.00b | 8.85s | -3.04s 🚀 |
| dist/ro.ee42c980.js | 478.00b | +0.00b | 6.47s | -1.91s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/media-viewer.bc1a2415.js | 537.32kb | +0.00b | 12.38s | +689.00ms ⚠️ |
| dist/EmojiPickerComponent.c199902f.js | 189.68kb | +0.00b | 12.40s | +640.00ms ⚠️ |
| dist/ConfigPanelFieldsLoader.1a016f33.js | 82.96kb | +0.00b | 12.40s | +640.00ms ⚠️ |
| dist/pdfRenderer.6335b9a2.js | 12.08kb | +0.00b | 12.38s | +3.64s ⚠️ |
| dist/index.html | 248.00b | +0.00b | 6.30s | -5.63s 🚀 |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.95s | -25.00ms |
| Cached | 323.00ms | -13.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/376227799674913349)**

File: packages/core/integration-tests/test/css.js [hunk 3]
```diff
@@ -68,7 +68,59 @@ describe('css', () => {
...
+      },
+      {
+        type: 'js',
+        assets: ['esmodule-helpers.js', 'index.js'],
+      },
+      {name: 'Foo.css', type: 'css', assets: ['foo.css']},
+      {name: 'entry.css', type: 'css', assets: ['foo.css', 'main.css']},
+    ]);
+  });
+  it.skip('create a new css bundle to maintain one css bundle per bundlegroup constraint', async () => {
```
Comment (devongovett) [inline packages/core/integration-tests/test/css.js:96]: skipped?

Comment (AGawrys) [reply packages/core/integration-tests/test/css.js:96]: Oh forgot about this... okay yes so I still do have one more question. The current solution works with our existing test cases and fixes the cases in the mentioned issue. **However**, I added this case as an alternative and I'm not sure what our best move is. No one has encountered this to my knowledge yet.

In this test case, we have 1 entry (`entry.js`) with two `async js` siblings, with which it shared two other `.css` files (`main` and `foo.css` ) 

Both `foo.css` (3) and `main.css` (2) have `needsStableName: true` but have no subset or perfect overlap in terms of bundleGroups. Should we over-fetch and merge them anyway or should we create a new bundle with duplicated just for `entry.js`?

AFAIK old bundler just inefficiently merged them. 

neithercanhost
cc: @devongovett

**Comment by jondlm** [comment]
I ran into this one again today with another codebase. Seems like maybe we should move forward with the fix even though we don't have a great solution to the `skip`ed test?

**Comment by jondlm** [comment]
@AGawrys I was testing out this patch today and noticed that [`BitSet` here](https://github.com/parcel-bundler/parcel/pull/9023/files#diff-e06d72b9dc8c51ce91705f2a8abf1cad7024a22fe93d5d1400302abf07ae11bdR27) has been moved to `@parcel/graph`. It's being double imported and failing. I simply removed the import from `@parcel/util` and it seems to work now.

**Comment by jondlm** [comment]
Darn. Tested this patch out on our codebase and I'm at least getting a slightly more helpful error message :)

```
🚨 Build failed.

@parcel/namer-default: Bundle group cannot have more than one entry bundle of the same type. The offending bundle type is css
```

I'll dig into it more next week.

**Comment by TobiasSchikora** [comment]
Any updates on this? :-/

**Comment by jondlm** [comment]
Sorry forgot to circle back on this. Unfortunately that patch didn't fix the issue so I'm still hunting for a proper fix.

**Comment by TobiasSchikora** [comment]
It seems to be a very hard bug. Thank you anyway for your efforts. I think you would help many people who want to update from Parcel 1 to Parcel 2 but can't because of this bug, including me. I also notice that using Parcel 1 is slowly becoming a problem. This can't go on for long and I don't want to switch to Vite or anything else because I really like Parcel. I hope a solution can be found! Thank you!

**Comment by AGawrys** [comment]
@jondlm @TobiasSchikora So sorry that this has been such a pain for you. I updated the branch, removing the extra bitSet import seemed to work for me. 

@jondlm In this PR there is a scenario I wasn't sure how to cover, it could be what you're running into? i.e.  A new scenario with the same symptom. Do you have a public repro or minimal repro I could take a look at so I could confirm?  I can work to expand this fix if my hunch is correct.

 In the meantime I'll try to get this merged today.

**Review by jondlm — APPROVED** [review]
LGTM. I tested it out with one of my [repros](https://github.com/jondlm/parcel-bug-css-name-collision) and it fixed the issue. I still think there are some lurking issues with duplicate css bundles but this seems like a step in the right direction.

Thank you @AGawrys!

**Comment by AGawrys** [comment]
@jondlm 
Sorry, I had to formally request you as a reviewer for your approval to allow me to merge, mind approving once more? Thanks

**Review by jondlm — APPROVED** [review]
Sure thing!

**Comment by jondlm** [comment]
Oh. I don't have write access to the repo so my review probably doesn't count :(

**Review by mischnic — APPROVED** [review]
There you go 😄

**Comment by TobiasSchikora** [comment]
WOW, that's really great news. I can't wait to try it out! Thank you very much! 🧡

**Comment by TobiasSchikora** [comment]
OK, I have now installed the latest Nightly (`2.11.1-nightly.3109`). The original error message is gone, but I have a new one:

```
🚨 Build failed.

@parcel/bundler-default: Edge from 289 to 83 not found!

  Error: Edge from 289 to 83 not found!
      at ContentGraph.removeEdge (C:\mf\node_modules\@parcel\graph\lib\Graph.js:117:13)
      at createIdealGraph (C:\mf\node_modules\@parcel\bundler-default\lib\DefaultBundler.js:648:43)
      at Object.bundle (C:\mf\node_modules\@parcel\bundler-default\lib\DefaultBundler.js:123:19)
      at BundlerRunner.bundle (C:\mf\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:261:23)
      at async Object.run (C:\mf\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:129:17)
      at async RequestTracker.runRequest (C:\mf\node_modules\@parcel\core\lib\RequestTracker.js:653:20)
      at async Object.run (C:\mf\node_modules\@parcel\core\lib\requests\ParcelBuildRequest.js:52:7)
      at async RequestTracker.runRequest (C:\mf\node_modules\@parcel\core\lib\RequestTracker.js:653:20)
      at async Parcel._build (C:\mf\node_modules\@parcel\core\lib\Parcel.js:315:11)
      at async Parcel._startNextBuild (C:\mf\node_modules\@parcel\core\lib\Parcel.js:223:24)
```

Does anyone know what to do there? Thanks for any help!
