### PR TITLE
Make NodeResolver check realpath before resolving with `source` entry

### LINKED ISSUE #5784: `package.json#source` field is used for npm packages with pnpm
# 🐛 bug report

When using pnpm, the resolver tries to use the `"source"` field of a package from npm.

## 😯 Current Behavior

```
🚨 Build failed.
@parcel/core: Failed to resolve 'compute-scroll-into-view' from './index.js'
/index.js:1:35
> 1 | import computeScrollIntoView from "compute-scroll-into-view";
>   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | computeScrollIntoView();
@parcel/resolver-default: Could not load './src/index.ts' from module 'compute-scroll-into-view' found in package.json#source
/node_modules/compute-scroll-into-view/package.json:88:13
  87 |   },
> 88 |   "source": "src/index.ts",
>    |             ^^^^^^^^^^^^^^ './src/index.ts' does not exist, did you mean './dist/index.js'?'
  89 |   "umd:main": "umd/compute-scroll-into-view.min.js"
  90 | }
```

## 🤔 Expected Behavior

Ignore `package.json#source` for npm packages

## 🔦 Context

https://github.com/parcel-bundler/parcel/issues/5604#issuecomment-773799994

## 💻 Code Sample

```js
import computeScrollIntoView from "compute-scroll-into-view";

computeScrollIntoView();
```

```json
{
  "dependencies": {
    "@babel/core": "^7.12.13",
    "compute-scroll-into-view": "^1.0.16"
  }
}
```

Use `pnpm install`!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  31f431d93da97d3edc3f489847053ef601412666

### LINKED ISSUE #7610: Parcel tries to import `source` of dependency instead of `main` or `module` even if it does not exist
# 🐛 bug report

Parcel tries to resolve the `source` file of dependencies instead of the file specified by `main` or `module` even if the file referred to by `source` does not exist. This results in errors when importing a package that does not ship with source files.

## 🎛 Configuration (.babelrc, package.json, cli command)

Default configuration. Running `parcel serve`.

## 🤔 Expected Behavior

Parcel should import the file specified by `main` or `module` if the `source` file is not found.

## 😯 Current Behavior

Parcel always tries to resolve the `source` file of dependencies if it's specified. This fails when importing a package that does not ship with source files.

## 💁 Possible Solution

Use the  `main` or `module` field during import resolution when appropriate.

It should be enough to filter entry points for existence in the `NodeResolver`:

```diff
--- a/packages/utils/node-resolver-core/src/NodeResolver.js
+++ b/packages/utils/node-resolver-core/src/NodeResolver.js
@@ -872,7 +872,10 @@ export default class NodeResolver {
           field: entry.field,
           filename: path.resolve(pkg.pkgdir, entry.filename),
         };
-      });
+      })
+      .filter(
+          entry => fs.existsSync(entry.filename)
+      );
   }
 
   async loadAsFile({
```

It's used by the [`DefaultResolver`](https://github.com/parcel-bundler/parcel/blob/v2/packages/resolvers/default/src/DefaultResolver.js#L18) like so:

```js
    const resolver = new NodeResolver({
      fs: options.inputFS,
      projectRoot: options.projectRoot,
      // Extensions are always required in URL dependencies.
      extensions:
        dependency.specifierType === 'commonjs' ||
        dependency.specifierType === 'esm'
          ? ['ts', 'tsx', 'js', 'jsx', 'json']
          : [],
      mainFields: ['source', 'browser', 'module', 'main'],
    });
```

(If this is the correct approach I can submit the change in a PR. I was not able to test this yet.)

## 🔦 Context

I am trying to import [`@radix-ui/react-scroll-area`](https://www.npmjs.com/package/@radix-ui/react-scroll-area). This causes the build to fail:
```
× Build failed.

@parcel/core: Failed to resolve '@radix-ui/react-scroll-area' from './app/components/app.tsx'

  K:\Development\gh-dashboard\app\components\app.tsx:4:29
    3 | import styled from '@emotion/styled'
  > 4 | import * as ScrollArea from '@radix-ui/react-scroll-area'
  >   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    5 |
    6 | import { usePromise } from '../hooks/use-promise'

@parcel/resolver-default: Could not load './src/index.ts' from module '@radix-ui/react-scroll-area' found in
package.json#source

  K:\Development\gh-dashboard\node_modules\@radix-ui\react-scroll-area\package.json:5:13
    4 |   "license": "MIT",
  > 5 |   "source": "src/index.ts",
  >   |             ^^^^^^^^^^^^^^ './src/index.ts' does not exist, did you mean './dist/index.js'?'
    6 |   "main": "dist/index.js",
    7 |   "module": "dist/index.module.js",
```

## 💻 Code Sample

```
import * as ScrollArea from '@radix-ui/react-scroll-area'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.2.1`
| Node             | `17.4.0`
| npm/Yarn         | `pnpm 6.28.0`
| Operating System | `Windows 10 21H2`

### PR DESCRIPTION
**Pull request by g6123**
# ↪️ Pull Request

- Some modern package managers ([pnpm](https://pnpm.io/) and [Yarn berry with `nodeLinker: pnpm`](https://yarnpkg.com/configuration/yarnrc#nodeLinker)) save dependencies in their internal storage, and make symlinks to them in `node_modules` directory.
- This comes problematic when Parcel is resolving `source` entry, because `NodeResolver` thinks dependencies behind symlinks are actually links to workspaces in the same monorepo, which is a false assumption in this case.
- This PR tries to handle this problem by checking if the realpath to the dependency includes `node_modules`, and if it does, ignoring `source` entry.
- Fixes #7610 
- Fixes #5784 

## 💻 Examples

For example, in the case of pnpm with default settings:

```
workspace/
  node_modules/
    .pnpm/compute-scroll-into-view@1.0.17/node_modules/compute-scroll-into-view/
      package.json
    compute-scroll-into-view/ -> symlink to .pnpm/compute-scroll-into-view@1.0.17/node_modules/compute-scroll-into-view
package.json
```

When trying to import `compute-scroll-into-view` from `workspace`, `node_modules/compute-scroll-into-view/` is a symbolic link. So Parcel tries to read [`source` field of `compute-scroll-into-view`](https://github.com/stipsan/compute-scroll-into-view/blob/acbb60a4fc10f1c0264aadb7371a0e4117906f97/package.json#L88), which points to an non-existing file.

## 🚨 Test instructions

I think the included test covers sufficient cases :thinking: 

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

File: packages/utils/node-resolver-core/src/NodeResolver.js [hunk 1]
```diff
@@ -906,11 +906,14 @@ export default class NodeResolver {
...
-    // If so, we treat the module as source code rather than a pre-compiled module.
+    // If the package has a `source` field, make sure
+    // - the package is behind symlinks
+    // - and the realpath to the packages does not includes `node_modules`.
+    // Since such package is likely a pre-compiled module
+    // installed with package managers, rather than including a source code.
     if (pkg.source) {
       let realpath = await this.fs.realpath(file);
-      if (realpath === file) {
+      if (realpath === file || realpath.includes('/node_modules/')) {
```
Comment (g6123) [inline packages/utils/node-resolver-core/src/NodeResolver.js]: Let me know if this is not be a cross-platform approach..

Comment (mischnic) [reply packages/utils/node-resolver-core/src/NodeResolver.js]: This is the only other place currently that does this kind of check (using `path.sep` instead of hardcoding the slash):
https://github.com/parcel-bundler/parcel/blob/96c847b21361bcd2f7c8712752e5376e1f80b27e/packages/core/core/src/summarizeRequest.js#L22-L24

Comment (g6123) [reply packages/utils/node-resolver-core/src/NodeResolver.js]: Okay, thank you. I just wondered `fs.realpath()` normalizes path separator or not. I once copied the snippet (9c9d379) you suggested, but it seemed not a good practice to paste the same constant here and there in the codebase, so revised with `normalizeSeparators()` (255ba5b).

File: packages/utils/node-resolver-core/src/NodeResolver.js [hunk 2]
```diff
@@ -906,11 +906,17 @@ export default class NodeResolver {
...
+    // - the package is behind symlinks
+    // - and the realpath to the packages does not includes `node_modules`.
+    // Since such package is likely a pre-compiled module
+    // installed with package managers, rather than including a source code.
     if (pkg.source) {
       let realpath = await this.fs.realpath(file);
-      if (realpath === file) {
+      if (
+        realpath === file ||
+        normalizeSeparators(realpath).includes('/node_modules/')
```
Comment (devongovett) [inline packages/utils/node-resolver-core/src/NodeResolver.js]: `realpath` will already return a normalized string for the platform it is running on, so might be faster to do this instead:

```suggestion
        realpath.includes(`${path.sep}node_modules${path.sep}`)
```
