### PR TITLE
Fix renamed external imports

### LINKED ISSUE #3785: Parcel 2: Issue with multiple export with same name
# 🐛 bug report

Multiple named exports with same name causes crash in parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)

Repro here: https://github.com/lindskogen/parcel-v2-repro

But basically this code snippet causes the bug:
(The two exports named `faCircle`)

```ts
import * as React from "react";
import { faCircle as farCircle } from "@fortawesome/free-regular-svg-icons/faCircle";
import { faCircle as fasCircle } from "@fortawesome/free-solid-svg-icons/faCircle";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export interface Props {
  text: string;
}

export const Header: React.FC<Props> = () => (
  <h1>
    <FontAwesomeIcon icon={farCircle} />
    <FontAwesomeIcon icon={fasCircle} />
  </h1>
);

```

## 🤔 Expected Behavior

It should bundle the code,

## 😯 Current Behavior

```
@parcel/packager-js: Cannot read property 'buildError' of undefined
TypeError: Cannot read property 'buildError' of undefined
    at Scope.checkBlockScopedCollisions (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/scope/index.js:344:22)
    at Scope.registerBinding (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/scope/index.js:501:16)
    at Scope.registerDeclaration (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/scope/index.js:449:14)
    at Object.Declaration (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/scope/index.js:125:12)
    at NodePath._call (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/lindskogen/parcel/node_modules/@babel/traverse/lib/context.js:144:19)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 4a3f5349157
| Node             | v10.17.0
| npm/Yarn         | yarn 1.19.1
| Operating System | macOS 10.15.1

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Closes #3785

Fixes two typos.

## 💻 Examples

```js
import { foo as a } from "external/a";
import { foo as b } from "external/b";

console.log(a, b);
```

### CODE REVIEW

File: packages/shared/scope-hoisting/src/link.js [hunk 1]
```diff
@@ -248,7 +248,7 @@ export function link({
           programScope.hasBinding(imported) ||
           programScope.hasReference(imported)
         ) {
-          programScope.generateUid(imported);
+          renamed = programScope.generateUid(imported);
```
Comment (mischnic) [inline packages/shared/scope-hoisting/src/link.js]: This caused:
```js
import { foo } from "external/a";
import { foo } from "external/b";
```

File: packages/shared/scope-hoisting/src/formats/commonjs.js [hunk 2]
```diff
@@ -53,8 +53,8 @@ function generateDestructuringAssignment(env, specifiers, value, scope) {
     for (let specifier of specifiers) {
       statements.push(
         ASSIGN_TEMPLATE({
-          SPECIFIERS: specifier.key,
-          MODULE: t.memberExpression(value, specifier.value)
+          SPECIFIERS: specifier.value,
+          MODULE: t.memberExpression(value, specifier.key)
```
Comment (mischnic) [inline packages/shared/scope-hoisting/src/formats/commonjs.js]: This caused:
```js
var { a: foo } = require("external/a");
var { b: foo } = require("external/b");
```
(ObjectProperty should be other way around)

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.69s | -935.00ms 🚀 |
| Cached | 8.33s | -839.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 166.00ms | -57.00ms 🚀 |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 164.00ms | -58.00ms 🚀 |
| dist/legacy/index.js | 252.00b | +0.00b | 366.00ms | -87.00ms 🚀 |
| dist/modern/index.js | 215.00b | +0.00b | 363.00ms | -85.00ms 🚀 |
| dist/legacy/index.css | 29.00b | +0.00b | 1.28s | -106.00ms 🚀 |
| dist/modern/index.css | 29.00b | +0.00b | 1.11s | -103.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 14.00ms | +2.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 13.00ms | +3.00ms ⚠️ |
| dist/legacy/index.js | 252.00b | +0.00b | 19.00ms | +3.00ms ⚠️ |
| dist/modern/index.js | 215.00b | +0.00b | 14.00ms | +2.00ms ⚠️ |
| dist/legacy/index.css | 29.00b | +0.00b | 12.00ms | +2.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 12.00ms | +3.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 14.22s | -300.00ms |
| Cached | 13.35s | +876.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 34.53kb | +0.00b | 2.13s | +135.00ms ⚠️ |
| dist/module/index.js | 34.33kb | +0.00b | 2.12s | +132.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 34.53kb | +0.00b | 14.00ms | -3.00ms 🚀 |
| dist/module/index.js | 34.33kb | +0.00b | 9.00ms | -1.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.59m | -11.28s 🚀 |
| Cached | 10.98s | +254.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.31mb | -312.00b 🚀 | 2.00m | -7.87s 🚀 |
| dist/pdfRenderer.0c70848e.js | 1.13mb | +0.00b | 36.90s | -3.21s 🚀 |
| dist/smartMediaEditor.29d5f169.js | 601.41kb | +0.00b | 1.31m | -6.55s 🚀 |
| dist/popup.a9bec4e0.js | 284.70kb | +0.00b | 2.05m | -7.74s 🚀 |
| dist/EmojiPickerComponent.7202df5c.js | 105.88kb | +0.00b | 48.29s | -4.87s 🚀 |
| dist/Toolbar.001e4f01.js | 105.38kb | +0.00b | 1.35m | -6.25s 🚀 |
| dist/ui.e13f5d2e.js | 73.73kb | +0.00b | 49.86s | -4.99s 🚀 |
| dist/smartMediaEditor.d061a179.js | 67.38kb | +0.00b | 1.06m | -5.47s 🚀 |
| dist/component.10b390dc.js | 46.17kb | +0.00b | 43.65s | -3.20s 🚀 |
| dist/popup.37645d0d.js | 44.40kb | +0.00b | 39.51s | -6.28s 🚀 |
| dist/popup.de16c573.js | 40.69kb | +0.00b | 42.73s | -3.06s 🚀 |
| dist/popup.742fc489.js | 37.84kb | +0.00b | 38.84s | -3.32s 🚀 |
| dist/DatePicker.6844209a.js | 27.57kb | +0.00b | 48.56s | -3.17s 🚀 |
| dist/EmojiPickerComponent.bb15ebef.js | 26.66kb | +0.00b | 47.14s | -4.58s 🚀 |
| dist/esm.d429ab19.js | 25.72kb | +0.00b | 42.73s | -3.05s 🚀 |
| dist/js.adf5baf7.js | 16.54kb | +0.00b | 2.00m | -7.87s 🚀 |
| dist/workerHasher.8269e4ca.js | 11.56kb | +0.00b | 38.84s | -3.33s 🚀 |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 48.63s | -4.64s 🚀 |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 43.84s | -3.21s 🚀 |
| dist/index.css | 3.38kb | +0.00b | 1.37m | -6.23s 🚀 |
| dist/png-chunks-extract.3d8d8594.js | 3.33kb | +0.00b | 2.00m | -7.87s 🚀 |
| dist/feedback.4dda4a59.js | 2.93kb | +0.00b | 44.78s | -3.56s 🚀 |
| dist/EmojiUploadComponent.0460cc59.js | 2.91kb | +0.00b | 48.56s | -4.60s 🚀 |
| dist/component.8fa44754.js | 2.29kb | +0.00b | 43.67s | -3.20s 🚀 |
| dist/media-picker-analytics-error-boundary.c660ebe7.js | 1.92kb | +0.00b | 42.76s | -3.06s 🚀 |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 44.14s | -3.25s 🚀 |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 44.33s | -3.39s 🚀 |
| dist/16.de3f3184.js | 1.62kb | +0.00b | 43.97s | -3.23s 🚀 |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 44.40s | -3.43s 🚀 |
| dist/workerHasher.7f0e2d92.js | 1.48kb | +0.00b | 38.84s | -3.33s 🚀 |
| dist/workerHasher.30e330ec.js | 1.48kb | +0.00b | 49.28s | -4.81s 🚀 |
| dist/workerHasher.854262ce.js | 1.48kb | +0.00b | 49.30s | -4.85s 🚀 |
| dist/workerHasher.64914391.js | 1.48kb | +0.00b | 1.04m | -5.30s 🚀 |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 44.68s | -3.53s 🚀 |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 44.49s | -3.47s 🚀 |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 44.09s | -3.28s 🚀 |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 43.89s | -3.17s 🚀 |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 43.98s | -3.22s 🚀 |
| dist/code.092e0137.js | 1.28kb | +0.00b | 44.32s | -3.36s 🚀 |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 44.24s | -3.33s 🚀 |
| dist/16.51bbc68e.js | 1.23kb | +0.00b | 44.23s | -3.30s 🚀 |
| dist/component.8351f228.js | 1.23kb | +0.00b | 43.65s | -3.20s 🚀 |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 44.49s | -3.47s 🚀 |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 44.77s | -3.56s 🚀 |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 44.22s | -3.31s 🚀 |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 44.76s | -3.56s 🚀 |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 43.97s | -3.22s 🚀 |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 44.22s | -3.31s 🚀 |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 44.31s | -3.37s 🚀 |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 44.40s | -3.40s 🚀 |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 44.11s | -3.26s 🚀 |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 43.99s | -3.25s 🚀 |
| dist/16.24165259.js | 1.09kb | +0.00b | 43.98s | -3.21s 🚀 |
| dist/16.74510c56.js | 1.09kb | +0.00b | 44.09s | -3.28s 🚀 |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 44.11s | -3.26s 🚀 |
| dist/16.a79db876.js | 1.09kb | +0.00b | 43.88s | -3.18s 🚀 |
| dist/heading5.2f045997.js | 1.06kb | +0.00b | 44.77s | -3.55s 🚀 |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 43.88s | -3.17s 🚀 |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 44.23s | -3.29s 🚀 |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 44.70s | -3.56s 🚀 |
| dist/mention.9fdad24e.js | 981.00b | +0.00b | 44.52s | -3.45s 🚀 |
| dist/fallback.305c8864.js | 980.00b | +0.00b | 44.69s | -3.51s 🚀 |
| dist/heading4.63d1ca06.js | 976.00b | +0.00b | 44.76s | -3.56s 🚀 |
| dist/layout.6f66c2da.js | 962.00b | +0.00b | 44.41s | -3.44s 🚀 |
| dist/divider.160f3108.js | 940.00b | +0.00b | 44.39s | -3.41s 🚀 |
| dist/quote.88bfdca4.js | 936.00b | +0.00b | 44.62s | -3.47s 🚀 |
| dist/action.146450ba.js | 919.00b | +0.00b | 44.32s | -3.35s 🚀 |
| dist/decision.06254b93.js | 898.00b | +0.00b | 44.39s | -3.41s 🚀 |
| dist/panel-warning.59c8ef3f.js | 891.00b | +0.00b | 44.61s | -3.46s 🚀 |
| dist/list.4f623de3.js | 870.00b | +0.00b | 44.52s | -3.44s 🚀 |
| dist/heading1.65fb8482.js | 864.00b | +0.00b | 44.69s | -3.53s 🚀 |
| dist/panel-error.c2479698.js | 791.00b | +0.00b | 44.52s | -3.45s 🚀 |
| dist/panel.23cd7224.js | 788.00b | +0.00b | 44.61s | -3.46s 🚀 |
| dist/table.4ace5843.js | 780.00b | +0.00b | 44.68s | -3.53s 🚀 |
| dist/panel-success.6a7b97d7.js | 728.00b | +0.00b | 44.60s | -3.47s 🚀 |
| dist/panel-note.5ff85bdc.js | 727.00b | +0.00b | 44.60s | -3.47s 🚀 |
| dist/simpleHasher.efc670cc.js | 446.00b | +0.00b | 38.84s | -3.34s 🚀 |
| dist/simpleHasher.f8edc084.js | 446.00b | +0.00b | 49.29s | -4.81s 🚀 |
| dist/simpleHasher.884d4eb6.js | 446.00b | +0.00b | 49.30s | -4.85s 🚀 |
| dist/simpleHasher.c5e45ebc.js | 446.00b | +0.00b | 1.04m | -5.29s 🚀 |
| dist/dropzone.976debcc.js | 177.00b | +1.00b ⚠️ | 2.00m | +1.24m ⚠️ |
| dist/clipboard.976debcc.js | 177.00b | +1.00b ⚠️ | 43.62s | -3.22s 🚀 |
| dist/browser.976debcc.js | 177.00b | +1.00b ⚠️ | 1.06m | +16.55s ⚠️ |
| dist/editorView.976debcc.js | 177.00b | -1.00b 🚀 | 42.73s | -26.14s 🚀 |
| dist/media-card-analytics-error-boundary.976debcc.js | 176.00b | -5.00b 🚀 | 44.30s | -1.40m 🚀 |
| dist/16.976debcc.js | 174.00b | -5.00b 🚀 | 43.22s | -4.45s 🚀 |
| dist/component.ab65829f.js | 62.00b | +0.00b | 43.84s | -3.21s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.32mb | -312.00b 🚀 | 392.00ms | +18.00ms |
| dist/smartMediaEditor.29d5f169.js | 601.41kb | +0.00b | 169.00ms | +12.00ms ⚠️ |
| dist/popup.a9bec4e0.js | 284.70kb | +0.00b | 189.00ms | +14.00ms ⚠️ |
| dist/EmojiPickerComponent.7202df5c.js | 105.88kb | +0.00b | 137.00ms | +11.00ms ⚠️ |
| dist/Toolbar.001e4f01.js | 105.38kb | +0.00b | 132.00ms | +11.00ms ⚠️ |
| dist/media-viewer.12bd9010.js | 86.76kb | +0.00b | 172.00ms | +10.00ms ⚠️ |
| dist/card.80c210d3.js | 76.35kb | +0.00b | 173.00ms | +11.00ms ⚠️ |
| dist/ui.e13f5d2e.js | 73.74kb | +0.00b | 134.00ms | +10.00ms ⚠️ |
| dist/smartMediaEditor.d061a179.js | 67.38kb | +0.00b | 133.00ms | +11.00ms ⚠️ |
| dist/component.10b390dc.js | 46.17kb | +0.00b | 146.00ms | +10.00ms ⚠️ |
| dist/popup.37645d0d.js | 44.40kb | +0.00b | 161.00ms | +16.00ms ⚠️ |
| dist/popup.e57e7ab5.js | 43.88kb | +0.00b | 162.00ms | +16.00ms ⚠️ |
| dist/popup.de16c573.js | 40.69kb | +0.00b | 160.00ms | +15.00ms ⚠️ |
| dist/popup.742fc489.js | 37.84kb | +0.00b | 163.00ms | +14.00ms ⚠️ |
| dist/DatePicker.6844209a.js | 27.57kb | +0.00b | 131.00ms | +11.00ms ⚠️ |
| dist/EmojiPickerComponent.bb15ebef.js | 26.66kb | +0.00b | 131.00ms | +11.00ms ⚠️ |
| dist/esm.d429ab19.js | 25.72kb | +0.00b | 160.00ms | +15.00ms ⚠️ |
| dist/js.adf5baf7.js | 16.54kb | +0.00b | 164.00ms | +14.00ms ⚠️ |
| dist/workerHasher.8269e4ca.js | 11.56kb | +0.00b | 162.00ms | +16.00ms ⚠️ |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 130.00ms | +11.00ms ⚠️ |
| dist/card.f99e1597.js | 5.89kb | +0.00b | 164.00ms | +13.00ms ⚠️ |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 145.00ms | +10.00ms ⚠️ |
| dist/index.css | 3.38kb | +0.00b | 104.00ms | +9.00ms ⚠️ |
| dist/png-chunks-extract.3d8d8594.js | 3.33kb | +0.00b | 164.00ms | +14.00ms ⚠️ |
| dist/feedback.4dda4a59.js | 2.93kb | +0.00b | 132.00ms | +11.00ms ⚠️ |
| dist/EmojiUploadComponent.0460cc59.js | 2.91kb | +0.00b | 131.00ms | +11.00ms ⚠️ |
| dist/component.8fa44754.js | 2.29kb | +0.00b | 146.00ms | +11.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.c660ebe7.js | 1.92kb | +0.00b | 159.00ms | +23.00ms ⚠️ |
| dist/card.9520f336.js | 1.80kb | +0.00b | 160.00ms | +9.00ms ⚠️ |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 141.00ms | +10.00ms ⚠️ |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 139.00ms | +11.00ms ⚠️ |
| dist/16.de3f3184.js | 1.62kb | +0.00b | 144.00ms | +11.00ms ⚠️ |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 137.00ms | +11.00ms ⚠️ |
| dist/workerHasher.7f0e2d92.js | 1.48kb | +0.00b | 163.00ms | +14.00ms ⚠️ |
| dist/workerHasher.30e330ec.js | 1.48kb | +0.00b | 130.00ms | +11.00ms ⚠️ |
| dist/workerHasher.854262ce.js | 1.48kb | +0.00b | 130.00ms | +12.00ms ⚠️ |
| dist/workerHasher.64914391.js | 1.48kb | +0.00b | 129.00ms | +11.00ms ⚠️ |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 135.00ms | +11.00ms ⚠️ |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 136.00ms | +11.00ms ⚠️ |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 149.00ms | +11.00ms ⚠️ |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 144.00ms | +11.00ms ⚠️ |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 144.00ms | +12.00ms ⚠️ |
| dist/code.092e0137.js | 1.28kb | +0.00b | 139.00ms | +11.00ms ⚠️ |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 140.00ms | +11.00ms ⚠️ |
| dist/16.51bbc68e.js | 1.23kb | +0.00b | 140.00ms | +11.00ms ⚠️ |
| dist/component.8351f228.js | 1.23kb | +0.00b | 147.00ms | +12.00ms ⚠️ |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 137.00ms | +11.00ms ⚠️ |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 133.00ms | +12.00ms ⚠️ |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 141.00ms | +10.00ms ⚠️ |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 133.00ms | +11.00ms ⚠️ |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 144.00ms | +11.00ms ⚠️ |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 141.00ms | +11.00ms ⚠️ |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 139.00ms | +11.00ms ⚠️ |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 138.00ms | +11.00ms ⚠️ |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 142.00ms | +11.00ms ⚠️ |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 143.00ms | +11.00ms ⚠️ |
| dist/16.24165259.js | 1.09kb | +0.00b | 143.00ms | +11.00ms ⚠️ |
| dist/16.74510c56.js | 1.09kb | +0.00b | 150.00ms | +11.00ms ⚠️ |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 149.00ms | +18.00ms ⚠️ |
| dist/16.a79db876.js | 1.09kb | +0.00b | 145.00ms | +11.00ms ⚠️ |
| dist/heading5.2f045997.js | 1.06kb | +0.00b | 133.00ms | +11.00ms ⚠️ |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 145.00ms | +11.00ms ⚠️ |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 141.00ms | +11.00ms ⚠️ |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 134.00ms | +12.00ms ⚠️ |
| dist/mention.9fdad24e.js | 981.00b | +0.00b | 136.00ms | +11.00ms ⚠️ |
| dist/fallback.305c8864.js | 980.00b | +0.00b | 134.00ms | +11.00ms ⚠️ |
| dist/heading4.63d1ca06.js | 976.00b | +0.00b | 133.00ms | +11.00ms ⚠️ |
| dist/layout.6f66c2da.js | 962.00b | +0.00b | 137.00ms | +11.00ms ⚠️ |
| dist/divider.160f3108.js | 940.00b | +0.00b | 138.00ms | +11.00ms ⚠️ |
| dist/quote.88bfdca4.js | 936.00b | +0.00b | 135.00ms | +11.00ms ⚠️ |
| dist/action.146450ba.js | 919.00b | +0.00b | 139.00ms | +11.00ms ⚠️ |
| dist/decision.06254b93.js | 898.00b | +0.00b | 138.00ms | +11.00ms ⚠️ |
| dist/panel-warning.59c8ef3f.js | 891.00b | +0.00b | 135.00ms | +11.00ms ⚠️ |
| dist/list.4f623de3.js | 870.00b | +0.00b | 136.00ms | +11.00ms ⚠️ |
| dist/heading1.65fb8482.js | 864.00b | +0.00b | 134.00ms | +11.00ms ⚠️ |
| dist/panel-error.c2479698.js | 791.00b | +0.00b | 135.00ms | +10.00ms ⚠️ |
| dist/panel.23cd7224.js | 788.00b | +0.00b | 134.00ms | +10.00ms ⚠️ |
| dist/table.4ace5843.js | 780.00b | +0.00b | 135.00ms | +12.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.dd752a9e.js | 777.00b | +0.00b | 161.00ms | +9.00ms ⚠️ |
| dist/panel-success.6a7b97d7.js | 728.00b | +0.00b | 135.00ms | +11.00ms ⚠️ |
| dist/panel-note.5ff85bdc.js | 727.00b | +0.00b | 135.00ms | +11.00ms ⚠️ |
| dist/simpleHasher.efc670cc.js | 446.00b | +0.00b | 161.00ms | +15.00ms ⚠️ |
| dist/simpleHasher.f8edc084.js | 446.00b | +0.00b | 130.00ms | +11.00ms ⚠️ |
| dist/simpleHasher.884d4eb6.js | 446.00b | +0.00b | 129.00ms | +11.00ms ⚠️ |
| dist/simpleHasher.c5e45ebc.js | 446.00b | +0.00b | 128.00ms | +11.00ms ⚠️ |
| dist/esm.976debcc.js | 176.00b | +2.00b ⚠️ | 161.00ms | +7.00ms |
| dist/media-card-analytics-error-boundary.976debcc.js | 176.00b | +2.00b ⚠️ | 164.00ms | +13.00ms ⚠️ |
| dist/dropzone.976debcc.js | 176.00b | +2.00b ⚠️ | 159.00ms | +22.00ms ⚠️ |
| dist/clipboard.976debcc.js | 176.00b | +2.00b ⚠️ | 159.00ms | +23.00ms ⚠️ |
| dist/browser.976debcc.js | 176.00b | +2.00b ⚠️ | 147.00ms | +11.00ms ⚠️ |
| dist/16.976debcc.js | 176.00b | +2.00b ⚠️ | 140.00ms | +11.00ms ⚠️ |
| dist/editorView.976debcc.js | 176.00b | +2.00b ⚠️ | 127.00ms | +11.00ms ⚠️ |
| dist/card.aae6ebb9.js | 62.00b | +0.00b | 160.00ms | +8.00ms |
| dist/component.ab65829f.js | 62.00b | +0.00b | 146.00ms | +11.00ms ⚠️ |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/249291249212719625)**
