### PR TITLE
Don't discard invalidations when transformer throws an error

### LINKED ISSUE #6124: Elm + parcel serve unusable: File changes not detected after compilation error
# 🐛 bug report

If Elm compilation fails then `parcel serve/watch` auto-recomplitaion mostly breaks.  If the entry-point Elm file (i.e. Main.elm) is edited then recompilation will work, but if any non-entry-point Elm file is edited recompilation does not occur. Since the entry point (`Main.elm`) is very rarely touched in most Elm projects it makes `parcel serve/watch` basically unusable w/ Elm.

[SSCCE here](https://github.com/cmditch/parcel2-elm-error)

## 🎛 Configuration (.babelrc, package.json, cli command)
https://github.com/cmditch/parcel2-elm-error/blob/master/package.json

## 🤔 Expected Behavior

Every time an Elm file is touched, regardless of the compilation state, `parcel serve/watch`should recompile the project.

## 💁 Possible Solution

No idea. The watcher seems to work on all Elm files, but only when the last compilation was a success.

## 💻 Code Sample
Clone and run `yarn; yarn hot` in the [SSCCE here](https://github.com/cmditch/parcel2-elm-error) and see [instructions here](elm-error/blob/master/src/elm/Init.elm#L3) to reproduce.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-nightly.639+059d502f
| Node             |  12.22.0
| npm/Yarn         |  yarn 1.22.10
| Operating System | macOS 10.15.7

Thanks,
Coury

### PR DESCRIPTION
**Pull request by mischnic**
No invalidation gets added to the graph if `runTransform` throws an error. So instead catch it and return the error along with invalidations that were added along the way

Closes https://github.com/parcel-bundler/parcel/issues/6124

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.36s | +118.00ms |
| Cached | 371.00ms | +40.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 105.00ms | -551.00ms 🚀 |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 710.00ms | +54.00ms ⚠️ |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 710.00ms | +54.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.html | 826.00b | +0.00b | 1.13s | -90.00ms 🚀 |
| dist/modern/index.html | 749.00b | +0.00b | 1.13s | -92.00ms 🚀 |
| dist/legacy/index.c1bc86aa.css | 94.00b | +0.00b | 1.27s | -140.00ms 🚀 |
| dist/modern/index.57a95cbe.css | 94.00b | +0.00b | 1.27s | -139.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.69s | -242.00ms |
| Cached | 467.00ms | -12.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.19m | +195.00ms |
| Cached | 1.54s | +2.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/editorView.af442747.js | 594.92kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/popup.64bc9a82.js | 209.67kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/Toolbar.1af0e801.js | 107.23kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/Modal.cd71eaf3.js | 45.33kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/ui.5d3f7adc.js | 14.94kb | +0.00b | 53.74s | +13.85s ⚠️ |
| dist/smartMediaEditor.48c8cf63.js | 13.25kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/dropzone.39132d0c.js | 12.16kb | +0.00b | 53.73s | +13.84s ⚠️ |
| dist/EmojiPickerComponent.0482d6c0.js | 3.73kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/dropzone.55bef257.js | 3.29kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/clipboard.df70240c.js | 2.93kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/ResourcedEmojiComponent.667554b4.js | 2.12kb | +0.00b | 53.74s | +13.85s ⚠️ |
| dist/browser.4e039ed7.js | 1.69kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/media-card-analytics-error-boundary.c718a9a7.js | 1.12kb | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/media-picker-analytics-error-boundary.8b2547e5.js | 966.00b | +0.00b | 53.73s | +13.85s ⚠️ |
| dist/simpleHasher.fc0d6100.js | 643.00b | +0.00b | 53.73s | +13.85s ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.43s | +4.00ms |
| Cached | 406.00ms | +18.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/320622732508136019)**

**Comment by mischnic** [comment]
Somehow returning the ThrowableDiagnostic object as opposed to throwing it strips the `diagnostics` property on the other thread. Might be a difference between structured cloning vs v8's serialization...

**Comment by mischnic** [comment]
Turns out that when throwing an error the worker farm automatically serializes
https://github.com/parcel-bundler/parcel/blob/4745cd3023f8d5a5adcf9e565d5b82d1418dc262/packages/core/workers/src/WorkerFarm.js#L309

and deserializes
https://github.com/parcel-bundler/parcel/blob/4745cd3023f8d5a5adcf9e565d5b82d1418dc262/packages/core/workers/src/WorkerFarm.js#L337-L339
 the ThrowableDiagnostic. So I'm doing that manually now for that added `error` property on the return value.

**Comment by objarni** [comment]
Would love to test this out. Anyway I can help?

File: packages/core/integration-tests/test/cache.js [hunk 1]
```diff
@@ -5836,6 +5836,49 @@ describe('cache', function () {
...
+      );
+      assert.strictEqual(output1, 'a');
+
+      // Change included file
+      await overlayFS.writeFile(path.join(fixture, 'included.txt'), 'ERROR');
+      event = await getNextBuild(b);
+      invariant(event.type === 'buildFailure');
+      assert.strictEqual(event.diagnostics[0].message, 'Custom error');
+
+      // Change included file back
```
Comment (mischnic) [inline packages/core/integration-tests/test/cache.js]:
```suggestion
      // Clear transformer error
```

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.79s | -0.00ms |
| Cached | 291.00ms | -0.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.98s | +82.00ms |
| Cached | 416.00ms | -15.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.c5bb83f1.png | 246.00b | +0.00b | 4.09s | -584.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 58.34s | -479.00ms |
| Cached | 1.40s | +33.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/editorView.af442747.js | 594.92kb | +0.00b | 32.49s | -11.63s 🚀 |
| dist/popup.64bc9a82.js | 209.67kb | +0.00b | 32.48s | -11.64s 🚀 |
| dist/Toolbar.1af0e801.js | 107.23kb | +0.00b | 32.49s | -11.63s 🚀 |
| dist/Modal.cd71eaf3.js | 45.33kb | +0.00b | 32.48s | -11.64s 🚀 |
| dist/ui.5d3f7adc.js | 14.94kb | +0.00b | 32.49s | -11.64s 🚀 |
| dist/smartMediaEditor.48c8cf63.js | 13.25kb | +0.00b | 32.48s | -11.64s 🚀 |
| dist/dropzone.39132d0c.js | 12.16kb | +0.00b | 32.48s | -11.64s 🚀 |
| dist/EmojiPickerComponent.0482d6c0.js | 3.73kb | +0.00b | 32.49s | -11.64s 🚀 |
| dist/dropzone.55bef257.js | 3.29kb | +0.00b | 32.49s | -11.63s 🚀 |
| dist/clipboard.df70240c.js | 2.93kb | +0.00b | 32.48s | -11.64s 🚀 |
| dist/ResourcedEmojiComponent.667554b4.js | 2.12kb | +0.00b | 32.49s | -11.64s 🚀 |
| dist/browser.4e039ed7.js | 1.69kb | +0.00b | 32.48s | -11.64s 🚀 |
| dist/media-card-analytics-error-boundary.c718a9a7.js | 1.12kb | +0.00b | 32.48s | -11.64s 🚀 |
| dist/media-picker-analytics-error-boundary.8b2547e5.js | 966.00b | +0.00b | 32.49s | -11.64s 🚀 |
| dist/simpleHasher.fc0d6100.js | 643.00b | +0.00b | 32.49s | -11.64s 🚀 |

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.27s | -3.00ms |
| Cached | 341.00ms | -19.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 579.68kb | +0.00b | 4.64s | -427.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/320985847952310867)**

**Review by devongovett — APPROVED** [review]

**Comment by n1k0** [comment]
Great, thank you so much folks <3 Do we have an idea when this will be released?

Edit: Sorry, I just realized it shipped along v2.2.1 already. And… it solved the very last issue I had with Parcel v2 🎉  

You're amazing, keep up the good work 👍 🙏

**Comment by objarni** [comment]
Thanks for your efforts!

Did some testing with parcel 2.2.1 and a small Elm app (https://github.com/objarni/KataDB/ ) with following setup:

    npm install
    npm start

`npm start` is a shorthand for "parcel".

Observations using Sublime Text's Ctrl+S to save and Firefox browser:

* Modifying title in `src/index.html` hotreloads
* Changing string "Filter by tag" in `src/Main.elm` hotreloads
* Changing string "Most recently used" in `src/KataDb.elm` DOES NOT hotreload, however hitting Ctrl+R in Firefox does refresh the page/app, so rebuilding of the Elm app has probably happened "behind the scenes" but not percolated to the surface. Edit: indeed rebuilding does happen, I can see the terminal "Built in 66ms" flashing "Building" when saving `KataDb.elm`!

Hypothesis: hotreloading works for html files and the "first" Elm file (Main.elm), but not dependent .elm files like KataDb.

**Comment by w0rm** [comment]
@objarni I imagine hot reloading would keep the current model and swap out update and view. `KataDb.elm` contains a constant that is used to initiate the model, therefore changing it doesn't hot reload at runtime.

**Comment by objarni** [comment]
@w0rm that makes sense! Do you have any advice on what would trigger a re-init of the model except refreshing page?

**Comment by w0rm** [comment]
@objarni I think manually refreshing the page is probably acceptable in such cases. It is a non trivial task for the hot reload to tell apart this type of change.
