### PR TITLE
Fix: join srcset in source with ", "

### LINKED ISSUE #7884: picture srcset missing space
# 🐛 bug report

When creating a picture element based on the [documentation](https://parceljs.org/features/production/#image-optimization|) Parcel removes the space between the 2 images when using more than one srcset image.

Source html:
```
<picture>
  <source type="image/webp" srcset="image.jpg?as=webp&width=400, image.jpg?as=webp&width=800 2x">
  <source type="image/jpeg" srcset="image.jpg?width=400, image.jpg?width=800 2x">
  <img src="image.jpg?width=400" width="400">
</picture>
```

after running parcel:
Schermafbeelding 2022-04-01 om 20 24 44

When adding the space manually with the dev tools it does load the image.

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration I just run from the commandline:
`npm run parcel src/index.html`
`npm run parcel build src/index.html`

## 🤔 Expected Behavior

I would expect the space to be here so it loads the image in the browser.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | v16.13.0
| npm/Yarn         | 8.1.0
| Operating System | MacOS Big Sur 11.6.5

### PR DESCRIPTION
**Pull request by Shinyaigeek**
# ↪️ Pull Request

Fixes: #7884 

I found this is parcel’s issue. htmlnano depends on [srcset](https://github.com/sindresorhus/srcset), npm module to parse srcset attribute and after https://github.com/sindresorhus/srcset/pull/11 PR was merged `srcset` **module** cannot parse srcset **attribute** without whitespace after “,” because `hoge.png,bar.png` is a valid URL.

However, parsel joins multiple image URLs in srcset **attribute** with “,” so this issue happens. parcel should join multiple image URLs in srcset **attribute** with “, “(with space), so I fixed so.

## 💻 Examples

```html
<source srcset="hoge.png?as=webp&width=400, hoge.png?as=webp&width=800 2x">
```

into transformed into above by HTMLTransformer

```html
<source srcset="hoge.HASH.png,hoge.HASH.png 2x">
```

but `srcset` module cannot parse this srcset **attribute** as a two image URLs.

## 🚨 Test instructions

I fixed html srcset integration testcase to check output HTML's srcset is valid.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
https://html.spec.whatwg.org/multipage/images.html#srcset-attribute:

> If present, its value must consist of one or more image candidate strings, each separated from the next by a U+002C COMMA character (,). If an image candidate string contains **no descriptors and no ASCII whitespace after the URL**, the following image candidate string, if there is one, **must** begin with one or more ASCII whitespace.

**Review by mischnic — APPROVED** [review]

File: packages/transformers/html/src/dependencies.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ function collectSrcSetDependencies(asset, srcset, opts) {
     newSources.push(pair.join(' '));
   }
 
-  return newSources.join(',');
+  return newSources.join(', ');
```
Comment (wbinnssmith) [inline packages/transformers/html/src/dependencies.js:105]: might be worth a comment explaining the significance of the trailing space

Comment (Shinyaigeek) [reply packages/transformers/html/src/dependencies.js:105]: Sorry for late response, [b19e0af](https://github.com/parcel-bundler/parcel/pull/7918/commits/b19e0af62077e97e2baebde610a93f684db4f4a4) 👍

**Review by devongovett — APPROVED** [review]
