### PR TITLE
HTML bundle serving bug.

### LINKED ISSUE #782: 🐛 publicURL with development server
### 🎛 Configuration (.babelrc, package.json, cli command)
`parcel src/index.html --public-url ./`
or 
`parcel src/index.html --public-url /`

### 🤔 Expected Behavior

The site should be served at `localhost:1234`.

### 😯 Current Behavior

- with `parcel src/index.html --public-url ./`:
	- `http://localhost:1234/` properly serves `index.html`
	- every request serves index.html (i.e. `http://localhost:1234/423958b25b168623f5a455b67f81b487.js` returns the `index.html` file)

- with `parcel src/index.html --public-url /`:

	- http://localhost:1234/ returns a 404
	- everything works when navigating to `http://localhost:1234/index.html`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.5.1
| Node             |v9.5.0
| npm/Yarn         |yarn 1.3.2
| Operating System |macOS 10.12.6

### PR DESCRIPTION
**Pull request by ry**
When serving HTML bundle with publicUrl="/", allow the server to send static assets other than html.

Fixes #782

### CODE REVIEW

File: src/Server.js [hunk 1]
```diff
@@ -49,6 +50,11 @@ function middleware(bundler) {
       } else {
         // Otherwise, serve the file from the dist folder
         req.url = req.url.slice(bundler.options.publicURL.length);
+        // If we're serving an html bundle, and the requested path has not file
+        // extension, serve the index.html. Otherwise go to the file server.
+        if (bundler.mainAsset.type === 'html' && path.extname(req.url) == "") {
```
Comment (DeMoorJasper) [inline src/Server.js]: This would break any file that doesn't have an extension?

Comment (ry) [reply src/Server.js]: Currently only HTML is served, so it wouldn't change the behavior. But it's true that it will not serve files without extensions - but I'd argue that is desired behavior for single page apps.

**Comment by davidnagli** [comment]
@ry @DeMoorJasper Is this a duplicate of #838?

I noticed that #838 closes this PR 🤔 🤷‍♂️

**Comment by devongovett** [comment]
Thanks!

File: src/Server.js (hunk 1 above)
Comment (pulpdood) [reply src/Server.js]: I need to verify my domain for Apple Pay for my frontend Stripe Elements app, and this requires serving a static file without a file extension, so there is a use case for this.
