### PR TITLE
Safe cssnano transforms by default

### LINKED ISSUE #698: @font-face files omitted when building with parcel build index.html
```javascript
import { h, app } from 'hyperapp';
import 'normalize.css';
import 'typeface-varela-round';
import './index.css';
```

This works fine when running `parcel index.html` but it does not work using `parcel build index.html`
Somehow, the typeface file gets omitted. The only way it'll work is if I manually copy the @font-face declaration to another css file that already contains some other css.

### PR DESCRIPTION
**Pull request by olizilla**
Pass `{safe: true}` to cssnano by default, to avoid the dangers of the advanced transforms that it would enable by default in cssnano@3.x

Adds a test (well co-opts an existing test) to ensure that @font-face files make it through to the final css bundle when `{ production: true }`

Once cssnano v4 is finally released as stable, the default options can be removed, as cssnano 4 will default to safe transforms only.

Fix #698

### CODE REVIEW

File: src/transforms/postcss.js [hunk 1]
```diff
@@ -51,7 +51,15 @@ async function getConfig(asset) {
 
   if (asset.options.minify) {
     config.plugins.push(
-      cssnano((await asset.getConfig(['cssnano.config.js'])) || {})
+      cssnano(
+        (await asset.getConfig(['cssnano.config.js'])) || {
```
Comment (DeMoorJasper) [inline src/transforms/postcss.js]: Maybe change this to Object.assign?
So config doesn't overwrite defaults but appends them

Comment (olizilla) [reply src/transforms/postcss.js]: That's reasonable, but how would we communicate the net result to users. I think it's easier to reason about if we just use the `cssnano.config.js` as provided (_advanced user, let them choose_), and otherwise, just use safe defaults.

Comment (DeMoorJasper) [reply src/transforms/postcss.js]: Alright, fair enough
