### PR TITLE
More bugs

### LINKED ISSUE #6393: Parcel 2 doesnt send file change over HMR
# 🐛 bug report

The changed made to the files are programmatic.
These are the events emitted by the file-system on a single change (I am not sure why so many, but that shouldn't be relevant.):
```
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html CLOSE_WRITE,CLOSE 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html ACCESS 
/tmp/parcel_watch098676075/index.html CLOSE_NOWRITE,CLOSE 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html CLOSE_WRITE,CLOSE 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html ACCESS 
/tmp/parcel_watch098676075/index.html CLOSE_NOWRITE,CLOSE 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html CLOSE_WRITE,CLOSE 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html ACCESS 
/tmp/parcel_watch098676075/index.html CLOSE_NOWRITE,CLOSE 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html CLOSE_WRITE,CLOSE 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html ACCESS 
/tmp/parcel_watch098676075/index.html CLOSE_NOWRITE,CLOSE 
```
The files are changed in the `--dist-dir` given to parcel, so the page is rebuild successfully, hover not send over HMR

When editing with vscode:
```
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html MODIFY 
/tmp/parcel_watch098676075/index.html CLOSE_WRITE,CLOSE 
/tmp/parcel_watch098676075/index.html OPEN 
/tmp/parcel_watch098676075/index.html ACCESS 
/tmp/parcel_watch098676075/index.html CLOSE_NOWRITE,CLOSE 
```

The page is rebuild successfully and send over HMR

No configuration.
Run with `parcel File1 File2 --hmr-port 8989 --dist-dir Output_directory`

## 🤔 Expected Behavior

With the first series of events, HMR should be triggered, not just page building.

## 😯 Current Behavior

Currently the page is built, but not send over HMR

## 💁 Possible Solution

Always send the page over HMR when rebuilding

## 🔦 Context

I was trying to get my page to automatically rebuild after editing some templates. I have a small tool to compile these templates into a website I want to run through parcel.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2 beta 3.1
| Node             |    v12.22.0
| npm/Yarn         | 7.15.1
| Operating System | arch linux june 2nd

### PR DESCRIPTION
**Pull request by devongovett**
* Reloads the page if multiple assets changed and not all of them were accepted by HMR. This happens e.g. when changing an HTML file with Tailwind. The CSS gets accepted, but the HTML does not, and the page doesn't get reloaded currently. Fixes #6393.
* Fixes React Fast Refresh runtime not being applied with the new automatic JSX runtime, which doesn't require a dependency on `"react"` to be in the file. Now we also look for `"react/jsx-runtime"`.
* If the resolver failed but then the error was fixed (e.g. file didn't exist and it was created), we didn't trigger a rebuild and you had to restart Parcel. This was because the invalidations were never added to the graph. Now we do this before throwing the error.
* `new URL('something', import.meta.url)` was getting transformed into a require of a runtime and returning a string instead of an actual URL object. Now it's transformed into `new URL(require('something'))` instead.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.84s | -54.00ms |
| Cached | 540.00ms | -18.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 299.00ms | +40.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 264.00ms | -32.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.91s | +240.00ms |
| Cached | 469.00ms | -28.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/303533495664247361)**

File: packages/core/core/src/requests/PathRequest.js [hunk 1]
```diff
@@ -311,7 +343,11 @@ export class ResolverRunner {
     }
 
     if (dep.isOptional) {
-      return null;
+      return {
+        assetGroup: null,
+        invalidateOnFileCreate,
```
Comment (wbinnssmith) [inline packages/core/core/src/requests/PathRequest.js:348]: 😁

**Review by wbinnssmith — APPROVED** [review]
